### ISSUE TITLE
pathwiz as a chemical substance

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1214] opened 2021-02-02 19:25 UTC
Name: Akt (PathWhiz.ElementCollection:342)
Id: PathWhiz.ElementCollection:342
Category: biolink:ChemicalSubstance

**Comment by saramsey** [comment] 2021-02-02 20:45
Issue confirmed. Classifying this as a bug.

**Comment by saramsey** [comment] 2021-02-02 20:45
Our fix will be to change these "Element Connection" type nodes to have biolink category `biolink:MolecularEntity`.

**Comment by saramsey** [comment] 2021-02-02 20:47
Yes, @ericawood is the correct person to tag on this (they wrote the ETL script); however, I have already implemented a fix. I am thus tagging this issue "verify this fix in the next KG2 build".

**Comment by saramsey** [comment] 2021-02-02 21:28
Second fix because I think we should also be classifying `PathWhiz.Bound:` nodes as `biolink:MolecularEntity` and not `biolink:ChemicalSubstance`.

**Comment by ericawood** [comment] 2021-03-06 20:09
This appears fixed in KG2.5.2:
```
{
  "iri": "https://pathbank.org/lims#/element_collections/342",
  "category_label": "molecular_entity",
  "full_name": "Akt",
  "deprecated": "False",
  "name": "Akt",
  "provided_by": "PathWhiz:",
  "id": "PathWhiz.ElementCollection:342",
  "category": "biolink:MolecularEntity",
  "update_date": "2019-09-13 00:27:20"
}
```
```
{
  "iri": "https://pathbank.org/lims#/bounds/16",
  "category_label": "molecular_entity",
  "deprecated": "False",
  "provided_by": "PathWhiz:",
  "id": "PathWhiz.Bound:16",
  "category": "biolink:MolecularEntity",
  "update_date": "2019-08-17 05:30:36"
}
```

**Closed by ericawood** 2021-03-06 20:09 UTC
Labels: bug, kg2, verify this fix in next KG2 build
