### ISSUE TITLE
Retrain drug re-purposing ML model on KG2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#758] opened 2020-05-20 18:20 UTC
@finnagin Just do what you did before, but this time with KG2 instead of KG1. Let me know if you need more computational resources for the node2vec part.

**Comment by finnagin** [comment] 2020-05-20 18:33
@dkoslicki I think I may be able to do it on finnkg2.rtx.ai which has 128GB of ram

**Comment by dkoslicki** [comment] 2020-05-20 18:34
Awesome!

**Comment by finnagin** [comment] 2020-05-22 03:16
@dkoslicki I tried running node2vec on finnkg2 but unfortunately it runs out of ram on kg2.

**Comment by dkoslicki** [comment] 2020-05-25 15:18
@finnagin If you send me links to the code and data, I can run it on my 1TB RAM machine and send you the results.

**Comment by finnagin** [comment] 2020-05-27 17:06
@dkoslicki that would be perfect. I was going to use kg2dev with 256gb of ram but that would be even better. I've sent code and the file to you on slack.

**Comment by finnagin** [comment] 2020-05-27 19:14
Just updating this issue from our discussion on slack:

* ran out of ram with the first set of parameters tried. 
* Trying again with reduced dimensions, random walk length, and number of random walks per node.
* If this doesn't work considering looking into using [graphSAGE](http://snap.stanford.edu/graphsage/) instead as that is less memory intense.

**Comment by dkoslicki** [comment] 2020-05-27 20:14
`node2vec` ran out of 1TB memory even using:
```
q=5
p=1
e=5
d=128
l=200
r=10
```
So may need to move to graphSAGE

**Comment by chunyuma** [comment] 2020-06-15 14:21
For update, I tried to run GraphSage with parameters: 20% validation data (total 5,580,155), 200 walk length, 10 number of walks and 256 embedding dimension on 1TB ram machine. It also ran out of memory. The main problem is that using 80% of data as training data generates a 113G random walk file which I guess is too big to crash down 1TB ram. I'm trying to increase 20% to 30% for validation data and reduce to 70% of data as training so that it should reduce the size of random walk file. But I can't guarantee it will be small adequate to run. Another way that we can reduce the size of random walk file is to reduce the `walk length` and `number of walks`. But I think `l=200` and `r=10` are small enough. They can't be decreased anymore otherwise it might affect the graph embedding as our graph is big.

**Comment by chunyuma** [comment] 2020-06-18 03:47
NEW UPDATE: I successfully ran GraphSage for KG2 with 70% training data and 30% validation data, 5 number of walks and 50 walk length. 

Next step is to increase number of walks and walk length gradually until it runs out of memory.

**Comment by dkoslicki** [comment] 2020-06-18 13:09
@chunyuma Fantastic that you were able to get it to run! Given this is the most time consuming step, do you want to run the embeddings through the random forest training just so we get an idea of the performance?

**Comment by chunyuma** [comment] 2020-06-18 15:07
@dkoslicki, sure, checking its performance via random forest is a good idea because there are a few parameters in GraphSage for which I have no idea what is the most appropriate value (eg. minibatch size, maximum node degree, number of negative samples). 

I think I can still use `semmed_tp.csv`, `mychem_tp.csv`, `mychem_tp_umls.csv` and `ndf_tp.csv` as positive examples and `semmed_tn.csv`, `mychem_tn.csv`, `mychem_tn_umls.csv` and `ndf_tn.csv`as negative, right? They should be also in KG2?

**Comment by dkoslicki** [comment] 2020-06-18 22:32
Yes, they should be in KG2, but check with @finnagin to see if identifiers have changed and/or if more training data is available with the new semmeddb implementation mentioned at the recent all hands meeting

**Comment by chunyuma** [comment] 2020-06-18 23:38
For KG2, I'm wondering why most drugs (`chemical_substance`) pulled by using the `pull_drugs` method in [this script](https://github.com/RTXteam/RTX/blob/demo/code/reasoningtool/MLDrugRepurposing/PullGraph.py) which called cypher query `match (n:chemical_substance) with distinct n.id as id, n.name as name return id, name` are not in the graph pulled by using the `pull_graph` method in the same script which called cypher query `match (n)-[r]-(m) where m<>n and type(r)<>"contraindicated_for" and type(r)<>"indicated_for" with distinct n as node1, m as node2 return node1.id as source, node2.id as target`. 

By using `pull_graph` method, I got 57,468,556 edges from KG2. And I got 2,102,899 drugs by using `pull_drugs`. However, only 258,332 out of 2,102,899 were found in 57,468,556 edges. Does this mean most of drugs are singleton?

For disease (`phenotypic_feature` and `disease`), I got 325,283 of which 322,964 are found in the graph.

**Comment by finnagin** [comment] 2020-06-19 04:13
@chunyuma That or they are connected only by a "indicated_for" or "contraindicated_for" edge since those are excluded.

**Comment by chunyuma** [comment] 2020-06-19 04:45
thanks @finnagin, I see!

**Comment by chunyuma** [comment] 2020-06-19 15:11
The performance of GraphSage with `d=256`, `l=100`, `r=5` and 70% training data is not bad. 

![Figure3](https://user-images.githubusercontent.com/20031672/85147945-89910600-b21d-11ea-9bea-79c7b205fe00.png)

![Figure1](https://user-images.githubusercontent.com/20031672/85147959-8d248d00-b21d-11ea-8a0f-8f5d523beb46.png)

**Comment by dkoslicki** [comment] 2020-06-19 15:36
Nice! That random pairs graph is especially good! Let’s go ahead and crank up the parameters like you suggested (to see when it runs out of memory), and see if we can’t get that AUC a bit better!

**Comment by chunyuma** [comment] 2020-06-26 14:15
@dkoslicki. here is the result of GraphSage with `d=256`, `l=100`, `r=5` and 80% training data.  The increased performance is not obvious and I think we can keep using 70% training data. The advantage of using 70% training data is that we can use higher length of random walk (l) and number of random walk (r) because of a smaller size of data set. The next step I will explore is how much performance the length of random walk and number of random walk can improve. I tried running GraphSage with  `d=256`, `l=150` and `r=10` for 70% training data and it ran out of memory. I guess `l=150` and `r=8` might be the most appropriate but need to be further tested. 

I'm running `d=256`, `l=100`, `r=8` to see how many increase it can get compared with `d=256`, `l=100`, `r=5` for 70% training data. Then I might try `d=256`, `l=150`, `r=5`. This might help to see which one can better facilitate the performance so that we can better balance these two parameters. 

![Figure3](https://user-images.githubusercontent.com/20031672/85864012-f4988a80-b791-11ea-9ab0-a88c9485d9a8.png)

![Figure1](https://user-images.githubusercontent.com/20031672/85863998-ef3b4000-b791-11ea-87c1-69aa34afbad3.png)

**Comment by dkoslicki** [comment] 2020-06-26 23:55
That sounds like a good plan @chunyuma! Thanks for the update (and I agree that the 70-80% change doesn’t increase performance enough to warrant going with 80%), so parameter tuning makes sense from this point.

**Comment by chunyuma** [comment] 2020-07-09 20:58
Update: The retraining process is done. Based on our limited computational resource, the final parameters of GraphSage which gets the best performance is:
- the length of random walk (l): 100
- the number of random walk (r): 8
- the percentage of data used for training: 70%
- dimension of embedding vector: 512
- training layer: 2
- batch size: 512
- the number of neighbors: 96

The two diagrams below show the model performance. 

![Figure1](https://user-images.githubusercontent.com/20031672/87089565-9beed600-c204-11ea-80f6-7aa90da93b12.png)

![Figure3](https://user-images.githubusercontent.com/20031672/87089575-9ee9c680-c204-11ea-9a4a-4a001d70f568.png)

I'm going to store the final `*.pkl`, '*.emb' and `map.csv` on `arax.rtx.ai` server. @dkoslicki, do I need to replace the original `LogModel.pkl`, `rel_max.emb.gz` and `map.csv` in `predict_drug_treats_disease.py`? I think we should modify `predict_drug_treats_disease.py` script and set an option to choose `kg`.

**Comment by dkoslicki** [comment] 2020-07-09 21:03
@chunyuma Excellent! And yes, I think you will need to overhaul everything `LogModel.pkl`, `rel_max.emb.gz` etc. Since some of these files are going to be large, we can use the same "check if file exists and if not scp it from `arax.rtx.ai` paradigm. Note too that due to the Eric's NodeSynonymizer, I don't think we will need to set an option to choose a KG. We just need to be able to: when presented with a pair of curies, find what they correspond to in the `map.csv` file using the NodeSynonymizer and then feed them into the random forest predictor. i.e. `predict_drug_treats_disease.py` will need to be re-factored a bit.

This was brief as I'm about to jump on another meeting, so LMK if more detail is needed.

**Comment by chunyuma** [comment] 2020-07-09 21:43
> find what they correspond to in the map.csv file using the NodeSynonymizer and then feed them into the random forest predictor.

@dkoslicki, I think what you mean here is to normalize both a pair of curies and the curie name in `map.csv` by using NodeSynonymizer and then find the match,  right?

**Comment by dkoslicki** [comment] 2020-07-09 22:35
> @dkoslicki, I think what you mean here is to normalize both a pair of curies and the curie name in `map.csv` by using NodeSynonymizer and then find the match, right?

I mean the following: In the current format, the `map.csv` looks like:
```
<snip>
GO:0089722,43892
GO:0090001,43893
GO:0090006,43894
GO:0090008,43895
GO:0090009,43896
GO:0090010,43897
GO:0090011,43898
GO:0090012,43899
GO:0090013,43900
<snip>
```
So if you call `probability = self.pred.prob_single(source_curie, target_curie)`, then you should be checking if `source_curie` and `target_curie` are synonyms for anything in `map.csv` (eg maybe FAKECURIEPREFIX:123 is synonymous with GO:0090013 and so should be mapped to node 43900 in the ML model). This is currently done [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L93-L98) and [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L36-L56), but will need to be changed a bit since I assume that `known_curies` used [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L31-L34) may be a bit too large to store in memory, and so should be read from a sqlite database or the like.

I don't think you need to be doing anything with names...

**Comment by chunyuma** [comment] 2020-07-13 03:52
@dkoslicki, after the `predict_drug_treats_disease` used the retrained data, it ran pretty pretty slow. These [lines](https://github.com/RTXteam/RTX/blob/c23522881813ec9260c4595e5ced47bfbe808ece/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L192-L201) and these [lines](https://github.com/RTXteam/RTX/blob/c23522881813ec9260c4595e5ced47bfbe808ece/code/ARAX/ARAXQuery/Overlay/predictor/predictor.py#L44-L46) are the most time-consuming. Since we used `NodeSynonymizer` to find synonyms for `drug` and `disease`, some of pairs might produce more than 500 combinations of which each costs around 1 second to get the probability. So some of drug-disease pairs might cost more than 500 seconds. This is too long. Perhaps we can modify the script to make it run in parallel and make it faster but this depends on how many computational cores of the machine where we ran. So I don't think this can help too much.

**Comment by dkoslicki** [comment] 2020-07-13 16:17
@chunyuma Before investigating your own parallelization, perhaps investigate if it's better to do all the ~500 predictions in one go. [The documents](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.predict_proba) indicate this can be done all in one go (and [is parallelized already](https://github.com/scikit-learn/scikit-learn/blob/fd237278e/sklearn/ensemble/_forest.py#L673-L686)), and should only require minor re-factoring of [predictor.py](https://github.com/RTXteam/RTX/blob/c23522881813ec9260c4595e5ced47bfbe808ece/code/ARAX/ARAXQuery/Overlay/predictor/predictor.py). I.e. Build up a large `X` (number of rows = number of pairs of curies) in `predictor.prob_single`, and then pass this to `model.predict_proba` and return the largest non-Inf result.

**Comment by edeutsch** [comment] 2020-07-13 21:57
I'm not certain I understand where the bottleneck is, but if you are finding it is in the NodeSynonymizer, there are likely ways to speed it up. Synonyms can be requested in batches (of 500 for example), and those batch queries are much faster than looping through them. But maybe that's not the issue..

**Comment by chunyuma** [comment] 2020-07-13 22:01
@edeutsch, no worries, the problem is not due to the NodeSynonymizer. I'm working on the way that was suggested by @dkoslicki and also trying to store the retrained data in a sqlite database to speed up the data read-in process.

**Comment by chunyuma** [comment] 2020-07-14 17:09
@dkoslicki, the `running slow` problem was solved through the use of database and parallelization. It also passed all `predict_drug_treats_disease` associated tests within `test_ARAX_overlay.py` and `test_example_2` test within `test_ARAX_workflows.py`. I didn't test the other `predict_drug_treats_disease` associated tests within `test_ARAX_workflows.py` because they involve `overlay_clinical_info` and thus they should run slow right now until I complete issue #875.

Please check it in `issue758` branch. If there is no problem, I can merge it to `master` branch and might close this issue.

**Comment by dkoslicki** [comment] 2020-07-14 22:23
Great work @chunyuma! It does appear to be running faster (and passes all the tests). It is still a bit slower:
Old version:
```
15.34s call     test_ARAX_overlay.py::test_predict_drug_treats_disease_virtual
4.56s call     test_ARAX_overlay.py::test_predict_drug_treats_disease_attribute
```
New version:
```
17.94s call     test_ARAX_overlay.py::test_predict_drug_treats_disease_attribute
17.88s call     test_ARAX_overlay.py::test_predict_drug_treats_disease_virtual
```
But I guess that's what we get when we move from KG1 to KG2 (bigger model/data + more synonyms to test).

Before you merge to master, can you check these couple of fixme's/todo's and see if they are relevant (or can be removed):

1. [here](https://github.com/RTXteam/RTX/blob/6df090e82cdc492ca735d44b8de59d4a1b6afc6c/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L67) Since we are now using KG2
2. [here](https://github.com/RTXteam/RTX/blob/6df090e82cdc492ca735d44b8de59d4a1b6afc6c/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L75-L79) Do we still need this given that the even though KG1 uses the wrong CURIE prefix, the node synonymizer uses correct ones? Depends on how you populated the sqlite database

Lastly, you should include somewhere in the repo (probably the `predictor` folder or `retrain_data` subfolder) the script(s) that you used to do the re-training (even if it includes paths relevant only to our lab server, these can be moved to variables in a bash script at some point), since this re-training will need to be done yet again when the new KG2 comes out a number of months from now. That, and we want something to point to if/when people ask us how this model makes its predictions or how it was trained.

**Comment by chunyuma** [comment] 2020-07-15 03:50
> But I guess that's what we get when we move from KG1 to KG2 (bigger model/data + more synonyms to test).

@dkoslicki, you're right. This should be normal for a bit slower than the old version because KG1 has much less synonyms to do the prediction. But it has already been much faster by using the sqlite database and parallelization.

> 1. here Since we are now using KG2

@dkoslicki, it should not matter if we use KG1 or KG2 in `get_normalizer_results` because we actually used `equivalent_identifiers` which should be the same for KG1 and KG2 based on what Eric told me. I know in #919 you mentioned that perhaps `get_equivalent_nodes` might be speed up the code but actually I compared these two methods and their difference can be ignored (the difference in the speed of retrieving a single curie is negligible). We can't use the `batch` in `get_equivalent_nodes` because we have to pair a single `drug` and a single `disease`. But you remind me that if we use `get_equivalent_nodes` then we don't need `map.txt` file  (which can further reduce the running time because we don't need to read this file, please see [here](https://github.com/RTXteam/RTX/blob/91c2a4642c974bc5d9bb7bca589ee26367121bb7/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L56-L59)).

> 2. here Do we still need this given that the even though KG1 uses the wrong CURIE prefix, the node synonymizer uses correct ones? Depends on how you populated the sqlite database

We don't need these lines because both sqlite database and `get_equivalent_nodes` use `CHEMBL.COMPOUND`. Actually, KG1, KG2 and `get_equivalent_nodes` all use `CHEMBL.COMPOUND` instead of `ChEMBL`. The only place where I saw `ChEMBL` is the old version of `map.csv`. I updated these lines [here](https://github.com/RTXteam/RTX/blob/91c2a4642c974bc5d9bb7bca589ee26367121bb7/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L63-L83).

> Lastly, you should include somewhere in the repo (probably the predictor folder or retrain_data subfolder) the script(s) that you used to do the re-training (even if it includes paths relevant only to our lab server, these can be moved to variables in a bash script at some point), since this re-training will need to be done yet again when the new KG2 comes out a number of months from now. That, and we want something to point to if/when people ask us how this model makes its predictions or how it was trained.

Actually I did this long time ago. All steps and scripts I used to retrain the new model were described in detail [here](https://github.com/RTXteam/RTX/tree/issue758/code/ARAX/ARAXQuery/Overlay/GraphSage_train).

If there are no other problems, I will merge it to `master` branch and close this issue. Please let me know.

**Comment by dkoslicki** [comment] 2020-07-15 16:09
@chunyuma Great! (apparently I forgot about your already including the re-training steps and scripts; I was probably looking in the wrong branch).

From my perspective, I think this is ready to be merged to master and closed out, so go for it!

**Closed** 2020-07-15 16:29 UTC
Labels: high priority
