### ISSUE TITLE
Errors in curie_id property of nodes in KG

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#74] opened 2018-04-18 19:32 UTC
Some of the curie_id properties of the nodes in the KG on the rtxsteve container on rtxdev.saramsey.org seem to have errors in them. I found the following nodes with the cypher command `match (n) where n.curie_id =~ '(?i).*[a-z]' return n.curie_id, n.description limit 50`:

| n.curie_id | n.description |
|-----|-------|
|"UBERON:0001029PHENOTYPE" | "obsolete neuromuscular junction phenotype"|
|"CL:0000573PHENOTYPE" | "retinal cone cell phenotype"|
|"CL:0001035PHENOTYPE" | "bone cell phenotype"|
|"UBERON:0001467PHENOTYPE" | "shoulder phenotype"|
|"GO:0007610PHENOTYPE" | "behavior phenotype"|
|"UBERON:0001799PHENOTYPE" | "vitreous chamber of eyeball phenotype"|
|"UBERON:0002107PHENOTYPE" | "liver phenotype"|
|"GO:0050890PHENOTYPE" | "cognition phenotype"|
|"GO:0060004PHENOTYPE" | "reflex phenotype"|
|"NBO:0000607PHENOTYPE" | "cognitive behavior phenotype"|
|"UBERON:0003657PHENOTYPE" | "limb joint phenotype"|
|"NBO:0000056PHENOTYPE" | "walking behavior phenotype"|
|"UBERON:0001090PHENOTYPE" | "synovial fluid phenotype"|
|"UniProt:EBI" | "MGAT5B"|
|"UniProt:TNF" | "ENSG00000204490"|
|"UniProt:CYorf15B" | "CY15B"|
|"UniProt:NFKBIA" | "ENSG00000100906"|
|"UniProt:HLA" | "ENSG00000204287"|
|"UniProt:MAFG" | "Q9BRP3"|
|"UniProt:EP400NL" | "H9KV84"|
|"UniProt:null" | "ANON1"|

Might be caused by an error in the KG construction?

**Comment by saramsey** [comment] 2018-04-18 22:47
Working on it

**Comment by saramsey** [comment] 2018-04-18 23:44
Testing a fix now, on rtxsteve

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 18, 2018, at 12:32 PM, Finn Womack <notifications@github.com<mailto:notifications@github.com>> wrote:


Some of the curie_id properties of the nodes in the KG on the rtxsteve container on rtxdev.saramsey.org<http://rtxdev.saramsey.org> seem to have errors in them. I found the following nodes with the cypher command match (n) where n.curie_id =~ '(?i).*[a-z]' return n.curie_id, n.description limit 50:

n.curie_id      n.description
"UBERON:0001029PHENOTYPE"       "obsolete neuromuscular junction phenotype"
"CL:0000573PHENOTYPE"   "retinal cone cell phenotype"
"CL:0001035PHENOTYPE"   "bone cell phenotype"
"UBERON:0001467PHENOTYPE"       "shoulder phenotype"
"GO:0007610PHENOTYPE"   "behavior phenotype"
"UBERON:0001799PHENOTYPE"       "vitreous chamber of eyeball phenotype"
"UBERON:0002107PHENOTYPE"       "liver phenotype"
"GO:0050890PHENOTYPE"   "cognition phenotype"
"GO:0060004PHENOTYPE"   "reflex phenotype"
"NBO:0000607PHENOTYPE"  "cognitive behavior phenotype"
"UBERON:0003657PHENOTYPE"       "limb joint phenotype"
"NBO:0000056PHENOTYPE"  "walking behavior phenotype"
"UBERON:0001090PHENOTYPE"       "synovial fluid phenotype"
"UniProt:EBI"   "MGAT5B"
"UniProt:TNF"   "ENSG00000204490"
"UniProt:CYorf15B"      "CY15B"
"UniProt:NFKBIA"        "ENSG00000100906"
"UniProt:HLA"   "ENSG00000204287"
"UniProt:MAFG"  "Q9BRP3"
"UniProt:EP400NL"       "H9KV84"
"UniProt:null"  "ANON1"

Might be caused by an error in the KG construction?

**Comment by saramsey** [comment] 2018-04-19 06:08
When we query with: Q16665; we get a node with alias: Q9BRP3

**Comment by saramsey** [comment] 2018-04-19 23:09
I'm testing the fix now... but it will take another two hours before I know if it worked.

**Comment by saramsey** [comment] 2018-04-19 23:45
restarted test, in order to fold in fixes for #80 and #79

**Comment by saramsey** [comment] 2018-04-26 16:14
fixed in KG:
http://rtxdev.saramsey.org:7674

**Closed by saramsey** 2018-04-26 16:14 UTC
