### ISSUE TITLE
Reviving lost Qs

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#326] opened 2019-04-29 15:28 UTC
In the move from the production site using API 0.8.0 to the /beta site using 0.9.1, we have lost support for the following Q numbers. If we can port these Q numbers to 0.9.1 or declare them obsolete, then the last hurdle will have been cleared and /beta can be moved to production:

- Q1
- Q2
 
- Q34
- Q39
- Q46
- Q103

**Comment by saramsey** [comment] 2019-04-29 19:10
EWD (at the AHM): plan is to work on this for a part of the mini-hackathon

**Comment by saramsey** [comment] 2019-04-29 19:11
Finn says that Jason is already working on this

**Comment by dkoslicki** [comment] 2019-05-02 22:33
I'm adding this to the agenda for the next team meeting, as these questions don't really fit in the "query graph" framework. We need to decide if we should:
1. Fudge the "query graph" component of the 0.9 response
2. Omit the "query graph" 
3. Extend the spec to fit these kinds of questions (eg. modifiers such as most/least/many/none/high or low Fisher score/etc).

**Comment by edeutsch** [comment] 2019-05-02 22:36
As in Monday's team meeting or tomorrow's mini hackathon?

**Comment by dkoslicki** [comment] 2019-05-02 23:09
Ah, that's right: how about tomorrow as that'll be a natural place to discuss it.

Sent from my mobile device, please excuse my brevity and/or typos

________________________________

**Comment by dkoslicki** [comment] 2019-05-03 19:10
Just so it's easy to find, this is from the mini-hackathon today (also at [this google doc](https://docs.google.com/document/d/1prKawNZial5735E_8W9EpqrCnyEhlwhP_QvcdcbRcPk/edit?usp=sharing)):

Issues:

- Port Q1 solution to output in 0.9.1 but using the “old way” sans query_graph
- Port Q2 solution to output in 0.9.1 but using the “old way” sans query_graph
- Plan out what the other missing QnSolutions would look like as a query_graph, including potential adjectives to capture additional semantics like:
- is_set=true seen in Q13, on nodes
- fisher_hop=true, on edges
- jaccard_two_hop=true
- Maybe we need a node set limiter, so that in addition to is_set=true, have limit_set=something or sort_by=...(sort descending, take top N)
-Another node adjective is “allow_subclasses=always|if_needed”? (this might be needed to fully complete the porting of Q3Solution, which ignores this feature)
- Need an edge attribute: is_directed=false


Examples:

Node: is_set=true, limit_set=top10,descending
Node: is_set=true, limit_set=top25%,ascending
Node: allow_subclasses=if_needed

Jaccard example:
- (phynotypic_feature:fever) - [contraindicated_for] - (drugs?: is_set=true) - [interact] -  (proteins?: scoring=Jaccard, num_results=N)
To compute the protein score, you need number of drugs along that path
+ Each results score is based on Jaccard similarity of size of drug set
Protein: scoring=Jaccard

Fisher example:
- (proteins: is_set=true, listA) - [involved_in] - (pathways?, scoring=Fisher, num_results=N) 

Allow_subclass_example:
(malaria)<-[is_subclass]-(other_malaria_type)-[has_phenotype]->(?phenotype)
Answer: 5 possibilities?
Malaria - [has_phenotype] - fever       (not really true in the KG, but implied)
West African malaria - [has_phenotype] - fever     (not strictly what asked for; substitution of n00)
Malaria - [has_phenotype] - fever, West African malaria - [has_phenotype] - fever (two problems for the price of one)
Malaria - [is_superclass] - West African malaria - [has_phenotype] - fever   (does not match query_graph; has extra node and edge)
(no results)   possibly with a suggestion to try node - subclass - rest of query?

TODO:

1. Bandaid  Q1 and Q2 (no query_graph or bindings, just use result.result_graph) (Eric)
2. Include decorations of Jaccard and Fisher in output 0.9 API spec (with full query graph) for Q34, Q39, Q46, Q103 (maybe Q55). Look at Q3Solution.py on NewFmt branch for an example. (David + Jason(?) + Finn(?))
3. Fix the Q3Solution.py to output a query_graph with allow_subclasses=always|if_needed
4. Get the QueryGraphReasoner to take as input decorated 0.9 JSON  (later)
5. Ask Patrick about: Allow_subclass example workaround
6. Write code to provide a restated_question based on a query graph (Eric)
7. Write code to create a tabular result summary (Eric)
8. Check how to get directed and undirected edges in query graph (Finn). See the /beta UI with (malaria)-[subclass_of]-> (disease) and (malaria)<-[subclass_of]-(disease) and note different results.

**Comment by finnagin** [comment] 2019-05-09 19:32
Directed and undirected edges can be specified on an edge by edge basis by including an edge property `"directed":True` or `"directed":False`.

**Comment by edeutsch** [comment] 2019-05-09 19:35
Is that an opposite policy to including 2 edges, one in each direction, as we currently have in the current KG, for example between chemical_substances and proteins?

**Comment by dkoslicki** [comment] 2019-05-09 19:37
This was for the ease of the user, as it's not immediately apparent which direction arrows should point for each predicate type. Having "undirected:True" allows for the user to say "just make these things connect along this edge type" which, personally, I do all the time.

The KG does have the 2 edges for bidirected currently, and I think it's no problem to have the user facing side and the KG have different policies.

**Comment by finnagin** [comment] 2019-05-09 19:41
To add to this we could still specify that we want an edge that is specified as bi-directional in our graph by just adding two edges with `"directed":True` with the source_node and target_node swapped.

**Comment by dkoslicki** [comment] 2019-05-09 19:47
@finnagin specify in the query graph, or the KG? From a user standpoint, a radio button seems best, but on the back-end I think you're free to implement it however you want (though it may be cleaner to convert ``-[]->`` to ``-[]-`` in the cypher query instead of making multiple queries or using ``OPTIONAL MATCH``

**Comment by edeutsch** [comment] 2019-05-09 19:47
I'm a bit confused I confess, but I just advocate that we have a clear written policy on how we handle this that we can all agree on.

**Comment by dkoslicki** [comment] 2019-05-09 19:57
I'm pretty sure the current operating policy is:
1. In the KG, all arrows are directional (a constraint of Neo4j), therefore bidirectional edges are represented by two arrows, one in each direction.
2. Cypher queries made to the KG, on the other hand, can choose to include or ignore the directionality of arrows. Hence, anything that leverages a cypher query (like all the reasoning code, the QueryGraph paradigm, etc.) can choose to include or ignore directionality of arrows as well.

Does that clarify? Basically, these are constraints or features of Neo4j+Cypher, so we're just trying to align our reasoning code more closely to that, hence why Finn added that feature in the query_graph code.

**Comment by edeutsch** [comment] 2019-05-09 20:10
Great so far. And how does "undirected:True" (dkoslicki above) and "directed:True" (finnagin above) fit into the policy? We should choose one. And I am now realizing these properties are only for query_graph{}, not for the KG, correct? And how does one of these in the query_graph{} map to cypher?

**Comment by finnagin** [comment] 2019-05-09 20:13
@dkoslicki Sorry I think maybe I confused the issue a bit with my last comment. If you don't care about direction then, in the query graph, add in the property `"directed":False` and it will match if there exists any edge between two nodes regardless of direction. On the backend this is how it works. It adds in edges using `-[ ]-` instead of `-[ ]->`. 
If, however, you specifically want an edge that would be considered bi-directed in the KG (i.e. nodes in our KG that are connected with two opposite arrows) then you could construct a query that has two edges pointing in opposite directions between the two nodes with `"directed":True` as a property


@edeutsch There is just one. Only the property  "directed:True" or "directed:False" is supported right now.

**Comment by dkoslicki** [comment] 2019-05-09 20:13
oooh, I see the cause of the confusion: that's my typo. It should be "directed:True" as Finn noted (less negatives, as Luis noted).

And yes, these are only for query_graph{}, not the KG. The query_graph{} get's magically converted to cypher via Finn's work on porting Gamma's code to do the same. The resulting cypher can be rather long/ugly, but as far as we've tested it, it seems to be correct.

**Comment by dkoslicki** [comment] 2020-05-29 21:35
Not relevant anymore. Closing

**Closed by dkoslicki** 2020-05-29 21:35 UTC
