### ISSUE TITLE
Strange 'same_as' relationship in KG2

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1027] opened 2020-08-19 19:12 UTC
In `kg2endpoint` (which I believe is still KG2.2.0), I noticed that these two nodes are linked by `same_as` relationships:
```
match p=(n {id:'ICD10:N18'})--(m {id:'MONDO:0000001'}) return p
```
![Screen Shot 2020-08-19 at 11 58 41 AM](https://user-images.githubusercontent.com/49423686/90678297-5c5bd680-e213-11ea-93ba-dab92b0b7989.png)

but that doesn't seem to make much sense. (a `subclass_of` relationship would make more sense...)

it looks like the `same_as` edges are coming from MONDO:
```
{
  "simplified_relation_curie": "biolink:same_as",
  "simplified_relation": "https://w3id.org/biolink/vocab/same_as",
  "negated": "False",
  "relation_curie": "MONDO:equivalentTo",
  "subject": "MONDO:0000001",
  "edge_label": "equivalent_to",
  "update_date": "2020-07-21 21:02:07 GMT",
  "relation": "http://purl.obolibrary.org/obo/MONDO_equivalentTo",
  "simplified_edge_label": "same_as",
  "publications_info": "{}",
  "provided_by": [
    "OBO:mondo.owl"
  ],
  "publications": "[]",
  "object": "ICD10:N18"
}
```
```
{
  "simplified_relation_curie": "biolink:same_as",
  "simplified_relation": "https://w3id.org/biolink/vocab/same_as",
  "negated": "False",
  "relation_curie": "MONDO:equivalentTo",
  "subject": "ICD10:N18",
  "edge_label": "equivalent_to",
  "update_date": "2020-07-21 21:02:07 GMT",
  "relation": "http://purl.obolibrary.org/obo/MONDO_equivalentTo",
  "simplified_edge_label": "same_as",
  "publications_info": "{}",
  "provided_by": [
    "OBO:mondo.owl"
  ],
  "publications": "[]",
  "object": "MONDO:0000001"
}
```
not sure if this is an issue with MONDO itself, but it's not great for the `NodeSynonymizer`, since it uses (or will use) `same_as` relationships in deciding which nodes to merge.

**Comment by saramsey** [comment] 2020-08-19 19:51
This is what I am seeing in the OBO-JSON version of `mondo.owl`:

<img width="837" alt="Screen Shot 2020-08-19 at 12 50 23 PM" src="https://user-images.githubusercontent.com/5562107/90682941-a09ea500-e21a-11ea-8ca9-087116b74be8.png">

**Comment by saramsey** [comment] 2020-08-19 19:52
Not sure why we are getting a `same_as` relationship. I will have to investigate.

**Comment by saramsey** [comment] 2020-08-20 04:44
OK, there is actually an axiom in `mondo.owl` that asserts this relationship (`MONDO:equivalentTo`) between `MONDO:0000001` and `ICD10:N18`:
<img width="912" alt="Screen Shot 2020-08-19 at 9 43 51 PM" src="https://user-images.githubusercontent.com/5562107/90717771-32cb9b00-e265-11ea-9ef1-7af13209c320.png">

**Comment by saramsey** [comment] 2020-08-20 04:51
I've noted this issue on the MONDO GitHub issue tracker:
https://github.com/monarch-initiative/mondo/issues/1921

**Comment by saramsey** [comment] 2020-08-20 04:58
Since this is causing issues with the node synonymizer, I've hand-hacked the local `mondo.owl` file on `kg2dev` and converted it to a Pickle file:
```
cd ~/kg2-code
source ~/kg2-venv/bin/activate
python
import kg2_util
ontology = kg2_util.make_ontology_from_local_file('/home/ubuntu/kg2-build/mondo.owl', save_pickle=True)
```
so that the next time we build KG2 on `kg2dev.rtx.ai`, it should read MONDO from the local `mondo.pickle` file and not download the latest version. This is a temporary stop-gap, that will solve the problem only on `kg2dev`, until I can get the MONDO team to fix the upstream `mondo.owl`.

**Comment by saramsey** [comment] 2020-08-20 19:55
OK, apparently at least one other group (in Scotland) has noticed this issue as well

https://github.com/monarch-initiative/mondo/issues/1921

**Comment by kvarforl** [comment] 2020-10-26 23:03
From the above query `match p=(n{id:'ICD10:N18'})--(m {id:'MONDO:0000001'}) return p`:
![image](https://user-images.githubusercontent.com/39020520/97237416-4aaf2600-17a4-11eb-96d7-5161c780bb8c.png)
... we've adjusted to just  `close_match` instead of `same_as`.

@saramsey  should that be considered fixed? I'm assuming not, based on amy's comment above suggesting that it should be a `subclass_of` relationship, but let me know your thoughts.

**Comment by saramsey** [comment] 2020-10-27 05:08
Hi @kvarforl, I have an idea. In `predicate-remap.yaml`, I think we should change:
```
OBO:xref:
  rename:
  - close_match
  - skos:closeMatch
```
(lines 2421-2424)
to 
```
OBO:xref:
  rename:
  - related_to
  - biolink:related_to
```
This is in keeping with the original meaning of `xref` in the OBO specification, shown here: https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html (see "xrefs")

**Comment by saramsey** [comment] 2020-10-27 05:11
A fancier, future fix could be as follows:  whenever we see an `xref` link in an OBO ontology, how we would handle it would depend on an `if` statement as follows:
- if it is an OBO ontology that has `treat-xrefs-as-equivalent` set (instead of `OBO:xref`), use `skos:close_match`; examples of such ontologies seem to be `nbo.owl` and `uberon-ext.owl`.
- if it is an OBO ontology that does not have `treat-xrefs-as-equivalent` set (which is the vast majority of OBO ontologies), just use `OBO:xref` which will get mapped to `biolink:related_to` by the `filter_kg_and_remap_predicates.py` script later in the build process.

**Comment by saramsey** [comment] 2021-02-01 23:06
> Hi @kvarforl, I have an idea. In `predicate-remap.yaml`, I think we should change:
> 
> ```
> OBO:xref:
>   rename:
>   - close_match
>   - skos:closeMatch
> ```
> 
> (lines 2421-2424)
> to
> 
> ```
> OBO:xref:
>   rename:
>   - related_to
>   - biolink:related_to
> ```
> 
> This is in keeping with the original meaning of `xref` in the OBO specification, shown here: https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html (see "xrefs")

Hmm... I see now that the problem is that this causes a validation failure, as `OBO:xref` is supposed to mapped to `biolink:close_match` per the biolink model (#1204)

**Comment by saramsey** [comment] 2021-02-01 23:12
Hmm, OBO xrefs may require special handling in `multi_ont_to_json_kg.py`. Maybe

- if the ontology has `treat-xrefs-as-equivalent` set to true, then use `skos:close_match`
- otherwise use `biolink:related_to`

maybe?

**Comment by saramsey** [comment] 2021-02-01 23:16
still no word from the MONDO team about this issue; I pinged them again

**Comment by saramsey** [comment] 2021-02-02 02:37
OK, Mondo team has committed a fix and it should be in the official `mondo.owl` file in March.

https://github.com/monarch-initiative/mondo/issues/1921

**Comment by kvarforl** [comment] 2021-04-26 02:38
it looks like these two nodes are no longer connected at all in KG2.6.0.

```
match p=(n{id:'ICD10:N18'})--(m {id:'MONDO:0000001'}) return p
```
returns no results, but both nodes still exist, which seems in line with the Mondo PR! Closing this out :)

**Closed by kvarforl** 2021-04-26 02:38 UTC
Labels: bug, kg2, verify this fix in next KG2 build
