### ISSUE TITLE
There non-human proteins showing up in the KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#21] opened 2018-03-21 02:06 UTC
I've been looking at the COP for the treatment of osteoarthritis by naproxen, and it appears that one of the reason why we are not getting the correct answer is that some of the relevant nodes are not expanded. For example, the PTGS1 gene is a ("the relevant") target of naproxen, and yet:

match (n:uniprot_protein{description:"PTGS1"}) return n.expanded
False

And so I cannot connect PTGS1 to any relevant piece of anatomy:

match p=(s:pharos_drug{name:"naproxen"})-[:targets]-(:uniprot_protein{description:"PTGS1"})-[]-(:anatont_anatomy) return p limit 50
(no changes, no records)

Was there an error in the Orangeboard construction that caused this node not to be expanded? I had assumed that we had seeded with all drugs and expanded from there. Yet:

match p=(s:pharos_drug{name:"naproxen"})-[:targets]-(t:uniprot_protein) return t.name, t.description, t.expanded
╒════════╤═══════════════╤════════════╕
│"t.name"│"t.description"│"t.expanded"│
╞════════╪═══════════════╪════════════╡
│"P25101"│"EDNRA"        │false       │
├────────┼───────────────┼────────────┤
│"P0DJD9"│"PGA5"         │false       │
├────────┼───────────────┼────────────┤
│"P23219"│"PTGS1"        │false       │
├────────┼───────────────┼────────────┤
│"Q15722"│"LTB4R"        │false       │
├────────┼───────────────┼────────────┤
│"P11712"│"CYP2C9"       │true        │
├────────┼───────────────┼────────────┤
│"P09917"│"ALOX5"        │true        │
├────────┼───────────────┼────────────┤
│"O14842"│"FFAR1"        │false       │
├────────┼───────────────┼────────────┤
│"Q07869"│"PPARA"        │false       │
├────────┼───────────────┼────────────┤
│"O43174"│"CYP26A1"      │false       │
├────────┼───────────────┼────────────┤
│"P24530"│"EDNRB"        │false       │
├────────┼───────────────┼────────────┤
│"P37231"│"PPARG"        │true        │
├────────┼───────────────┼────────────┤
│"Q8TCC7"│"SLC22A8"      │false       │
├────────┼───────────────┼────────────┤
│"P49286"│"MTNR1B"       │false       │
├────────┼───────────────┼────────────┤
│"P08183"│"ABCB1"        │true        │
├────────┼───────────────┼────────────┤
│"P01375"│"TNF"          │true        │
├────────┼───────────────┼────────────┤
│"P00374"│"DHFR"         │true        │
├────────┼───────────────┼────────────┤
│"P08684"│"CYP3A4"       │true        │
├────────┼───────────────┼────────────┤
│"P35354"│"PTGS2"        │true        │
├────────┼───────────────┼────────────┤
│"P33261"│"CYP2C19"      │false       │
├────────┼───────────────┼────────────┤
│"P42330"│"AKR1C3"       │false       │
├────────┼───────────────┼────────────┤
│"P16473"│"TSHR"         │false       │
├────────┼───────────────┼────────────┤
│"Q16665"│"HIF1A"        │true        │
├────────┼───────────────┼────────────┤
│"P48039"│"MTNR1A"       │false       │
└────────┴───────────────┴────────────┘

**Comment by saramsey** [comment] 2018-03-24 04:10
So, there are a couple of ways we could fix this, depending on how one defines "fix".

We could specifically seed uniprot protein IDs for genes that are in the COP spreadsheet; that would take care of the COP spreadsheet, at least.

More generally, here is the thing.  If we are expanding 3X then we can always get to some proteins in the third hop, and these by definition won't be expanded.  Does that make sense?

I guess asymptotically if you did enough rounds of expansion, eventually all nodes would be expanded (as there are a finite number of nodes). I have no idea how many rounds it would take to reach this limit. Do you want to explore it?

**Comment by saramsey** [comment] 2018-03-27 17:09
In the current version of the KG (rtxdev.saramsey.org:7674), nearly all the proteins resultant from the above query are expanded, so I'm going reclassify this issue as a question. From what I'm seeing, I do not think this is a bug; BioNetExpander.py and BuildMasterKG.py appear to be working as designed.  
![screen shot 2018-03-27 at 10 07 47 am](https://user-images.githubusercontent.com/5562107/37982969-df58b744-31a6-11e8-8698-2b7516ca247c.png)

**Comment by dkoslicki** [comment] 2018-04-14 02:53
@saramsey I'm beginning to think that more expanding might be useful. In particular, for the COP questions, I am noticing that some of the "correct" protein targets do not connect to the desired disease (while other sub-optimal protein targets do connect). Note that COP's consist of 5 hops.

**Comment by saramsey** [comment] 2018-04-14 04:50
Or perhaps keep 3 hops, but just do more seeding?

I mean, we could seed every anatomy, every GO process, etc…..

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 13, 2018, at 7:53 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> I'm beginning to think that more expanding might be useful. In particular, for the COP questions, I am noticing that some of the "correct" protein targets do not connect to the desired disease (while other sub-optimal protein targets do connect). Note that COP's consist of 5 hops.

**Comment by dkoslicki** [comment] 2018-04-14 19:40
Yeah, more seeding might work. I'm thinking that seeding the protein nodes would help (get's us effectively one more hop for the COP's), and perhaps the anatomy too. I don't have much use for GO nodes yet.

**Comment by jaredroach** [comment] 2018-04-16 20:17
I wonder whether trying to connect primarily molecular/cellular processes to particular pieces of anatomy is a fundamentally flawed strategy. Once naproxen reaches "generalized anti-inflammatory effect on cells" (assuming that is a node), then going one hop forward to the target anatomy is trivial and un-interesting. Because it hits ANY anatomy, as long as it can be influenced by inflammation (which is almost all anatomy)>

**Comment by dkoslicki** [comment] 2018-04-16 21:15
@saramsey Just to close the loop on this one: I'm still getting PTGS1 not expanded in the new KG at ``rtx.ncats.io``:
```
match (n:protein{description:"PTGS1"}) return n.expanded
False
```
However you want to do it, can get get this (and other protein nodes) expanded?

**Comment by dkoslicki** [comment] 2018-04-16 21:16
@jaredroach Yes, it may be a flawed strategy, but that's what NCATS gave us to work with. Feel free to propose a different definition of a COP and I'd be happy to discuss/put it on the team meeting agenda. In a separate issue of course, since this issue (#21) is for nodes not being expanded in the KG.

**Comment by saramsey** [comment] 2018-04-16 23:42
I will research this tonight.  This is somewhat puzzling.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 2:15 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> Just to close the loop on this one: I'm still getting PTGS1 not expanded in the new KG at rtx.ncats.io:

match (n:protein{description:"PTGS1"}) return n.expanded
False


However you want to do it, can get get this (and other protein nodes) expanded?

**Comment by saramsey** [comment] 2018-05-02 16:57
Making progress on this.  I am seeing that for 395 proteins in the KG, the "symbol" and "name" fields are inexplicably swapped in Neo4j.

![screen shot 2018-05-02 at 9 56 07 am](https://user-images.githubusercontent.com/5562107/39537654-1994d6ea-4def-11e8-931a-fc522f1495e8.png)

Wondering if it is a bug in this code in Orangeboard, on line 301-302:
![screen shot 2018-05-02 at 9 56 57 am](https://user-images.githubusercontent.com/5562107/39537691-2cc72f88-4def-11e8-87a4-1e6fa8bded2b.png)

**Comment by saramsey** [comment] 2018-05-02 16:58
Updated the code to correctly also set the "symbol" field in this code branch, if it is a microRNA or protein node:
![screen shot 2018-05-02 at 9 57 51 am](https://user-images.githubusercontent.com/5562107/39537731-4c5b3312-4def-11e8-8283-12538a022b0b.png)

**Comment by edeutsch** [comment] 2018-05-02 17:06
Do we ever use symbol for other node types, like "ALS" in diseases?

**Comment by saramsey** [comment] 2018-05-02 17:07
no, as far as I know that is not part of the spec.

**Comment by edeutsch** [comment] 2018-05-02 17:09
What do you mean, "not part of the spec"? "symbol" is a field in the spec, isn't it?

**Comment by saramsey** [comment] 2018-05-02 23:18
yes but it is an optional field. and I think it is intended only for genes or proteins?

**Comment by saramsey** [comment] 2018-05-02 23:19
I'm beginning to think this is a bug. Neo4j weirdness delayed my testing but I am running the tests now, should be done in a couple of hours.  Provisionally reclassifying this issue as a bug.

**Comment by saramsey** [comment] 2018-05-03 16:05
I believe I have identified the root cause of this bug. Attempted code fix committed.  Testing now on rtxsteve.

**Comment by saramsey** [comment] 2018-05-07 16:02
OK it looks like with the current code in master, the resulting KG does still have proteins that are not "expanded", however, they are not human (thus I'm hoping  they are not problematic for reasoning).
I want to get these non-human proteins out of the KG (their presence is a bug by definition) but I also want to keep mindful of the priority list for KG enhancements.

**Comment by saramsey** [comment] 2018-05-07 16:03
PTGS2 is now expanded in the new KG

**Closed** 2018-05-09 18:56 UTC
Labels: bug, low priority, question
