### ISSUE TITLE
Autocomplete not working on the new arax.ncats.io

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2365] opened 2024-09-04 21:09 UTC
Jared observed that autocomplete is not working on the new rebuilt arax.ncats.io:
https://arax.ncats.io/beta/
![image](https://github.com/user-attachments/assets/a529dd7d-b8f0-455e-8538-a903e985f8db)

The console says this:
![image](https://github.com/user-attachments/assets/402fb267-45d6-4713-9414-23ad9b06e816)

The surface problem seems to be that something in the upgraded toolchain objects to importing what is supposed to be javaScript from a file with a .json extension (instead of .js)

But I suspect that this "quickdef" thing is an ancient holdover from Indiana and maybe not even really used.
I suspect the right solution is just to understand what it is/was and just gracefully remove it?
Not sure...

**Comment by isbluis** [comment] 2024-09-05 06:10
There were two unrelated reasons why autocomplete was not working on this new server:

1. The nginx server was configured to block incorrect MIME types, so that `quick_defs.json` would not load at all, since it really is a Javascript file.  Note that ITRB servers are *not* set up like this, and likely the old arax server as well
2. The autocomplete database (`autocomplete_v1.0_KG2.10.0.sqlite`) was an empty file in _devED_, where it was hosted.  Setting this as a symlink to point to the real file fixed all other issues.
Closing.

**Closed by isbluis** 2024-09-05 06:10 UTC

**Comment by saramsey** [comment] 2024-09-08 17:21
Good catch @isbluis. With the new version of Ubuntu inside the container, we got a newer version of Nginx and thus a new default config file. This may be an updated default setting or updated default config setting in the newer Nginx. I appreciate your tracking it down to the root cause.  Also thanks for fixing the autocomplete issue in `/devED`.

**Comment by isbluis** [comment] 2024-09-09 01:24
No worries, @saramsey !  I would have been able to fix this far faster if it had not taken so long to set up my ssh keys on the new server.
Still not sure how `/devED` ended up with an empty file; two ways that this can be improved:
1. Add an item to double-check that the sqlite exists (and is not empty)
2. Log an error if autocomplete cannot establish a connection (currently it just logs "Connected to xxxx" even if it failed) -- I can work on this.
