### ISSUE TITLE
create_indexes_constraints.py fails with an authentication error

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1157] opened 2020-12-11 16:27 UTC
Here is the error message, from `kg2_build/tsv-to-neo4j.log`:
```
/home/ubuntu/kg2-build/RTXConfiguration-config.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/create_indexes_constraints.py", line 105, in <module>
    driver = neo4j.GraphDatabase.driver(bolt, auth=(neo4j_user, neo4j_password))
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neo4j/__init__.py", line 116, in driver
    return Driver(uri, **config)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neo4j/__init__.py", line 157, in __new__
    return subclass(uri, **config)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neo4j/__init__.py", line 231, in __new__
    pool.release(pool.acquire())
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neo4j/__init__.py", line 228, in connector
    return connect(address, **dict(config, **kwargs))
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 964, in connect
    connection = _handshake(s, address, der_encoded_server_certificate, **config)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 932, in _handshake
    connection.hello()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 249, in hello
    self.sync()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 527, in sync
    detail_delta, summary_delta = self.fetch()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 419, in fetch
    return self._fetch()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/neobolt/direct.py", line 774, in on_failure
    raise AuthError(message)
neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.
```

The output of `setup-kg2-neo4j.sh` included this, with the correct password that matches the config file in place of the stars.
```
++ /home/ubuntu/kg2-venv/bin/python3 /home/ubuntu/kg2-code/read_kg2_password_from_rtxconfig.py -c /home/ubuntu/kg2-build/RTXConfiguration-config.json
+ kg2_neo4j_password=******
+ sudo su - neo4j -c 'neo4j-admin set-initial-password ******'
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Changed password for user 'neo4j'.
```
I also printed out the username and password in `create_indexes_constraints.py`, and again, it was as expected.

I tried purging neo4j and reinstalling it using the setup script, but nothing changed. I'm running the scripts on kg2endpoint2.

@finnagin @amykglen @saramsey  do any of you have any ideas of what I should do differently?

**Comment by saramsey** [comment] 2020-12-11 16:38
Are TCP ports 7474 and 7687 open in the AWS instance's network security group?

**Comment by saramsey** [comment] 2020-12-11 16:39
Are you able to get in using the Cypher shell?

**Comment by kvarforl** [comment] 2020-12-11 16:46
I got in with cypher shell using the default user/password configuration: neo4j neo4j. Your key should be on the instance if you would like to investigate!

**Comment by kvarforl** [comment] 2020-12-11 16:50
The TCP ports are open in the AWS instance's network secutiry group:
![image](https://user-images.githubusercontent.com/39020520/101931165-4b561d00-3b96-11eb-9390-60de1080ef35.png)

**Comment by saramsey** [comment] 2020-12-11 18:57
OK, so there may be a bug in `setup-kg2-neo4j.sh` or possibly in `install-neo4j.sh`. At line 74 of `setup-kg2-neo4j.sh`, there is this code:
```
sudo su - neo4j -c "neo4j-admin set-initial-password ${kg2_neo4j_password}"
```
which should set the database password to our "usual" Neo4j password. But for some reason, often times, it doesn't work. This is by no means the first time I've seen this issue. But in my testing in Ubuntu 18.04 inside a Docker container, I didn't see this issue, which is why I originally checked in that code at L74. So this is an odd one.  Now, one thing to know about this particular command (`neo4j-admin set-initial-password`) is that it has a huge limitation; it *only* works if Neo4j has never been previously started on the system. If for some reason `install-neo4j.sh` starts Neo4j, or if anything/anyone starts Neo4j before `neo4j-admin set-initial-password` is run, then the password setting silently fails, but does not tell Bash. Sigh. @kvarforl can you please log a separate issue on this?  I think the `set-initial-password` issue is the root cause here, and we should try to address it by fixing `install-neo4j.sh` or `setup-kg2-neo4j.sh` at some point. 

In the meantime, here is my "fix" when this issue happens:
1. Start up Neo4 (`sudo service neo4j start`)
2. Wait one minute, then confirm Neo4j is running (`sudo service neo4j status`)
3. Use my browser to connect to Neo4j via HTTP on port 7474. You should see a username/password authentication form.
4. Fill in "neo4j" and "neo4j" for username and password, respectively, and submit the form. You should be immediately prompted to set a new password. At that time, type in our "usual" Neo4j password (you'll have to enter it twice).
5. When you submit the form, Neo4j should be running and it should now have the correct password set.

So, can you please add the above five-point instructions to the KG2 README.md under the "Troubleshooting"  section? Thanks.
5.

**Closed** 2020-12-11 20:34 UTC
Labels: kg2
