### ISSUE TITLE
Duplicate reactome nodes in KG

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#251] opened 2018-06-27 22:49 UTC
It looks like there are several duplicate nodes in the KG at rtx.ncats.io:7574. You can find and example of two such nodes by entering `match (n) where n.id='REACT:R-HSA-109606' return n`. Upon examination the only difference I see is that the rtx_name properties are different as one had a prefix and the other does not e.g.

|n.rtx_name|
|--|
|"REACT:R-HSA-109606"|
|"R-HSA-109606"|

(generated by running `match (n) where n.id='REACT:R-HSA-109606' return n.rtx_name`)

Upon quick glance this seems it could be that a difference of the rtx_name property is causing the issue here because when I run `match (n), (m) where n<>m and split(n.id,':')[0] = 'REACT' and split(m.id,':')[0] = 'REACT' and n.id=m.id return n.rtx_name as rtx_name1, m.rtx_name as rtx_name2  limit 10` I get back:

rtx_name1 | rtx_name2
-- | --
"R-HSA-983231" | "REACT:R-HSA-983231"
"R-HSA-199977" | "REACT:R-HSA-199977"
"R-HSA-427389" | "REACT:R-HSA-427389"
"REACT:R-HSA-420499" | "R-HSA-420499"
"R-HSA-8939211" | "REACT:R-HSA-8939211"
"R-HSA-114508" | "REACT:R-HSA-114508"
"R-HSA-1566948" | "REACT:R-HSA-1566948"
"R-HSA-917729" | "REACT:R-HSA-917729"
"R-HSA-380972" | "REACT:R-HSA-380972"
"R-HSA-1237044" | "REACT:R-HSA-1237044"

which all have the same difference in rtx_name properties. 

**NOTE:** I didn't see any when I checked but it might be a good idea to look at a few of these nodes and see if there are any other differences between them.

It also looks like only reactome nodes have this issue which you can tell by running `match (n), (m) where n<>m and n.id=m.id return distinct split(n.id,':')[0]` which only returns the prefix 'REACT'.

Lastly, when I count the number of duplicate nodes by running `match (n), (m) where n<>m and n.id=m.id and split(n.id,':')[0] = 'REACT' and split(m.id,':')[0] = 'REACT'  return count(*)`, which will count all copies of each node, it returns that there are 1410 such nodes.

**Comment by finnagin** [comment] 2018-06-27 22:52
@saramsey I added the high priority label since it is on rtx.ncats.io but I'm only blocking on updating the indexes on that KG for David so feel free to remove the label if you don't think this is high priority.

**Comment by DeqingQu** [comment] 2018-06-28 00:15
@saramsey When I checked the duplicated nodes' relationships, I found there was no relation for the nodes whose rtx_name is started with 'REACT:' by running `match (n), (m) where n<>m and n.id=m.id and split(n.rtx_name, ':')[0] = 'REACT'optional match (n)-[r]-() return count(r)` (return 0). 

But there are many relations for the nodes whose rtx_name is not started with 'REACT:' by running `match (n), (m) where n<>m and n.id=m.id and split(n.rtx_name, ':')[0] = 'REACT' optional match (m)-[r]-() return count(r)` (return 790502)

I am not sure which kind of duplicated nodes should be deleted. If you want to delete all duplicated nodes whose rtx_name is started with 'REACT:', you can run `match (n), (m) where n<>m and n.id=m.id and split(n.rtx_name, ':')[0] = 'REACT'delete n`. It will delete 705 nodes.

I will write a Python function to patch the issue.

**Comment by saramsey** [comment] 2018-07-26 20:30
this is fixed

![screen shot 2018-07-26 at 1 30 07 pm](https://user-images.githubusercontent.com/5562107/43286841-090962e2-90d8-11e8-9d85-b06bbc22b158.png)

**Comment by finnagin** [comment] 2018-07-27 22:06
Something I just noticed is that the cypher querry used in the above comment, `match (n:pathway) where n.id starts with "R-" return count(*)`, there was a typo and n.id was used rather than n.rtx_name. If you replace id with rtx_name, `match (n:pathway) where n.rtx_name starts with "R-" return count(*)`, you will get 712 back. I think that's probably why we thought it was fixed.

Also, I looked into how many of each there were and it looks like there are 712 nodes where rtx_name starts with 'R-' (`match (n) where n.rtx_name starts with 'R-' return count(n)`) and 2208 that start with 'REACT' (`match (n) where n.rtx_name starts with 'REACT' return count(n)`).

However, if we look at the connections these nodes have the 712 'R-' nodes have 790844 relationships (`match (n) where n.rtx_name starts with 'R-' optional match (n)-[r]-() return count(r)`) where as none ofthe 2208 'REACT:' nodes have any relationships with any other node in our KG. (`match (n) where n.rtx_name starts with 'REACT' optional match (n)-[r]-() return count(r)`)

**Comment by DeqingQu** [comment] 2018-07-30 18:36
@saramsey The pathway nodes whose id starts with 'REACT:' are generated by `seed_nodes_from_master_tsv_file` function in BuildMasterKG.py from 'seed_nodes_filtered.tsv' file and the pathway nodes whose id starts with 'R-' are generated by `expand_protein` function in BioNetExpander.py. 

I copied some lines at the end of the seed_nodes_filtered.tsv file.

pathway REACT:R-HSA-72312       rRNA processing generic
pathway REACT:R-HSA-8868766     rRNA processing in the mitochondrion    generic
pathway REACT:R-HSA-8868773     rRNA processing in the nucleus and cytosol      generic
pathway REACT:R-HSA-191859      snRNP Assembly  generic
pathway REACT:R-HSA-2033515     t(4;14) translocations of FGFR3 generic
pathway REACT:R-HSA-379724      tRNA Aminoacylation     generic
pathway REACT:R-HSA-6787450     tRNA modification in the mitochondrion  generic
pathway REACT:R-HSA-6782315     tRNA modification in the nucleus and cytosol    generic
pathway REACT:R-HSA-72306       tRNA processing generic
pathway REACT:R-HSA-6785470     tRNA processing in the mitochondrion    generic
pathway REACT:R-HSA-6784531     tRNA processing in the nucleus  generic
pathway REACT:R-HSA-199992      trans-Golgi Network Vesicle Budding     generic
pathway REACT:R-HSA-4839744     truncated APC mutants destabilize the destruction complex       generic
pathway REACT:R-HSA-192814      vRNA Synthesis  generic
pathway REACT:R-HSA-192905      vRNP Assembly   generic

In `seed_nodes_from_master_tsv_file` function, only 'REACT:' nodes are generated and no relationship is created in the function. In `expand_protein` function, 'R-' nodes and relationships are generated at the same time. This explains why the 'REACT:' nodes have no relationships in our KG.

I think we should remove the 'REACT:' prefix from the seed_nodes_filtered.tsv file. Because in the `expand_pathway` function of BioNetExpander.py, `QueryReactome.query_reactome_pathway_id_to_uniprot_ids_desc(reactome_id_str)` is called to query uniprot ids related to the pathway node, but when using the pathway ID starts with 'REACT:' it always returns an empty dictionary.

**Comment by DeqingQu** [comment] 2018-08-05 21:53
@saramsey The new KG was generated successfully this morning. However, there are still two duplicate pathway nodes.

rtx_name1 | rtx_name2
-- | --
"R-HSA-1855204" | "REACT:R-HSA-1855204"
"R-HSA-112043" | "REACT:R-HSA-112043"

I checked the seed_nodes_filtered.tsv and found there are two duplicate pathway nodes in the seed files. I think the only two duplicate nodes in our new KG is caused by the duplicate nodes in seed file.
```
pathway	R-HSA-112043	PLC beta mediated events	general
pathway	R-HSA-1855204	Synthesis of IP3 and IP4 in the cytosol	general
pathway	REACT:R-HSA-112043	PLC beta mediated events	generic
pathway	REACT:R-HSA-1855204	Synthesis of IP3 and IP4 in the cytosol	generic
```

I have deleted the two duplicate nodes in the seed file and pushed the seed file to our master branch. There will be no duplicate nodes when we run the BuildMasterKG script next time.

I also deleted the duplicate nodes in our KG maunually. There are no duplicate nodes in our KG now. You can check it by `match (n), (m) where n<>m and n.rtx_name=m.rtx_name return count(n)` and `match (n), (m) where n<>m and n.id=m.id return count(n)`.
Moreover, `match (n) where n.rtx_name starts with 'R-' return count(n)` will return 0 and `match (n) where n.rtx_name starts with 'R-' optional match (n)-[r]-() return count(r)` will also return 0.

**Comment by saramsey** [comment] 2018-09-10 18:46
Closing this issue, as it appears to be fixed in the current KG on rtx.ncats.io:7574

**Closed by saramsey** 2018-09-10 18:46 UTC
Labels: high priority
