### ISSUE TITLE
Expand should return an error state if no answer is found

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#713] opened 2020-04-17 22:30 UTC
Consider the following query:
add_qnode(name=mRNA editing, id=n00)
add_qnode(type=protein, id=n01)
add_qedge(source_id=n00, target_id=n01, type=participates_in, id=e00)
expand(edge_id=e00)
resultify(ignore_edge_direction=true)

Seems reasonable. If you execute it, the result is:
the node binding list does not cover all nodes in the query graph

which is very difficult for the user to interpret.
Peering in the logging output, one sees:
INFO:    After Expand, Message.KnowledgeGraph has 0 nodes and 0 edges

I can think of very very scenarios where processing can continue in a reasonable fashion if Expand returns 0 nodes and 0 edges.

Can Expand return an ERROR when this happens? I think we discussed an option to turn this into a WARNING so that in the rare case where processing could continue despite nothing to Expand, it is possible.

**Comment by amykglen** [comment] 2020-04-20 17:45
Sounds good - this now throws an `error` by default, and I added an optional parameter `continue_if_no_results` that you can set to `true` if desired (changes in `expander` branch). (Perhaps later we'll know of some predictable situations where we would want execution to continue if an `expand` finds no results, but for now it is at least controllable via this parameter.)

**Comment by dkoslicki** [comment] 2020-04-24 01:17
Shall we close this @amykglen now that it’s implemented? (Note #721 )

**Comment by amykglen** [comment] 2020-04-24 01:22
Yes, though I made these changes before the discussion in #721, so they're in the `expander` branch, and haven't made it to `master` yet. And thus haven't been tested on production. (Which I believe is what #721 discussion seems to be saying should happen prior to closing?)

**Comment by edeutsch** [comment] 2020-04-24 02:02
I do encourage that we only close an issue about user-facing code when it is in master and rolled out and verified available to users.

**Comment by amykglen** [comment] 2020-04-28 14:05
Ok - I confirmed on beta that this is working (`expand` throws an `error` when no paths are found)

**Closed by amykglen** 2020-04-28 14:05 UTC
Labels: need to test on production
