### ISSUE TITLE
Previous RTX query system appears broken because of KGNodeIndex

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#663] opened 2020-03-06 20:12 UTC
As feared, the previous RTX query mechanism is unstable and probably mostly broken.

repro:
https://arax.rtx.ai/devED/
Ask: What proteins does acetaminophen target?

Result: ERROR:
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Question.py", line 302, in get_parameters
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 271, in get_node_property
    raise Exception("Node or property not found using query: '%s'" % query)
Exception: Node or property not found using query: 'match (n{id:'CUI:C1521840'}) return labels(n)'

The code is trying to query KG1 with a node CURIE it found in the KGNodeIndex from KG2: CUI:C1521840

**Comment by edeutsch** [comment] 2020-03-06 20:26
We do already, the production RTX interface is still operational at https://arax.rtx.ai/
It is only in the demo branch (currently devED) where the KGNodeIndex.
I don't think updating our KGNodeIndex to KG2 when we're still querying KG1 was a wise move. We will need to back that out I think.

**Comment by edeutsch** [comment] 2020-03-06 20:47
Unless there is bleating of protest, I think I will move to having two simultaneous KGNodeIndexes, one for KG1 and one for KG2. Method calls will return the answers they always have in the past for KG1 unless you specify a new optional argument provider='KG2', in which case you will get that. But you'll need to ask for it explicitly. I think this will allow the new functionality but not break all the old stuff. And will enable the "normalization" thing a bit as well, because it can look in KG2 for comprehensive synonym CURIEs but return the suggested CURIE in the KG1 domain.

**Comment by dkoslicki** [comment] 2020-03-07 01:11
The only thing to keep in mind is if during the demo someone wants us to trot out `expand(...,KP=ARAX/KG2)`. Otherwise, two node indexes seems fine

**Comment by edeutsch** [comment] 2020-03-09 06:16
I have implemented separate KGNodexIndexs. Please rerun your Indexes:

cd $RTX/data/KGmetadata
rm NodeNames*
python3 dumpdata.py

cd $RTX/code/reasoningtool/kg-construction
python3 KGNodeIndex.py --build

python3 KGNodeIndex.py --test

Note that calls to KGNodeIndex now default to KG1. If you want KG2, you'll need to specify it:

curies = kgNodeIndex.get_curies('fanconi anemia', kg_name='KG2')

Please let me know if this causes a problem for anyone.

**Comment by edeutsch** [comment] 2020-03-10 21:52
I have upgraded the KGNodeIndex system again and pushed demo. I had to change the schema a bit to allow mapping to KG1, but this now seems to work. I also added a CURIE synonym translator based on KG2 and that seems to work pretty well.

To rebuild, similar to before, I suggest:

(using latest code from `demo` branch merged into your branch)

If you did this in block in the last 2 days, you don't need to do it again. But if you didn't do it last time, need to do it now:
cd $RTX/data/KGmetadata
rm NodeNames*
python3 dumpdata.py

# The following definitely needs to be done
cd $RTX/code/reasoningtool/kg-construction
rm KGNodeIndex.sqlite
python3 KGNodeIndex.py --build

python3 KGNodeIndex.py --test

What can you do now?
Transform CURIEs to KG1 compatible CURIEs:
    tests = ["CUI:C0031485", "CUI:C0017205", "UniProtKB:P06865", "MESH:D005199", "HEXA",
             "CHEBI:5855", "fanconi anemia", "ibuprofen"]
    for test in tests:
        curies = kgNodeIndex.get_KG1_curies(test)
        print(test+" = "+str(curies))
(curies is a list)
CUI:C0031485 = ['REACT:R-HSA-2160456']
CUI:C0017205 = ['DOID:1926']
UniProtKB:P06865 = ['UniProtKB:P06865']
MESH:D005199 = ['DOID:13636']
HEXA = ['UniProtKB:P06865']
CHEBI:5855 = ['CHEMBL.COMPOUND:CHEMBL521']
fanconi anemia = ['DOID:13636']
ibuprofen = ['CHEMBL.COMPOUND:CHEMBL521']

Or you can convert CURIEs to a desired namespace:
    tests = [ [ "CUI:C0031485", "DOID" ], [ "FMA:7203", "UBERON" ], [ "MESH:D005199", "DOID" ], 
             [ "CHEBI:5855", "CHEMBL.COMPOUND" ], [ "ibuprofen", "CUI" ] ]
    for test in tests:
        curies = kgNodeIndex.convert_curie(test[0], test[1])
        print(f"{test[0]} -> {test[1]} = " + str(curies))

CUI:C0031485 -> DOID = ['DOID:9281']                                                                                                                                                  
FMA:7203 -> UBERON = ['UBERON:0002113']                                                                                                                                               
MESH:D005199 -> DOID = ['DOID:13636']                                                                                                                                                 
CHEBI:5855 -> CHEMBL.COMPOUND = ['CHEMBL.COMPOUND:CHEMBL521']                                                                                                                         
ibuprofen -> CUI = ['CUI:C0020740', 'CUI:C0699202', 'CUI:C0699206', 'CUI:C0887194', 'CUI:C0020743', 'CUI:C0699207', 'CUI:C0600248', 'CUI:C0887195', 'CUI:C0887196', 'CUI:C0887190', 'C
UI:C0887191', 'CUI:C0699204', 'CUI:C0887188', 'CUI:C0887192', 'CUI:C0887189', 'CUI:C0887193']                                                                                         

Similar functionality may exist elsewhere in the codebase, but I don't recall where. But this is very fast and can do transformations based on what's in KG2.It does rely on linking concepts by name, so if the names are different, it won't know they're the same thing, of course..

Let me know if you have troubles.

**Comment by dkoslicki** [comment] 2020-03-10 23:31
@edeutsch @amykglen Someone should check that @amykglen's `expand(...,kp=RTX/KG2)` still works with the new indicies from this.
eg:
```
    elif params.example_number == 20:  # Now try with KG2 expander
        query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=CUI:C1452002, id=n00)",
            "add_qnode(type=chemical_substance, is_set=true, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00, type=interacts_with)",
            "expand(edge_id=e00, kp=ARAX/KG2)",
            "return(message=true, store=false)"
        ]}} 
```
from `ARAX_query.py 20`.

**Comment by saramsey** [comment] 2020-03-13 03:57
Where are we with this issue? @amykglen is this something that needs to be checked before the demo?

**Comment by amykglen** [comment] 2020-03-13 04:31
confirmed KG2 expand still works with the new KGNodeIndex:
```
$ python ARAX_query.py 20
config.json                                                              100% 3910    59.8KB/s   00:00    
null
Response:
  status: OK
  n_errors: 0  n_warnings: 0  n_messages: 33
  - 2020-03-12 22:28:14.831202 INFO: ARAXQuery launching
  - 2020-03-12 22:28:14.831233 INFO: Examine input query for needed information for dispatch
  - 2020-03-12 22:28:14.831247 INFO: Found input processing plan. Sending to the ProcessingPlanExecutor
  - 2020-03-12 22:28:14.831259 DEBUG: Entering executeProcessingPlan
  - 2020-03-12 22:28:15.084107 DEBUG: No starting messages were referenced. Will start with a blank template Message
  - 2020-03-12 22:28:15.085541 DEBUG: Found processing_actions
  - 2020-03-12 22:28:15.085589 INFO: Parsing input actions list
  - 2020-03-12 22:28:15.085610 DEBUG: Parsing action: create_message
  - 2020-03-12 22:28:15.086415 DEBUG: Parsing action: add_qnode(name=CUI:C1452002, id=n00)
  - 2020-03-12 22:28:15.087017 DEBUG: Parsing action: add_qnode(type=chemical_substance, is_set=true, id=n01)
  - 2020-03-12 22:28:15.087059 DEBUG: Parsing action: add_qedge(source_id=n00, target_id=n01, id=e00, type=interacts_with)
  - 2020-03-12 22:28:15.087103 DEBUG: Parsing action: expand(edge_id=e00, kp=ARAX/KG2)
  - 2020-03-12 22:28:15.087130 DEBUG: Parsing action: return(message=true, store=false)
  - 2020-03-12 22:28:15.097238 DEBUG: Considering action 'create_message' with parameters None
  - 2020-03-12 22:28:15.097267 INFO: Creating an empty template ARAX Message
  - 2020-03-12 22:28:15.097687 DEBUG: Considering action 'add_qnode' with parameters {'name': 'CUI:C1452002', 'id': 'n00'}
  - 2020-03-12 22:28:15.097711 INFO: Adding a QueryNode to Message with parameters {'id': 'n00', 'curie': None, 'name': 'CUI:C1452002', 'type': None, 'is_set': None}
  - 2020-03-12 22:28:15.098504 DEBUG: Looking up CURIE CUI:C1452002 in KgNodeIndex
  - 2020-03-12 22:28:15.104940 DEBUG: Considering action 'add_qnode' with parameters {'type': 'chemical_substance', 'is_set': 'true', 'id': 'n01'}
  - 2020-03-12 22:28:15.105034 INFO: Adding a QueryNode to Message with parameters {'id': 'n01', 'curie': None, 'name': None, 'type': 'chemical_substance', 'is_set': 'true'}
  - 2020-03-12 22:28:15.107013 DEBUG: Considering action 'add_qedge' with parameters {'source_id': 'n00', 'target_id': 'n01', 'id': 'e00', 'type': 'interacts_with'}
  - 2020-03-12 22:28:15.107256 INFO: Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': 'interacts_with'}
  - 2020-03-12 22:28:15.107526 DEBUG: Considering action 'expand' with parameters {'edge_id': 'e00', 'kp': 'ARAX/KG2'}
  - 2020-03-12 22:28:15.107691 DEBUG: Applying Expand to Message with parameters {'edge_id': 'e00', 'kp': 'ARAX/KG2'}
  - 2020-03-12 22:28:15.107818 INFO: Extracting sub query graph to expand
  - 2020-03-12 22:28:15.114313 INFO: Sending sub query graph to KG2Querier: {'nodes': [{'id': 'n00', 'curie': 'CUI:C1452002', 'type': 'chemical_substance', 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'chemical_substance', 'is_set': True}], 'edges': [{'id': 'e00', 'type': 'interacts_with', 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}]}
  - 2020-03-12 22:28:15.114349 DEBUG: Generating cypher based on query graph sent to KG2Querier
  - 2020-03-12 22:28:15.114659 DEBUG: Sending cypher query to KG2 neo4j
  - 2020-03-12 22:28:20.243407 INFO: Query returned 1 results (2 nodes, 1 edges)
  - 2020-03-12 22:28:20.243541 INFO: Processing query results
  - 2020-03-12 22:28:20.244501 INFO: Merging answer knowledge graph into Message.KnowledgeGraph
  - 2020-03-12 22:28:20.244565 INFO: After Expand, Message.KnowledgeGraph has 2 nodes and 1 edges
  - 2020-03-12 22:28:20.244606 DEBUG: Considering action 'return' with parameters {'message': 'true', 'store': 'false'}
```
so all is well from my end.

**Comment by saramsey** [comment] 2020-03-24 16:27
can we close this issue?

**Comment by amykglen** [comment] 2020-03-24 20:52
yep, I think so (Eric's new KGNodeIndex seems to be working well, both for KG1 and KG2)

**Closed by amykglen** 2020-03-24 20:52 UTC
Labels: ARAX demo
