### ISSUE TITLE
entering a bogus node type causes ARAX to crash

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#690] opened 2020-03-17 05:28 UTC
When running this DSL:

# Create the QueryGraph
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=prot, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)

# Expand a graph for this query
expand(edge_id=[e00,e01], kp=ARAX/KG1)

# Compute Jaccard metrics, filter, consult COHD
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)

# Generate final results, filter, and return
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)
return(message=true, store=true)

ARAX crashes.
It's not clear what the best fix is. I'm thinking that Expand() should throw an ERROR not a WARNING. I think we discussed that. Maybe that is already in the Expander branch?

**Comment by saramsey** [comment] 2020-03-23 20:26
does this involve resultify?

**Comment by edeutsch** [comment] 2020-03-23 22:24
No, ARAX crashes before it hits resultify. The crash is actually in Overlay/compute_jaccard.py
So that's a bug to be fixed.
But, there are philosophical questions that are raised about exactly how ARAX should behave in this situation that we might all do well to discuss.

**Comment by dkoslicki** [comment] 2020-03-24 17:44
@dkoslicki 
- [ ] check into error that `compute_jaccard.py`
- [ ] fix error
- [ ] if code crashes, ping Amy to throw an error on expand with bogus node to prevent subsequent expansion

**Comment by amykglen** [comment] 2020-04-28 14:15
I think this can be closed? (addressed in #713) Confirmed on beta that the original DSL @edeutsch posted now throws an error on expand ("No paths were found in KG1 satisfying this query graph")

**Comment by edeutsch** [comment] 2020-04-28 14:44
I wonder if we still have the bug that overlay/compute_jaccard crashes (instead of graceful error) if it is given an empty graph? Maybe good to quickly fix that too?

**Comment by amykglen** [comment] 2020-04-28 16:44
That's true - I suppose that would be good to fix. Especially since `expand` technically can be run with `continue_if_no_results=true`, which would pass on an empty knowledge graph.

**Comment by dkoslicki** [comment] 2020-04-29 15:40
Yeah, I still haven't had a chance to fix this in `compute_jaccard.py` yet, and I agree it's a bug that it's not gracefully handling an empty QG

**Comment by dkoslicki** [comment] 2020-04-29 15:41
@amykglen @edeutsch is there an `ARAX_query.py X` where `X` is the example that causes this crash so I can test my fix?

**Comment by amykglen** [comment] 2020-04-29 15:48
I don't think there's one in there currently, but here's one:
```
query = {"previous_message_processing_plan": {"processing_actions": [
    "create_message",
    "add_qnode(name=DOID:14330, id=n00)",
    "add_qnode(type=not_a_real_type, is_set=true, id=n01)",
    "add_qnode(type=chemical_substance, id=n02)",
    "add_qedge(source_id=n00, target_id=n01, id=e00)",
    "add_qedge(source_id=n01, target_id=n02, id=e01, type=molecularly_interacts_with)",
    "expand(edge_id=[e00,e01], continue_if_no_results=true)",
    "overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)",
    "return(message=true, store=false)"
]}}
```

**Comment by dkoslicki** [comment] 2020-04-29 20:23
Fixed by throwing a warning instead of an error. Merged into master, ready for testing in production/beta

**Comment by dkoslicki** [comment] 2020-04-29 20:25
@edeutsch test via `python ARAX_query.py 690` or via the UI DSL command:
```
add_qnode(name=DOID:14330, id=n00)
add_qnode(type=not_a_real_type, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=molecularly_interacts_with)
expand(edge_id=[e00,e01], continue_if_no_results=true)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
return(message=true, store=true)
```
Expected behavior is 3 warnings, no errors, and no results (and empty KG)

**Comment by edeutsch** [comment] 2020-04-29 20:34
Rolled out master to beta and verified. Looks good, thanks!
https://arax.rtx.ai/beta/?m=1772

**Closed** 2020-04-29 20:37 UTC
Labels: need to test on production
