### ISSUE TITLE
Got an error from ARAX_expander

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#2392] opened 2024-10-01 19:43 UTC
Hi @amykglen,

I recently added a new test for xDTD (`test_xdtd_issue2160`) which runs the following query:
```
  {
      "edges": {
          "t_edge": {
          "attribute_constraints": [],
          "knowledge_type": "inferred",
          "object": "on",
          "predicates": [
              "biolink:treats"
          ],
          "qualifier_constraints": [],
          "subject": "sn"
          }
      },
      "nodes": {
          "on": {
          "categories": [
              "biolink:Disease"
          ],
          "constraints": [],
          "ids": [
              "MONDO:0019600"
          ],
          },
          "sn": {
          "categories": [
              "biolink:SmallMolecule"
          ],
          "constraints": [],
          "ids": [
              "PUBCHEM.COMPOUND:23931"
          ],
          }
      }
  }
```

I got the following error:
```
[UncaughtARAXiError] An uncaught error occurred: 't_edge': ['Traceback (most recent call last):\n', '  File "/scratch2/cqm5886/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_query.py", line 781, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/scratch2/cqm5886/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_expander.py", line 512, in apply\n    edge_keys_to_remove = {edge_key for edge_key, edge in overarching_kg.edges_by_qg_id[qedge_key].items()\n', "KeyError: 't_edge'\n"]

```

Could you please help me take a look at this issue? Thank you!

**Comment by amykglen** [comment] 2024-10-01 21:08
hm, sure, taking a look now

**Comment by amykglen** [comment] 2024-10-01 21:25
ok, this is fixed in `master`! it looks like this query produces no results (from xdtd or KPs), which was resulting in an error in the patch for #2328

**Comment by chunyuma** [comment] 2024-10-01 21:44
Thanks so much @amykglen. The "no results (from xdtd or KPs)" is consistent with previous result: https://github.com/RTXteam/RTX/issues/2160#issuecomment-1760387482.

**Comment by edeutsch** [comment] 2024-10-02 17:45
latest `master` just deployed to arax.ncats.io

**Comment by amykglen** [comment] 2024-10-02 17:53
confirmed this query no longer produces an error on ARAX endpoints tracking `master` - closing

**Closed by amykglen** 2024-10-02 17:53 UTC
Labels: verify in next deployment
