### ISSUE TITLE
Inverted edges (and mistyped nodes?)

### ISSUE THREAD

**Issue by cbizon** [RTXteam/RTX#1546] opened 2021-06-30 17:02 UTC
Input query posted to https://arax.ncats.io/api/rtxkg2/v1.1/query. 
```
query = {
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
            "MONDO:0005148"
          ],
          "categories": [
            "biolink:Disease"
          ],
          "is_set": False
        },
        "n1": {
          "categories": [
            "biolink:PhenotypicFeature"
          ],
          "is_set": False
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1",
          "predicates": [
            "biolink:has_phenotype"
          ]
        }
      }
    }
  }
}
```

i.e. what are the phenotypes of T2D?

This returns a bunch of edges where the object, rather than the subject is T2D:

```
"15088456": {
                "attributes": [
                    {
                        "attribute_source": "infores:rtx-kg2",
                        "attribute_type_id": "biolink:knowledge_source",
                        "value": "infores:monarch",
                        "value_type_id": "biolink:InformationResource"
                    }
                ],
                "object": "MONDO:0005148",
                "predicate": "biolink:has_phenotype",
                "subject": "MONDO:0000383"
            },
            "15088920": {
                "attributes": [
                    {
                        "attribute_source": "infores:rtx-kg2",
                        "attribute_type_id": "biolink:knowledge_source",
                        "value": "infores:monarch",
                        "value_type_id": "biolink:InformationResource"
                    }
                ],
                "object": "MONDO:0005148",
                "predicate": "biolink:has_phenotype",
                "subject": "MONDO:0000385"
            },
            "15089190": {
                "attributes": [
                    {
                        "attribute_source": "infores:rtx-kg2",
                        "attribute_type_id": "biolink:knowledge_source",
                        "value": "infores:monarch",
                        "value_type_id": "biolink:InformationResource"
                    }
                ],
                "object": "MONDO:0005148",
                "predicate": "biolink:has_phenotype",
                "subject": "MONDO:0000386"
            },
```

Additionally, many of these new subjects are bound to n1 but I would classify them as Diseases rather than PhenotypicFeatures.

**Comment by amykglen** [comment] 2021-06-30 18:29
thanks for the report. the inverted edges are actually because ARAX/RTX-KG2's current intended behavior is to ignore QEdge direction, though we're planning to change this so that direction is only ignored for "symmetric" predicates (according to Biolink) in #1527.

as for the Diseases vs. PhenotypicFeatures - this is also a design decision: we decided to conflate Diseases and PhenotypicFeatures (similar to how we conflate Proteins/Genes). though I'm sure it's up for debate whether that's the best decision. :)

**Comment by finnagin** [comment] 2022-02-02 06:16
Closing as #1527 has been resolved.

**Closed** 2022-02-02 06:15 UTC
