### ISSUE TITLE
Not all LOINCs are procedures?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1292] opened 2021-03-14 03:30 UTC
I'm getting the impression that the KG2 build process is calling all LOINCs a biolink:Procedure, when it seems pretty clear that a large number are not. Is there a way to determine the category of a LOINC rather than calling them all procedures?

e.g., see the LOINCs here:
https://arax.ncats.io/?term=thymus

**Comment by kvarforl** [comment] 2021-03-15 21:36
Yep, looks like you're right:
from kg2.5.2
```
match (n) where n.id contains 'LOINC' return n.category, count(*) order by count(*) desc
```

n.category | count(*)
-- | --
"biolink:Procedure" | 260726

I'll look into it now!

**Comment by kvarforl** [comment] 2021-03-15 22:05
Looks like there are TUI's and CUI's associated with  each LOINC node entry, so assigning better categories should be possible:
```
ubuntu@ip-172-31-59-26:~/kg2-build$ grep -A 15 -m 1  "LP249177-9" umls-lnc.json
      "id" : "http://purl.bioontology.org/ontology/LNC/LP249177-9",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "https://identifiers.org/umls:has_tui",
          "val" : "T023"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#prefLabel",
          "val" : "Thymus gland"
        }, {
          "pred" : "https://identifiers.org/umls:has_cui",
          "val" : "C0040113"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#notation",
          "val" : "LP249177-9"
        } ]
      },
```

This will require a better understanding of how `multi_ont_to_json_kg.py` works, so I'm tagging @ericawood  to ask for their help in investigating :)

**Comment by ericawood** [comment] 2021-03-16 00:31
Well, the problem is in these three lines:

https://github.com/RTXteam/RTX/blob/698fab0d5ac507e92b5190878922f9fa5b72d9a7/code/kg2/curies-to-categories.yaml#L17

https://github.com/RTXteam/RTX/blob/698fab0d5ac507e92b5190878922f9fa5b72d9a7/code/kg2/multi_ont_to_json_kg.py#L225-L226

Essentially, since `LOINC:LP249177-9` itself is not in curies-to-categories.yaml, the category given to the source is given to that node. `curies-to-categories.yaml` mappings, including those source mappings take priority over TUI mappings. There are three possible routes to change this:

1. Map `LOINC:LP249177-9` to `biolink:gross_anatomical_entity` as its TUI maps in `curies-to-categories.yaml`: https://github.com/RTXteam/RTX/blob/698fab0d5ac507e92b5190878922f9fa5b72d9a7/code/kg2/curies-to-categories.yaml#L263
2. Get rid of the LOINC prefix mapping in `curies-to-categories.yaml`
3. Make some big, systemic changes to switch priority to TUIs in `multi_ont_to_json_kg.py`

**Comment by edeutsch** [comment] 2021-03-16 00:56
A one-off fix that affects this CURIE only will not help much. There are *thousands* of these. The above is just a single example. All LOINCs are being set to biolink:Procedure where the reality is that a huge number of LOINCs are not procedures, but a variety of other types. So I think maybe that means option 3?

**Comment by kvarforl** [comment] 2021-03-16 16:23
I'm curious to see what happens with option 2! If I'm not misinterpreting things, I think that removing the curie prefix mapping would cause each individual node to be assigned its TUI category (which is more dynamic than the blanket assignment of "procedure").

**Comment by edeutsch** [comment] 2021-03-17 01:07
That sounds good. I confess I don't really understand the distinction between 2 and 3. But I think just blindly setting them all to biolink:Procedure is not the way to go. And just fixing this one example is not the way to go.

**Comment by saramsey** [comment] 2021-03-17 01:31
I concur with the KG2 team, option 2 is looking good. Thank you.

**Comment by ericawood** [comment] 2021-03-17 22:06
Here's the output of `report_stats_on_json_kg.py`'s `number_of_nodes_by_source_and_category`:
Before testing option 2:
```
         "umls_source:LNC": {
             "information_content_entity": 1,
             "procedure": 260726
         }
```
After testing option 2:
```
         "umls_source:LNC": {
             "activity": 450,
             "agent": 100,
             "anatomical_entity": 1622,
             "cell": 719,
             "cellular_component": 76,
             "chemical_substance": 18397,
             "device": 578,
             "disease": 2255,
             "disease_or_phenotypic_feature": 24576,
             "drug": 18,
             "genomic_entity": 946,
             "geographic_location": 344,
             "gross_anatomical_structure": 2689,
             "individual_organism": 2392,
             "information_content_entity": 1,
             "molecular_activity": 24,
             "molecular_entity": 27135,
             "named_thing": 131708,
             "pathological_process": 396,
             "phenomenon": 1096,
             "physiological_process": 3296,
             "population_of_individual_organisms": 188,
             "procedure": 7847,
             "protein": 163
         }
```

**Comment by ericawood** [comment] 2021-03-17 22:08
Here's what `LOINC:LP249177-9` looks like after that change:
```
{
    "category": "biolink:GrossAnatomicalStructure",
    "category_label": "gross_anatomical_structure",
    "creation_date": null,
    "deprecated": false,
    "description": null,
    "full_name": "Thymus gland",
    "id": "LOINC:LP249177-9",
    "iri": "http://purl.bioontology.org/ontology/LNC/LP249177-9",
    "name": "Thymus gland",
    "provided_by": "umls_source:LNC",
    "publications": [],
    "replaced_by": null,
    "synonym": [],
    "update_date": "2020"
}
```

**Comment by edeutsch** [comment] 2021-03-17 22:59
Fabulous! Many thanks! That will help the NodeSynonymizer a lot!

**Comment by ericawood** [comment] 2021-04-24 00:05
This appears to be fixed in `KG2.6.0`: 

`match (n) where n.id contains 'LOINC' return n.category, count(n) order by count(n) desc` (Thank you Lindsey for the Cypher)

n.category | count(n)
-- | --
"biolink:NamedThing" | 131708
"biolink:MolecularEntity" | 35120
"biolink:InformationContentEntity" | 33711
"biolink:DiseaseOrPhenotypicFeature" | 24576
"biolink:ChemicalSubstance" | 10163
"biolink:Procedure" | 7847
"biolink:PhysiologicalProcess" | 3296
"biolink:GrossAnatomicalStructure" | 2689
"biolink:IndividualOrganism" | 2392
"biolink:Disease" | 2255
"biolink:AnatomicalEntity" | 1622
"biolink:Phenomenon" | 1096
"biolink:GenomicEntity" | 946
"biolink:Cell" | 719
"biolink:Device" | 578
"biolink:Activity" | 450
"biolink:PathologicalProcess" | 396
"biolink:GeographicLocation" | 344
"biolink:Drug" | 267
"biolink:PopulationOfIndividualOrganisms" | 188
"biolink:Protein" | 163
"biolink:Agent" | 100
"biolink:CellularComponent" | 76
"biolink:MolecularActivity" | 24

**Closed by ericawood** 2021-04-24 00:05 UTC
Labels: bug, kg2, verify this fix in next KG2 build
