### ISSUE TITLE
OpenTelemetry issues reported by ARS group

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2378] opened 2024-09-17 21:17 UTC
Today I received this from Shervin:

_Hi, 
i wanted to circle back with you about the ARAX jeager tracing, currently the ARAX message trace comes back to us under the initial submit trace but not not under the arax asyncquery endpoint. we are looking to ideally have sth like aragorn here https://translator-otel.ci.transltr.io/trace/7f8711d7afac23bcbbe72fc06b70df44 Do you think thats achievable for ARAX as well?_

I don't know anything about the OpenTelemetry implementation or even really what this means.
It looks like @kvnthomas98 implemented our OpenTelemetry, see #2186 
Some more, perhaps related info at https://github.com/NCATSTranslator/Feedback/issues/925

@kvnthomas98 would you be able to address this? I don't know where to start.

**Comment by kvnthomas98** [comment] 2024-09-18 15:02
Hi @edeutsch , I'll look into this today

**Comment by kvnthomas98** [comment] 2024-10-01 16:22
This is fixed in fixed in CI(confirmed by Shervin): [sample trace](https://translator-otel.ci.transltr.io/trace/c3dd8882f3fab5ed039303c0aca0a9berl).

We were using a BatchSpanExporter which sends traces 5 seconds after the last time traces got sent or if it reaches a batch size of 50.
As ARAX forks a child process whenever a new query comes in and since sending the response to the callback url is the last step in our process, some traces still remain in the buffer.
After the child process completes this last trace kept getting lost. So we now use a SimpleSpanExporter, which exports traces immediately and nothing is lost in the buffer.

**Closed by kvnthomas98** 2024-10-01 16:22 UTC
