### ISSUE TITLE
pathway without the members of the pathway

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1215] opened 2021-02-02 19:33 UTC
match (n:`biolink:Pathway`{id:"REACT:R-HSA-8851907"}) return n

should have MET and AKT in the pathway, but doesn't:
match p=(n:`biolink:Pathway`{id:"REACT:R-HSA-8851907"})-[]-() return p
returns no results

**Comment by saramsey** [comment] 2021-02-02 21:30
Verifying that we are pulling KG1 data from this location:
```
   "KG1": {
        "neo4j": {
            "bolt": "bolt://arax.ncats.io:7687",
            "database": "arax.ncats.io:7474/db/data",
            "username": "neo4j",
```

**Comment by saramsey** [comment] 2021-02-02 21:34
confirmed, that node has no neighbors in the (very old) version of Reactome that we ETL'd into KG1:
<img width="576" alt="Screen Shot 2021-02-02 at 1 32 56 PM" src="https://user-images.githubusercontent.com/5562107/106665459-2c9f5180-655b-11eb-8248-978f2eb74500.png">

I think the best way to handle this may be to do a full ETL of the current version of Reactome.

**Comment by saramsey** [comment] 2021-02-02 21:37
You may wish to look at `PathWhiz.ElementCollection:342` which has several neighbors in the KG2:

<img width="1072" alt="Screen Shot 2021-02-02 at 1 36 37 PM" src="https://user-images.githubusercontent.com/5562107/106665860-b0f1d480-655b-11eb-8a67-b4fc01bb0dae.png">

I am aware that `PathWhiz.ElementCollection:342` is currently erroneously labeled with category `biolink:ChemicalSubstance` but that will be fixed in the commits logged under issue #1214.

**Comment by saramsey** [comment] 2021-02-02 21:42
Note also, in KG2.5.1:

<img width="694" alt="Screen Shot 2021-02-02 at 1 42 07 PM" src="https://user-images.githubusercontent.com/5562107/106666453-78062f80-655c-11eb-8abe-7d68da130d6c.png">

**Comment by dkoslicki** [comment] 2021-02-02 21:54
Hmm... I was looking in KG2.5.1:
![Capture](https://user-images.githubusercontent.com/6362936/106667417-e5bf5500-6576-11eb-8a8a-c1e12f6d6592.PNG)

The motivation was the following:
look for all akt containing pathways:
```
match (n:`biolink:Pathway`) where toLower(n.name) contains "akt" return n.name, n.id
```
Then note that the last one (REACT:R-HSA-8851907) answers the question we were considering (how do MET and AKT interact?), and trying to find if we could have discovered this by asking what pathways MET and AKT have in common.

**Comment by saramsey** [comment] 2021-02-02 21:58
I don't think they are synonymous. AKT is RAC-alpha serine/threonine-protein kinase and PI3K is phosphoinositide 3-kinase, right?

**Comment by saramsey** [comment] 2021-02-02 22:03
This query might be helpful?

```
match (n:`biolink:Pathway`)-[r]-(m) where lower(m.name) = 'akt' return n.id, n.name;
```

<img width="698" alt="Screen Shot 2021-02-02 at 2 03 27 PM" src="https://user-images.githubusercontent.com/5562107/106668706-712cec00-655f-11eb-8175-f5e62395fb58.png">

**Comment by saramsey** [comment] 2021-02-02 22:05
Closing this issue since at this point the main path forward is #636

**Closed by saramsey** 2021-02-02 22:05 UTC
Labels: kg2
