### ISSUE TITLE
Improper response returned when furnished id does not exist

### ISSUE THREAD

**Issue by isbluis** [RTXteam/RTX#2222] opened 2023-12-01 09:04 UTC
Recent changes (in the past week?) have caused the `/response` endpoint to furnish invalid responses instead of a `404` when called with a **non-existent id**.

To test, call `/response` on _dev_ with a nonexistent id, e.g.
`wget https://arax.ncats.io/devLM/api/arax/v1.4/response/34564678678678`

response is:
```
[
  {
    "detail": "There is no response corresponding to response_id=34564678678678",
    "status": 404,
    "title": "Response not found",
    "type": "about:blank"
  },
  404
]
```

In _production_, the previous/"correct?" response is:
`wget https://arax.ncats.io/api/arax/v1.4/response/34564678678678`

```
--2023-12-01 08:53:38--  https://arax.ncats.io/api/arax/v1.4/response/34564678678678
Resolving arax.ncats.io (arax.ncats.io)... 35.81.149.105
Connecting to arax.ncats.io (arax.ncats.io)|35.81.149.105|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2023-12-01 08:53:39 ERROR 404: NOT FOUND.
```
Tagging @saramsey at the suggestion of @edeutsch ; please assign as you see fit.  Thanks!

**Comment by saramsey** [comment] 2023-12-01 17:33
Thanks for bringing this to my attention, @isbluis. I have a sneaking suspicion this is a bug due to my efforts to forkify `response_controller.py`. Hmm. I will take a look.

**Comment by edeutsch** [comment] 2023-12-01 18:55
My recollection is that when you return a 2-element list to the Flask framework, the first element is the HTTP content, and the second element is the HTTP status code. OR something like that. If only one item is returned to the framework, that item is the content and the HTTP status code is assumed to be 200.

i.e. if the status code is something besides 200, you need to return that code in addition to the content.

**Comment by saramsey** [comment] 2023-12-01 22:32
Thanks, Eric. Super helpful.

**Comment by saramsey** [comment] 2023-12-01 22:37
Problem confirmed on `arax.ncats.io/test`; it is inappropriately returning a 200 status code:
```
stephenr@ip-172-31-53-16:~$ curl -i https://arax.ncats.io/test/api/arax/v1.4/response/34564678678678
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 01 Dec 2023 22:37:01 GMT
Content-Type: application/json
Content-Length: 181
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS
X-Frame-Options: SAMEORIGIN

[
  {
    "detail": "There is no response corresponding to response_id=34564678678678",
    "status": 404,
    "title": "Response not found",
    "type": "about:blank"
  },
  404
]
```
and that it is working correctly on `arax.ncats.io` (i.e., production):
```
stephenr@ip-172-31-53-16:~$ curl -i https://arax.ncats.io/api/arax/v1.4/response/34564678678678
HTTP/1.1 404 NOT FOUND
Server: nginx
Date: Fri, 01 Dec 2023 22:36:45 GMT
Content-Type: application/json
Content-Length: 158
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS

{
  "detail": "There is no response corresponding to response_id=34564678678678",
  "status": 404,
  "title": "Response not found",
  "type": "about:blank"
}
```

**Comment by saramsey** [comment] 2023-12-01 22:37
Creating branch `issue-2222` to work this issue.

**Comment by saramsey** [comment] 2023-12-01 23:13
Commit merged to `master` and branch `issue-2222` has been deleted.

**Comment by saramsey** [comment] 2023-12-01 23:16
@isbluis I've committed a patch for this issue, to `master`. Sorry about this bug. I've tested the test on `/test`, and it works. I've rolled out the patch to `/test` on `arax.ncats.io` (but haven't yet rolled it out to other endpoints).

**Closed by saramsey** 2023-12-01 23:16 UTC

**Comment by saramsey** [comment] 2023-12-01 23:20
The cause of this issue, apart from my carelessness, is the fact that JSON is a poor serialization for built-in python objects. Basically, 
`json.loads(json.dumps((1,2,3)))` is a list:
```
>>> import json
>>> x = (1,2,3)
>>> type(x)
<class 'tuple'>
>>> x2 = json.loads(json.dumps(x))
>>> type(x2)
<class 'list'>
>>> x2
[1, 2, 3]
```
