### ISSUE TITLE
need EPC information on query results

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1792] opened 2022-02-09 22:32 UTC
This issue was brought to my attention by Rosina Weber from Team Explanatory Agent.

Here is the ARS link for the query that Explanatory Agent's team ran: https://arax.ncats.io/?r=769be14d-d53f-4327-a761-a7a2b53972ae

Their team would like to see more Evidence, Provenance,  and Confidence/Context (EPC) information for edges in RTX-KG2 query results, such as the result 1 (_NPHS1_), as shown here:

<img width="850" alt="Screen Shot 2022-02-09 at 2 29 31 PM" src="https://user-images.githubusercontent.com/5562107/153301337-83b712ce-f47a-4780-8177-262baa494a2e.png">

Specifically, there is nothing quantitative (nor a list of publications) in the edges that their tool could use to score the result-graph. It looks like the subject score and the list of PMIDs didn't make it through?

**Comment by saramsey** [comment] 2022-02-09 22:38
The PMIDs or score are not in the JSON response either, so it does not appear to be a UI issue: https://arax.ncats.io/api/arax/v1.2/response/769be14d-d53f-4327-a761-a7a2b53972ae

**Comment by edeutsch** [comment] 2022-02-09 23:14
All the publication information is present when you query ARAX:
https://arax.ncats.io/?r=36721

But it seems to be true that when you pose the same query to RTX-KG2, all that extra information is not there. Presumably ARAX adds it?
https://arax.ncats.io/kg2/
```
{
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0009688"
      ],
      "categories": [
        "biolink:Disease"
      ],
      "is_set": false,
      "name": "myasthenia gravis"
    },
    "n1": {
      "ids": [
        "UMLS:C0699748"
      ],
      "categories": [
        "biolink:Disease",
        "biolink:NamedThing"
      ],
      "is_set": false,
      "name": "Pathogenesis"
    }
  }
}
```

**Comment by saramsey** [comment] 2022-02-10 00:17
thank you Eric and Amy for responding

**Comment by edeutsch** [comment] 2022-02-10 00:30
For the record, the RTX-KG2 API already has this in it in the Query class:
```
        return_minimal_metadata:
          type: boolean
          default: false
          description: >-
            Set to true in order to return only the most minimal metadata.
            By default, rich metadata for nodes and edges are supplied, which
            may cause a very large and slower Response.
 ```

I do not know if there's any code that does anything with it.

**Comment by amykglen** [comment] 2022-02-10 02:10
thanks - yeah, I think that's what we need to plug into Expand (nothing is hooked up to it yet)

**Comment by saramsey** [comment] 2022-02-16 22:12
also we should make the infores links (e.g., `infores:semmeddb`) clickable and have the link go to a user-understandable overview web page for the source

**Comment by saramsey** [comment] 2022-02-16 22:12
also we should ideally have ARAX results from SemMedDB include subject score, object score, and the sentence in the metadata (attribute list) for the edge.

**Comment by amykglen** [comment] 2022-02-16 22:17
> also we should ideally have ARAX results from SemMedDB include subject score, object score, and the sentence in the metadata (attribute list) for the edge.

I think we already do have this, for edges from KG2 at least:

![Screen Shot 2022-02-16 at 2 16 53 PM](https://user-images.githubusercontent.com/49423686/154366715-9e41272d-66c5-49a2-b332-5a9592053a6f.png)

**Comment by amykglen** [comment] 2022-04-04 17:11
@rcpeene - here's a little summary of what needs to be done here in case you work on this issue:

basically there is a `return_minimal_metadata` parameter somewhere in the info passed into Expand's `apply()`** method (I think?), and we essentially just need to add an `or not return_minimal_metadata` to this `if` clause:
https://github.com/RTXteam/RTX/blob/c51882200c3168bef2355fb33c9df612e9638f46/code/ARAX/ARAXQuery/ARAX_expander.py#L435-L438

and then make sure that in Expand's query of the KG2 API it specifies `return_minimal_metadata: True`. (omitting all the attributes makes processing faster, and then ARAX just adds the attributes at the end of processing.)

and then do a bunch of testing to make sure it's working (note that you'll need to **locally** set [this line](https://github.com/RTXteam/RTX/blob/c51882200c3168bef2355fb33c9df612e9638f46/code/ARAX/ARAXQuery/ARAX_expander.py#L84) to `True` in order to run in "RTXKG2" mode, like the KG2 API does, which is specifically the part you need to test). ideally you want to run test queries where `return_minimal_metadata` is true/false and print out the KG that the KG2 KP API returns (_before_ it's been processed by ARAX) and make sure that all the attributes (like publications, etc.) are not appearing/are appearing as expected.

** note that I think this `return_minimal_metadata` parameter may only exist for queries when in RTXKG2 mode (and not ARAX mode), so we might need to handle that. (i.e., if it doesn't exist, consider it to be False). @edeutsch knows more about this parameter than me, so he should be able to help with any questions about it.

**Comment by amykglen** [comment] 2022-05-18 22:06
@edeutsch - re: this comment of yours:

> For the record, the RTX-KG2 API already has this in it in the Query class:
> 
>         return_minimal_metadata:
>           type: boolean
>           default: false
>           description: >-
>             Set to true in order to return only the most minimal metadata.
>             By default, rich metadata for nodes and edges are supplied, which
>             may cause a very large and slower Response.
> I do not know if there's any code that does anything with it.

can you clarify where we can actually access the `return_minimal_metadata` parameter from within Expand? should it be in the `input_parameters` when in `RTXKG2` mode? (I'm not seeing it there) or where?

**Comment by edeutsch** [comment] 2022-05-19 05:57
yeah, it wasn't hooked up yet. I just committed some code that hooks it up. but now master is broken and failing with:

2022-05-19T05:54:29.964387 ERROR: [InvalidParameter] Supplied parameter return_minimal_metadata is not permitted for Expand

is that you wanted to implement this option?

**Comment by amykglen** [comment] 2022-05-19 15:50
yes, thanks! I just pushed some code to `master` that makes that makes that error go away. will finish the rest of the implementation later

**Comment by amykglen** [comment] 2022-05-19 20:14
@edeutsch - when sending a query to KG2, the `return_minimal_metadata` parameter should be specified on the same level as the `submitter`, right? like this?

```
{
   "message":{
      "query_graph":{
         "nodes":{
            "n0":{
               "ids":[
                  "UniProtKB:P84077"
               ],
               "categories":[
                  "biolink:Protein",
                  "biolink:Gene"
               ],
               "is_set":false
            },
            "n1":{
               "categories":[
                  "biolink:Protein",
                  "biolink:Gene"
               ],
               "is_set":true
            }
         },
         "edges":{
            "e0":{
               "predicates":[
                  "biolink:entity_negatively_regulates_entity"
               ],
               "subject":"n0",
               "object":"n1",
               "exclude":false
            }
         }
      }
   },
   "submitter":"infores:arax",
   "return_minimal_metadata":true
}
```
for some reason when I submit that query to KG2 (locally, so it should be using your latest code because I have my own machine acting as the KG2 API), the value of `return_minimal_metadata` is still always `False` when it's passed into Expand. wondering if the `True` value might be being overwritten somewhere?

**Comment by edeutsch** [comment] 2022-05-19 23:40
It's quite possible that I botched it. Is this using your own KG2 endpoint or a KG2 on arax.ncats.io. Although I checked in the code, I did not deploy it everywhere yet.

**Comment by edeutsch** [comment] 2022-05-20 00:04
yes, my mistake. fix just pushed. but not rolled out everywhere. Sorry!

**Comment by amykglen** [comment] 2022-05-20 00:23
no worries, thanks! ok, I just pushed code that finishes plugging this parameter into Expand. so once `master` is rolled out everywhere, the KG2 API will include all attributes in results (publications, etc.) by default.

(yet ARAX still only gets back minimal metadata when it queries KG2, as desired, since it now sets `return_minimal_metadata=true`)

**Comment by amykglen** [comment] 2022-06-01 22:14
still waiting for the next rollout to verify this is working as expected

**Comment by amykglen** [comment] 2022-06-22 23:32
confirmed this is working as expected on `kg2beta`! 

the KG2 API now includes all attributes - including publications - by default. that behavior can be turned off using the `return_minimal_metadata` flag:
```
{
   "message":{
      "query_graph":{
         "edges":{
            "e00":{
               "subject":"n00",
               "object":"n01",
               "predicates":[
                  "biolink:physically_interacts_with"
               ]
            }
         },
         "nodes":{
            "n00":{
               "ids":[
                  "CHEMBL.COMPOUND:CHEMBL112"
               ]
            },
            "n01":{
               "categories":[
                  "biolink:Protein"
               ]
            }
         }
      }
   },
   "submitter":"ARAX GUI",
   "stream_progress":true,
   "return_minimal_metadata":true,
   "query_options":{
      "kp_timeout":"30",
      "prune_threshold":"50"
   }
}
```

**Comment by amykglen** [comment] 2022-06-22 23:33
good to close this issue, @saramsey?

**Closed** 2022-08-03 21:15 UTC
Labels: expand
