### ISSUE TITLE
Harmful Results in ARAX Query "What Causes Autism?"

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX#2303] opened 2024-06-28 04:39 UTC
While investigating the presence of medical myths in RTX-KG2 (particularly those caused by retracted papers, see https://github.com/RTXteam/RTX-KG2/issues/386), I ran the query "what causes autism?" on ARAX:

https://arax.rtx.ai/?r=243414

![image](https://github.com/RTXteam/RTX/assets/36611732/fea87cce-e02e-42c9-9d70-fae7c58d2fc3)

The top result is "Vaccines". The second result is "Measles-Mumps-Rubella Vaccine". While RTX-KG2 is responsibly for passing along these edges, Steve recommended that I post an issue for ARAX as well. These two results are widely considered not just misinformation, but actively harmful. Is it possible that we could consider, for major medical myths like this, at least ranking harmful answers lower or blacklisting them entirely? Or is this dependent on RTX-KG2 to filter out these edges (which came largely from SemMedDB misparses)?

**Comment by chunyuma** [comment] 2024-07-03 15:51
The issue #2299 may be able to address this issue. I am now working on it.

**Comment by dkoslicki** [comment] 2024-07-03 17:13
Max's (@mfl15) SemMedDB filtering will probably help with this

**Comment by chunyuma** [comment] 2024-07-03 17:36
Hi Max (@mfl15), what is your thought on filtering out the PMIDs that SemMedDB claims to support the corresponding triples based on their sentences? How much computational resources and time we might need?  

An example: 
a triple - (Vaccines, causes, autism spectrum disorder)

SemMedDB PMID sentences: 
[PMID:22957409](https://pubmed.ncbi.nlm.nih.gov/22957409/) : At a time when many readily believe that vaccines cause autism, or that government scientists created AIDS as a weapon of black genocide, it is not surprising that medical quackery, especially cancer quackery, remains a flourishing and lucrative business throughout the developed world. (2012 Aug)
[PMID:20194286](https://pubmed.ncbi.nlm.nih.gov/20194286/) : Hispanic parents were also more likely to be concerned about serious adverse effects of vaccines and to believe that some vaccines cause autism. (2010 Apr)
[PMID:12455213](https://pubmed.ncbi.nlm.nih.gov/12455213/) : Do vaccines cause autism? (2002 Nov 18)
[PMID:16447135](https://pubmed.ncbi.nlm.nih.gov/16447135/) : Although current vaccine shortages do not appear to be related to issues of liability, a new wave of tort litigation alleging that some vaccines cause autism has led to speculation that history could repeat itself. (2006 Mar 01)
[PMID:29329259](https://pubmed.ncbi.nlm.nih.gov/29329259/) : Religious cults such as The People's Temple, Heaven's Gate, Aum Shinrikyo, and Islamic State (ISIS) and conspiracy beliefs such as assassinations, moon-hoax, and vaccine-induced autism beliefs are discussed using this construct. (2018 Jan 12)
[PMID:25002000](https://pubmed.ncbi.nlm.nih.gov/25002000/) : Somali parents were significantly more likely to believe that autism is caused by vaccines (35% vs. 8% of non-Somali parents). (2014)
[PMID:17928818](https://pubmed.ncbi.nlm.nih.gov/17928818/) : Despite compelling scientific evidence against a causal association, many parents and parent advocacy groups continue to suspect that vaccines, particularly measles-mumps-rubella (MMR) vaccine and thimerosal-containing vaccines (TCVs), can cause autism. (2007 Dec)
[PMID:20087185](https://pubmed.ncbi.nlm.nih.gov/20087185/) : There is no credible evidence that vaccines cause autism. (2010 Apr)
[PMID:19813430](https://pubmed.ncbi.nlm.nih.gov/19813430/) : The belief that vaccines cause autism was the most prevalent parental concern, reported by 70% of pediatricians. (2009 Sep)
[PMID:26529071](https://pubmed.ncbi.nlm.nih.gov/26529071/) : These providers expressed vaccine safety (87/680 (13%)) and efficacy (21/680 (31%)) concerns and stated belief in vaccine misperceptions: vaccine causes autism (34/668, 5%), multiple vaccines at a single visit reduces vaccine efficacy (43/680, 6%) or overwhelms the immune system (63/680, 9%), and administering HPV vaccine will increase the likelihood of unprotected adolescent sexual activity (29/680, 4%). (2015 Nov 27)
[PMID:26502656](https://pubmed.ncbi.nlm.nih.gov/26502656/) : After 5600 families of children diagnosed with autism filed claims with the National Vaccine Injury Compensation Program in the United States, the court selected 'test' cases consolidated into the Omnibus Autism Proceedings, held from 2007 to 2008, to examine claims that vaccines caused the development of autism. (2015 Aug)
[PMID:20453581](https://pubmed.ncbi.nlm.nih.gov/20453581/) : Despite incontrovertible evidence that vaccines do not cause autism, some parents continue to refuse them and many parents of children with autism seek hope in unproven and potentially harmful complementary and alternative (CAM) approaches. (2010 May)
[PMID:29904533](https://pubmed.ncbi.nlm.nih.gov/29904533/) : For example, communicating the lack of evidence that vaccines cause autism did not convince many reluctant parents to vaccinate their kids (Nyhan, Reifler, Richey, Freed, Pediatrics 133:e835-e842, 2014). (2018)
[PMID:22222344](https://pubmed.ncbi.nlm.nih.gov/22222344/) : More than 18% believed that vaccines can cause autism. (2012)
[PMID:25898051](https://pubmed.ncbi.nlm.nih.gov/25898051/) : IMPORTANCE: Despite research showing no link between the measles-mumps-rubella (MMR) vaccine and autism spectrum disorders (ASD), beliefs that the vaccine causes autism persist, leading to lower vaccination levels. (2015 Apr 21)
[PMID:22848999](https://pubmed.ncbi.nlm.nih.gov/22848999/) : That vaccines do not cause autism is now a widely accepted proposition, though a few dissenters remain. (2012 Apr)
[PMID:24590751](https://pubmed.ncbi.nlm.nih.gov/24590751/) : Refuting claims of an MMR/autism link successfully reduced misperceptions that vaccines cause autism but nonetheless decreased intent to vaccinate among parents who had the least favorable vaccine attitudes. (2014 Apr)
[PMID:26014839](https://pubmed.ncbi.nlm.nih.gov/26014839/) : Scientists believed in genetic causes while many parents believed in vaccines as the cause of autism. (2016 Apr)
[PMID:25176640](https://pubmed.ncbi.nlm.nih.gov/25176640/) : Two coders independently and reliably coded for the presence or absence of each of 15 myths about vaccination (e.g., "vaccines cause autism"), statements that countered these myths, and recommendations for or against vaccination. (2014 Oct 07)
[PMID:20812501](https://pubmed.ncbi.nlm.nih.gov/20812501/) : Recent studies have refuted the theory that the consecutive administration of vaccines weakens the young immune system in children, and leads to an autoimmune process that causes autism. (2010 Apr)

**Comment by mfl15** [comment] 2024-07-03 17:43
Hello Chunyu,

It is currently in progress and require extensive resources, I've already parallelized it, but looks like will need more scaling. Will keep you posted.


Thank you,

Maksym Lupei,<https://www.linkedin.com/in/drjennifernicholas/> Ph.D.

Postdoctoral Scholar
College of Engineering
Penn State University
W204 Westgate Building, University Park, PA 16802
________________________________

**Comment by chunyuma** [comment] 2024-07-03 17:47
Thank you @mfl15. No worries, since we discussed this in today's RTX team AHM, we would like to hear your thoughts.

**Comment by dkoslicki** [comment] 2024-09-25 17:50
This query seems to be much improved: https://arax.ci.transltr.io/?r=302450 Still has MMR vaccines, but not as top results (and the generic "vaccines" is now absent). Tentatively closing; LMK if you prefer to keep it open

**Closed by dkoslicki** 2024-09-25 17:50 UTC
