### ISSUE TITLE
ARAX returning results with predicates that are not supported by Biolink Model 3.1.2 

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1967] opened 2023-02-15 21:10 UTC
I looked into this very briefly so I thought I'd start an issue locally.

Related to this: https://github.com/NCATSTranslator/Feedback/issues/118

It seems like there are two possibilities:
1) KG2.8.0 contains "gene_associated_with_condition", which apparently it should not
2) They are querying production KG2.7.6 instead of CI KG2.8.0

The query in question appears to be:
827077 | 2023-02-15 19:42:47 | 40 | ars.ci.transltr.io | 52.4.10.150, 10.11.0.190 | arax.ci.transltr.io | arax-0 | ARAX | 5094 | 129227 | ✓ Completed | OK | Normal completion with 24 results.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Are the result is 
https://arax.ncats.io/?r=129227
https://arax.ncats.io/api/arax/v1.3/response/129227

As far as I can tell they are querying CI with KG2.8.0, so I think that rules out option 2. Although I am not really certain.

There is also potentially option 3:
3) As far as we were aware, the ask was for gene-chemical associations:
![image](https://user-images.githubusercontent.com/12707718/219162512-4c572434-56f4-4f5d-90f4-1e93f2d62393.png)
not for gene-disease associations. So this is not yet done.

That's about all I know. Tossing this out for others more knowledgeable..

**Comment by saramsey** [comment] 2023-02-17 18:59
Hi @edeutsch thank you for reporting this issue in the RTX project area so we can track it locally.  I guess my first order of business is to try and ascertain, when a query is posted on `ui.ci.transltr.io`, which ARAX endpoint is queried? How would we know?

**Comment by edeutsch** [comment] 2023-02-17 19:22
I'm uncertain that I understand the question correctly, but the endpoint is likely to be /async_query. But could be /query. I think an easy way to know is to look at the second log entry, and if it is "asynchronous Query launching on incoming Query", then you know that the endpoint was /async_query

**Comment by saramsey** [comment] 2023-02-17 21:01
Thanks @edeutsch. I didn't phrase my question well. I meant, what ARAX API base URL is being hit?  How do we know that it is an ARAX version that is hitting RTX-KG2.8.0c?

**Comment by edeutsch** [comment] 2023-02-17 21:10
Well, you can see in the OP that arax.ci.transltr.io is being hit. And arax.ci.transltr.io **should** be hitting KG2.8.0c. But it is not trivial to be sure. I sifted through the logs to find a tell and did not come up with one. I thought it listed in the logs exactly which KP endpoint URLs are being bit, but I didn't see it there. Maybe I just missed it.

I just went to arax.ci.transltr.io and issued our example query and only 17 results came back, which I think is the surest sign that arax.ci.transltr.io is using KG2.8.0c right now (KG2.7.6c returns >100). But was it 2.8.0c when the initial query was sent? I'm not 100% certain. I think so, but there is room for uncertainty here. Maybe we need to consider augmenting the log messages to make it more clear.

**Comment by saramsey** [comment] 2023-02-17 21:15
> Well, you can see in the OP that arax.ci.transltr.io is being hit. And arax.ci.transltr.io **should** be hitting KG2.8.0c. But it is not trivial to be sure. I sifted through the logs to find a tell and did not come up with one. I thought it listed in the logs exactly which KP endpoint URLs are being bit, but I didn't see it there. Maybe I just missed it.
> 
> I just went to arax.ci.transltr.io and issued our example query and only 17 results came back, which I think is the surest sign that arax.ci.transltr.io is using KG2.8.0c right now (KG2.7.6c returns >100). But was it 2.8.0c when the initial query was sent? I'm not 100% certain. I think so, but there is room for uncertainty here. Maybe we need to consider augmenting the log messages to make it more clear.

Thanks for your reply.  Because I cannot remember any of these details, I took a look at this Google Sheet which seems to aim to disambiguate the various ARAX instances:

https://docs.google.com/spreadsheets/d/1eC3GrRW6gw5zn7XKjvaHD9KCulO-GqEaTJ3mG6PgOOY/edit#gid=0

<img width="895" alt="Screen Shot 2023-02-17 at 1 13 00 PM" src="https://user-images.githubusercontent.com/5562107/219794551-7ea110c0-6592-44d1-bdaa-5641d585bdb2.png">

Isn't KG2.8.0c only served up in development maturity level ARAX installations?

**Comment by saramsey** [comment] 2023-02-17 21:18
Ah, wait, I see that the `master` branch of RTX has file `code/config_dbs.json` which is clearly referencing KG2.8.0c, 
<img width="1030" alt="Screen Shot 2023-02-17 at 1 18 41 PM" src="https://user-images.githubusercontent.com/5562107/219795505-e74eaa76-629b-4c88-b2a4-5c45fea3a00b.png">

**Comment by edeutsch** [comment] 2023-02-17 21:27
It is my understanding:

> I would imagine that arax.ci.transltr.io would be querying the RTX-KG2 service on kg2.ci.transltr.io. 

correct.

> As far as I know (but maybe I am out-of-date), that instance is running code from the master branch of the RTX project area,

correct. 

> whereas I thought that, in the RTX project area, all the KG2.8.0c stuff was in the kg2-integration branch.

This is true, but it is also now in master. So anything running master should have KG2.8.0.

> Paging @amykglen and @acevedol for a sanity check on what I just wrote.

**Comment by saramsey** [comment] 2023-02-17 21:28
Thanks @edeutsch. So, the view from the synonymizer supports your expectation that `arax.ci.transltr.io` is indeed backed by the RTX-KG2.8.0c KP: 

<img width="646" alt="Screen Shot 2023-02-17 at 1 26 30 PM" src="https://user-images.githubusercontent.com/5562107/219797158-744be51e-5521-41a3-8dea-d61387c25dcd.png">

**Comment by saramsey** [comment] 2023-02-17 21:34
> 1. KG2.8.0 contains "gene_associated_with_condition", which apparently it should not

Well, `gene associated with condition` is in the Biolink 3.0 spec (the version of Biolink against which RTX-KG2.8.0pre was built). Here is the permalink:
https://github.com/biolink/biolink-model/blob/1efe2ed5a738f9cb4c32566f8cb7e713f62fa1ab/biolink-model.yaml#L4420

That predicate is also not deprecated:

<img width="1123" alt="Screen Shot 2023-02-17 at 1 33 29 PM" src="https://user-images.githubusercontent.com/5562107/219798031-9f75b4e9-40bb-46c5-bd2e-dba9b55dc346.png">

**Comment by saramsey** [comment] 2023-02-17 21:37
Note, the predicate `gene associated with condition` is also in Biolink 3.1.2, and also (in that release) not deprecated:
<img width="1145" alt="Screen Shot 2023-02-17 at 1 36 18 PM" src="https://user-images.githubusercontent.com/5562107/219798379-61a368b2-3687-4556-bedd-6350d4a6c466.png">

Also, I note that in NCATSTranslator/Feedback issue 118, they didn't boldface `gene_associated_with_condition`, so I am not sure that is the predicate they were raising an issue about?

<img width="802" alt="Screen Shot 2023-02-17 at 1 36 53 PM" src="https://user-images.githubusercontent.com/5562107/219798456-4e53d104-cdee-4359-9f94-09e1b2c5c357.png">

**Comment by saramsey** [comment] 2023-02-17 21:38
Now, as to `KCNH3 [increases_activity_of] Gentamycin`, that's another story. Investigating now....

**Comment by edeutsch** [comment] 2023-02-17 21:39
ah, sorry, my error, I mis-inferred which predicate they were unhappy about

**Comment by saramsey** [comment] 2023-02-17 21:41
But RTX-KG2.8.0pre doesn't have that predicate! 

<img width="724" alt="Screen Shot 2023-02-17 at 1 40 30 PM" src="https://user-images.githubusercontent.com/5562107/219799053-914c098b-1dd7-448e-87f6-84bd220e6e62.png">

I am 100% certain of it. And yes, I am talking to RTX-KG2.8.0pre:

<img width="628" alt="Screen Shot 2023-02-17 at 1 41 06 PM" src="https://user-images.githubusercontent.com/5562107/219799140-828e36be-0a6e-4c51-8d18-47af4595551c.png">

**Comment by saramsey** [comment] 2023-02-17 21:44
So, my friends, we have a bit of a mystery on our hands. We have an ARAX result-set that supposedly comes from a query being executed via `ui.ci.transltr.io`,

https://arax.ncats.io/?r=cccb6699-29f4-492b-9733-ab77bd1a8261

that pulls up a collection of edges that includes a Biolink 2.X.X-era predicate (i.e., `biolink:increases_activity_of`).

**Comment by saramsey** [comment] 2023-02-17 21:45
Here is the JSON query:

```
{
  "edges": {
    "N1": {
      "attribute_constraints": [],
      "object": "sn",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "qualifier_constraints": [],
      "subject": "on"
    },
    "creative_DTD_qedge_0": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_0",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "sn"
    },
    "creative_DTD_qedge_1": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_1",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_0"
    },
    "creative_DTD_qedge_2": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "on",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_1"
    },
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "creative_DTD_qnode_0": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    },
    "creative_DTD_qnode_1": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    },
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0007972"
      ],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:NamedThing"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by saramsey** [comment] 2023-02-17 22:10
So, here is the edge in question. Note the Biolink-3.0-compatible predicate:

<img width="1191" alt="Screen Shot 2023-02-17 at 2 10 25 PM" src="https://user-images.githubusercontent.com/5562107/219803337-694f0316-b5fc-41ad-b38a-f904d73031a7.png">

**Comment by saramsey** [comment] 2023-02-17 22:11
And if we click on the edge, we see:

<img width="592" alt="Screen Shot 2023-02-17 at 2 11 01 PM" src="https://user-images.githubusercontent.com/5562107/219803432-734b59d1-2176-4613-ace8-affee1510579.png">

**Comment by saramsey** [comment] 2023-02-17 22:12
This latest evidence motivates me to ask, what exactly tells us that `ui.ci.transltr.io` is querying `arax.ci.transltr.io` (and not some other ARA instance) via the ARS?

**Comment by edeutsch** [comment] 2023-02-17 22:30
aha, wait a sec. The query_graph you show above has lots of "creative_DTD" stuff in it (that I don't fully understand).. what if this edge is coming out of DTD results? and not from KG2.8.0c itself?

**Comment by saramsey** [comment] 2023-02-17 22:54
Would DTD be giving an edge with 'biolink:increases_activity_of` as the predicate?

**Comment by saramsey** [comment] 2023-02-17 22:56
Wouldn't DTD leave some trace in the edge attributes (like EPC type stuff?), that it was a _predicted_ edge?

**Comment by edeutsch** [comment] 2023-02-17 23:31
I don't know. Perhaps my idea is preposterous. But sometimes that's all I've got. Quite often, actually..
I think we may need @amykglen and @chunyuma to come to the rescue..

**Comment by saramsey** [comment] 2023-02-17 23:37
So, I have confirmed that in **KG2.7.6c**, the bad predicate is there:

<img width="1342" alt="Screen Shot 2023-02-17 at 3 36 57 PM" src="https://user-images.githubusercontent.com/5562107/219816870-025466ea-bf3c-433b-9956-366a76e794be.png">

**Comment by saramsey** [comment] 2023-02-17 23:39
At this point, I am fairly confident that, somehow, the cached result posted in [NCATSTranslator/Feedback issue 118](https://github.com/NCATSTranslator/Feedback/issues/118) is against RTX-KG2.7.6c.

**Comment by amykglen** [comment] 2023-02-18 01:06
so I think because the original query was a `knowledge_type: inferred` query, I don't think RTX-KG2 is actually being queried directly as a KP (at least in the usual sense).

 I think it's XDTD that added all those KG2 edges, as @edeutsch suggested - and I don't know the details of how XDTD does that. not sure if it queries KG2 at runtime? but certainly those edges are from an older KG2 version. @chunyuma or @dkoslicki would know the details about where those edges are coming from.

of note, the edges added by XDTD seem to be lacking attributes (except for one attribute each, indicating they came from KG2); that probably isn't ideal. at the very least we should be 'tagging' those edges to make it clear they were added by XDTD, I'd think?

**Comment by saramsey** [comment] 2023-02-18 06:10
> so I think because the original query was a `knowledge_type: inferred` query, I don't think RTX-KG2 is actually being queried directly as a KP (at least in the usual sense).
> 
> I think it's XDTD that added all those KG2 edges, as @edeutsch suggested - and I don't know the details of how XDTD does that. not sure if it queries KG2 at runtime? but certainly those edges are from an older KG2 version. @chunyuma or @dkoslicki would know the details about where those edges are coming from.
> 
> of note, the edges added by XDTD seem to be lacking attributes (except for one attribute each, indicating they came from KG2); that probably isn't ideal. at the very least we should be 'tagging' those edges to make it clear they were added by XDTD, I'd think?

Thank you, @amykglen.  Agreed on all points.

**Comment by saramsey** [comment] 2023-02-21 17:54
Hi @chunyuma when you have a moment, could you please weigh in on this?  We want to know if the DTD module could be adding edges to the query-specific KG, with predicates like `biolink:increases_activity_of`.

**Comment by dkoslicki** [comment] 2023-02-21 18:43
Sorry for the delay @saramsey and @amykglen. The xDTD model does not query KG2 at run-time. This is likely a problem due to training the xDTD model on a previous version of KG2 and predicates have since changed. @chunyuma said he can look into how to address that. Any idea what the priority level is for this?

**Comment by chunyuma** [comment] 2023-02-21 19:20
Hi @saramsey @edeutsch @amykglen, I'm sorry for the late response. We did introduce some non-biolink predicates into the system. I [mentioned this issue](https://github.com/RTXteam/RTX/issues/1959) previously but it seems not a big issue. However, xDTD or xCRG doesn't use the predicates (like `biolink:increases_activity_of` or `biolink:decreases_activity_of `). They seem to be in the KG2c for a while because I saw them in many scripts ([here](https://github.com/RTXteam/RTX/blob/f1abafe508e49031805df70a9ee842e1b357b1c2/code/ARAX/test_async_demo_workflows/2021-12_demo/workflowA/A.2a_expanded_RHOBTB2_twohop.json#L30), [here](https://github.com/RTXteam/RTX/blob/b2aea971a4834b43fe9fd6315bea4f23aecceb46/code/ARAX/test/test_ARAX_workflows.py#L835-L855), and [here](https://github.com/RTXteam/RTX/blob/ad285b9c7bda946cf2e744301b2dd7695281cb60/code/ARAX/test/test_ARAX_expand.py#L1070)).

Here are a few non-predicates introduced by DTD, and some Overlay modules:

DTD (e.g. `predict_drug_treats_disease.py`) model introduces [biolink:probably_treats](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py#L460)
FET (e.g. `fisher_exact_test.py`) introduces [biolink:has_fisher_exact_test_p_value_with](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/fisher_exact_test.py#L423)
`compute_jaccard` introduces [biolink:has_jaccard_index_with](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/compute_jaccard.py#L81)
`overlay_clinical_info.py` introduces [biolink:has_real_world_evidence_of_association_with](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/overlay_clinical_info.py#L299)

I don't know if these predicates are problems or not, please let me know if we need to change them. Thanks!

**Comment by saramsey** [comment] 2023-02-21 20:52
> Sorry for the delay @saramsey and @amykglen. The xDTD model does not query KG2 at run-time. This is likely a problem due to training the xDTD model on a previous version of KG2 and predicates have since changed. @chunyuma said he can look into how to address that. Any idea what the priority level is for this?

Thanks, David. Are you positing that DTD, having been built against KG2.7.6c, is putting KG2.7.6c edges into the query-specific KG?  What we are seeing is edges with KG2.7.6c predicates, like `biolink:increases_activity_of`, showing up in results. My suspicion all along has been that this is likely happening because, somehow, the ARAX on `arax.ci.transltr.io` is querying a RTX-KG2 KP instance that is backed by KG2.7.6c. But @edeutsch is wondering if these edges are coming from DTD.

**Comment by chunyuma** [comment] 2023-02-21 20:58
Right, @saramsey. The `xDTD` is trained based on KG2.7.6c which is basically the KG2 paper used. So the edges it returned are based on KG2.7.6c. We can filter out some "bad" edges (e.g. `biolink:increases_activity_of`) within the `ARAX_infer` module if you want.

**Comment by edeutsch** [comment] 2023-02-21 21:10
> Right, @saramsey. The `xDTD` is trained based on KG2.7.3c which is basically the KG2 paper used. So the edges it returned are based on KG2.7.3c. We can filter out some "bad" edges (e.g. `biolink:increases_activity_of`) within the `ARAX_infer` module if you want.

or perhaps transform them on the fly to the correct Biolink 3.1 style?

**Comment by chunyuma** [comment] 2023-02-21 21:18
@edeutsch, it is always painful and involves lots of work in re-training the whole `xDTD` model to keep pace with the KG2 update. The whole process might need more than 2-3 weeks. I think the easiest way is to filter out those "bad" edges within the `ARAX_infer`.

**Comment by dkoslicki** [comment] 2023-02-21 21:26
@chunyuma Eric wasn't suggesting re-training the model, rather just have rules in place that convert predicates to their new wording _after_ xDTD has returned its results

**Comment by dkoslicki** [comment] 2023-02-21 21:27
So don't filter out the edges, rather update the predicate

**Comment by chunyuma** [comment] 2023-02-21 21:32
> @chunyuma Eric wasn't suggesting re-training the model, rather just have rules in place that convert predicates to their new wording after xDTD has returned its results

@edeutsch @dkoslicki, is there a predicate mapping that I can use to covert predicates to their new wording after xDTD has returned its results?

**Comment by chunyuma** [comment] 2023-02-21 21:34
For example, what predicate I should covert `biolink:increases_activity_of` to?

**Comment by edeutsch** [comment] 2023-02-21 22:06
The RTX-KG2 team @saramsey @acevedol have been working on this very problem, so they would know and maybe have a nice mapping

**Comment by saramsey** [comment] 2023-02-22 00:11
> @saramsey, the `xDTD` is trained based on KG2.7.3c which is basically the KG2 paper used. So the edges it returned are based on KG2.7.3c. We can filter out some "bad" edges (e.g. `biolink:increases_activity_of`) within the `ARAX_infer` module if you want.

Thank you!  Yes, I think a quick-and-dirty predicate-mapping patch might be the solution here, while we wait for the new build of the DTD database on Beast. @acevedol can you help provide a mapping between KG2.7.3 predicates andKG2.8.0 predicates, for _just the types of predicates that have been flagged at issue here_, which I think includes `biolink:increases_activity_of` and (I presume, by symmetry), `biolink:decreases_activity_of`?

**Comment by saramsey** [comment] 2023-02-22 00:11
Thank you @edeutsch for your insightful diagnosing of this issue.

**Comment by edeutsch** [comment] 2023-02-22 00:25
just musing aloud, I wonder this this translation layer might be used a bit more generically even for KG2.8.0. As work to remap other old predicates to their new qualified form continues, I wonder if some general translation table could be used to update other predicates on the fly in advance of updates to KG2.8.0. i.e. as soon as you determine that A should be remapped to B, as you start work on transforming the KG load process, you could also update the on-the-fly translation layer, so that the new form is available immediately, not just at the next KG2 build.

Of course, if it were that easy, you probably would have just done that to all of KG2 already..

**Comment by saramsey** [comment] 2023-02-22 19:43
@edeutsch currently, DTD doesn't query the RTX-KG2 KP and it doesn't query the PloverDB. So, I think we have three choices:

1. ARAX-infer performs the translation on-the-fly, based on rules that are maintained in an artifact/file that resides in (and is maintained in) the ARAX code-base and thus available to be read when ARAX starts up
2. ARAX-infer performs the translation on-the-fly, based on rules that are obtained dynamically from the RTX-KG2 API
3. ARAX-infer performs the translation on-the-fly, based on rules that are obtained dynamically from the PloverDB API

Are those three basically the options?

**Comment by edeutsch** [comment] 2023-02-22 19:58
I am thinking that for options 2 and 3, a whole API would need to be designed and it doesn't seem worth it.
Option 1 seems very reasonable and easier than 2 or 3.
In theory this mechanism would be eventually obsoleted when all the various ARAX/KG2 components all caught up. But of course, by then Biolink 3.5 will add a new twist for the mechanism to consider.

> Ideally, Biolink-compliance should be expected at the boundaries between modules within ARAX. Right?

I don't know. They are, in fact, all Biolink compliant. They're just compliant with different versions of Biolink, which is a fast moving target. Since it seems very difficult for all of our components to move in lockstep, it seems reasonable to have some mechanism for temporary translation.

Putting it in ARAX-infer seems reasonable if only ARAX-infer is going to be behind.

Putting it more in ARAX proper may also make sense if other things might be a little behind. Consider the possibility that next week Biolink 3.2 is released. KG2 is behind. MolePro is even further behind. But there are relatively few changes in Biolink 3.2 (perhaps just a few more predicates turned into qualifiers). The ARAX translation layer can take results from BL 3.1 KG2 and BL 3.0 Molepro and tranform it all into a tidy BL 3.2 world just applying a few relatively simple-to-encode rules. this means we don't fret as as much when KG2 seems behind and we can always claim to support the latest release? Maybe Biolink 3.2 renames ChemicalEntity to ChemicalThingy. If this is a 5-minute fix in the translation layer, then we don't need to fret about KG2 being behind and creating a new release quite so urgently. I'm probably making it seem easier than it actually would be...

**Comment by saramsey** [comment] 2023-02-22 20:47
Thank you @edeutsch. Yes, to me, that's a very convincing argument for a dynamic translation layer. You also raise an interesting argument (which I hadn't considered) for centralizing the translation layer in ARAX. For communication between an ARA and a KP, I think it has always been expected that both must be on the same version of TRAPI. I guess there is not a one-to-one correspondence between TRAPI releases and Biolink releases, such that we could find a situation where an ARA and a KP both claim to be speaking "TRAPI version X", but the KP is using Biolink version Y and the ARA is expecting/speaking Biolink version Z. And that is not prohibited by Translator Reasoners Standard API specification, correct?

**Comment by edeutsch** [comment] 2023-02-22 21:21
Indeed there is not a one-to-one correspondence between TRAPI releases and Biolink releases. Some big changes in Biolink require a change to TRAPI (e.g. qualifiers) but most of the changes in Biolink that we've been wrestling with over the past few years (adding and changing categories and predicates) have been largely TRAPI neutral.

While 95% of all agents are solidly on TRAPI 1.3 today, I surmise that if anyone actually tried to determine this, there are probably 5 or more different Biolink versions reflected in KPs available today. And even if you tested claims of Biolink version support from various agents at face value, I bet you would find the truth is quite a bit more varied.

Even perfect translation is not necessary, I contend there's a lot of low-hanging fruit for easy 90-10 translation.

**Comment by saramsey** [comment] 2023-03-08 20:04
Eric, this issue was discussed at today's AHM. I believe we decided to try to rebuild DTD against KG2.8.0c and to try to automate some of the data processing steps that currently make rebuilding DTD labor-intensive. As for a translation layer, are you thinking in terms of a web service for that?

**Comment by edeutsch** [comment] 2023-03-08 20:32
Great! Sorry I could not make it today. I really would have wanted to be there, it sounds like a missed a lot, but the conference here also was crucial for me.

I was thinking of an internal Python class for the translation, not a web service. But perhaps a web service could make sense. It might help others. But would be less efficient for us if that is the only interface. I would suggest internal class/method that can be called near the end of processing.

**Comment by saramsey** [comment] 2023-03-29 23:06
As the remedy has been determined to be a rebuild of DTD, I am taking myself off the assignee list for this issue.

**Comment by chunyuma** [comment] 2023-04-26 18:34
I will wait for KG2.8.2c ready and then re-train the creative model to solve this issue.

**Comment by edeutsch** [comment] 2023-06-13 05:22
This issue is still generating Translator-wide issues for us: https://github.com/NCATSTranslator/Feedback/issues/330#issuecomment-1588344312

Apparently any edge that does not have a valid Biolink predicate does not get displayed in the UI.

@chunyuma What's the prognosis for getting this fixed? Do we have a date?

**Comment by edeutsch** [comment] 2023-06-27 19:17
@chunyuma What's the prognosis for getting this fixed? Do we have a date?

We have been given a deadline of July 7 to get this fixed and deployed

**Comment by edeutsch** [comment] 2023-06-29 18:10
Then I think we need to put serious effort into "query time patching of incorrect predicates". I think @saramsey is looking into this?

**Comment by chunyuma** [comment] 2023-07-01 19:48
Hi @edeutsch, I have a new update for the new model rebuild. Now, I can switch to CPU training and use much more processes (i.e., 50 instead of 16 cores). But I still need around 200 hours. So hopefully, we can make it done before July 7. Sorry for the late deployment.

**Comment by chunyuma** [comment] 2023-07-08 02:45
Hi @edeutsch, the new model has been rebuilt. And its new database with 80% completeness has been uploaded to the server. This issue should be fixed now.

**Comment by edeutsch** [comment] 2023-07-08 17:50
Hi @chunyuma I have deployed the latest `master` to all the usual places. Should this have deployed your fix? Did the new database get distributed to all the right places? Do you suppose that it automatically gets copied to ITRB CI. I am hazy on how this new database gets deployed.

**Comment by edeutsch** [comment] 2023-07-08 17:59
@chunyuma I just ran this query and I get 0 results and lots of warnings. Is this because this disease is in the missing 20%? Or some other problem?
```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0020066"
      ],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```

**Comment by chunyuma** [comment] 2023-07-12 20:41
@edeutsch, there are some diseases missing in the new xDTD database. I will try to recover them.

**Comment by saramsey** [comment] 2023-08-16 05:07
Hi @chunyuma what's the status of this issue?

**Comment by chunyuma** [comment] 2023-08-16 15:21
Hi @saramsey, since the `ExplainableDTD_v1.0_KG2.8.3_refreshedTo_KG2.8.4.db`, the refreshed xDTD model for KG2.8.4 based on KG2.8.3 (using biolink version 3.1.2), has been integrated into the `KG2.8.4` branch. When we decide to deploy the KG2.8.4c recently and merge the `KG2.8.4` branch to `master`, this issue can be resolved.

**Comment by saramsey** [comment] 2023-08-22 04:32
OK, since we have merged KG2.8.4 to master and since we have deployed KG2.8.4c, I think we should close this out.

**Comment by saramsey** [comment] 2023-08-22 04:35
I ran this query
```
{
  "edges": {
    "N1": {
      "attribute_constraints": [],
      "object": "sn",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "qualifier_constraints": [],
      "subject": "on"
    },
    "creative_DTD_qedge_0": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_0",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "sn"
    },
    "creative_DTD_qedge_1": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "creative_DTD_qnode_1",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_0"
    },
    "creative_DTD_qedge_2": {
      "attribute_constraints": [],
      "exclude": false,
      "object": "on",
      "option_group_id": "creative_DTD_option_group_0",
      "qualifier_constraints": [],
      "subject": "creative_DTD_qnode_1"
    },
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "creative_DTD_qnode_0": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    },
    "creative_DTD_qnode_1": {
      "constraints": [],
      "is_set": true,
      "option_group_id": "creative_DTD_option_group_0"
    },
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0007972"
      ],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:NamedThing"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```
on `arax.test.transltr.io` tonight, and I got not no results. Is that good?

**Comment by saramsey** [comment] 2023-08-22 04:36
Hoping that @chunyuma can help me understand how to interpret that result. Does that mean this issue is fixed?

**Comment by chunyuma** [comment] 2024-06-17 23:30
Sorry for the late response. I think this issue is fixed because it has been updated to KG2.8.4.

**Closed by chunyuma** 2024-06-17 23:30 UTC
Labels: high priority, verify in next deployment
