### ISSUE TITLE
Move ARAX to TRAPI 1.1

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1412] opened 2021-04-24 22:05 UTC
realized we don't seem to have an issue for this yet - creating one so we have a place to document related work

some links from the mini-hackathon we had about this a little ways back:
https://github.com/NCATSTranslator/ReasonerAPI/tree/v1.1.x
https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.1.x/TranslatorReasonerAPI.yaml 
https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.1.x/ChangeLog.md 

(although it seems these links are now broken?)

**Comment by edeutsch** [comment] 2021-04-25 03:27
TRAPI 1.1 schemas have been merged into master in the ReasonerAPI repo, so URLs are now:
https://github.com/NCATSTranslator/ReasonerAPI/
https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml
https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ChangeLog.md

**Comment by edeutsch** [comment] 2021-04-25 03:30
TRAPI 1.1 stuff is being set up in the NewFmt branch.
It is progressing nicely, but there is still more work to be done before I'll welcome everyone into the pool.
I'll let y'all know when it's safe to get in.

**Comment by edeutsch** [comment] 2021-04-25 06:45
okay everyone, the pool is open, and let me tell you, changing half your `id` to `ids` (ideally the right half) is super fun!
The branch is `NewFmt`

The changes that need to be made are mostly just:
QNode.id pluralized to ids and changed from CURIE or array of CURIEs to just array of CURIEs with array length > 0
QNode.category pluralized to categories and changed from BiolinkEntity or array of BiolinkEntitys to just array of BiolinkEntitys with array length > 0
QEdge.predicate pluralized to predicates and changed from BiolinkPredicate or array of BiolinkPredicates to just array of BiolinkPredicates with array length > 0
- One amusing gotcha is that list of n>=1 seems to be enforced by the class setter, so you can't do qnode.ids = [] and append later

The following are done:
/ ARAX_database_manager.py
/ query_graph_info.py
/ ARAX_query.py
/ ARAX_messenger.py
/ ARAX_query_graph_interpreter.py
/ ARAX_response.py

and it was a gas!

The following need to be done:
ARAX_decorator.py
ARAX_expander.py
ARAX_filter.py
ARAX_filter_kg.py
ARAX_filter_results.py
ARAX_overlay.py
ARAX_ranker.py
ARAX_resultify.py
and then also any dependent files in subdirs
It would be great if you can take the ones you know best and join in the fun.
It would be great if we can get this done fairly quickly. the endpoints are configured and up, so as soon as we can get all tests passing, it should be pretty quick to getting things up and running.

Note that this will be parallel to our main endpoints for a while. The GUIs are:
https://arax.ncats.io/NewFmt/
https://arax.ncats.io/kg2NewFmt/

and the corresponding API endpoints are:
https://arax.ncats.io/api/arax/v1.1/ui/
https://arax.ncats.io/api/rtxkg2/v1.1/ui/
(note the v1.1 instead of v1.0)

The GUI will also need to be updated to speak TRAPI 1.1. It is not yet.
Just to be clear, don't expect these locations to work properly yet. Much code needs to be fixed and deployed before they will work properly. But they exist.

Thanks!

**Comment by dkoslicki** [comment] 2021-04-25 19:51
@finnagin can you take care of the `filter_*` and you and @chunyuma can work on `overlay`?

**Comment by edeutsch** [comment] 2021-04-26 06:59
Thanks for all the checkins so far into NewFmt! I just rolled out the current state to v1.1 areas (both ARAX and KG2) in case this might be useful. Some tests are still failing. But some are passing too!

**Comment by amykglen** [comment] 2021-04-26 17:00
ok, I think `expand` is in a working state in `NewFmt` now (with the exception of @chunyuma's DTD, CHP, and COHD submodules), and `resultify` as well. 

one thing I'm unsure about (maybe to discuss at a minihackathon) is the new/changed `Attribute` properties? did my best to fill these out in at least a minimal way, but not completely sure which data should go in which property..

**Comment by edeutsch** [comment] 2021-04-26 17:22
Thank you @amykglen this is great.

the Attributes issue is an important one. I broke it out into a separate issue #1414. Let's have that discussion there.

**Comment by chunyuma** [comment] 2021-04-26 17:52
ok, I think all `QNode.category`, 'QNode.id', `QEdge.predicate` and `attribute.name`, `attribute.url`, `attribute.type` of `ARAX_overly.py`, `fisher_exact_test.py`, `overlay_clinical_info.py`, `predict_drug_treats_disease.py`, `test_ARAX_overlay.py`, `test_ARAX_workflows.py` have been moved to TRAPI 1.1.

**Comment by edeutsch** [comment] 2021-04-26 18:29
super, thanks, I just pulled the latest `NewFmt` to the v1.1 deployments and the tests are coming out better, but still some issue to fix. I suspect that filter is the main subsystem to be updated now. @finnagin if you can go through and update all the filter stuff, then maybe that'll fix the outstanding test fails, and it'll be minor mop up after that?

**Comment by finnagin** [comment] 2021-04-26 18:30
Sure! Working on that now...

**Comment by finnagin** [comment] 2021-04-26 19:37
All filter tests are passing now. Working on getting overlay tests to pass...

**Comment by finnagin** [comment] 2021-04-26 19:49
Overlay fast tests are passing now. Checking slow tests...

**Comment by edeutsch** [comment] 2021-04-26 20:30
I'm still seeing these errors. Are you not?
test_ARAX_expand.py::test_cohd_expand_chi_square INFO: Disconnecting from database FAILED                                                                                            
test_ARAX_expand.py::test_dtd_expand_1 FAILED                                                                                                      [ 16%]
test_ARAX_expand.py::test_chp_expand_1 FAILED                                                                                                      [ 18%]
test_ARAX_expand.py::test_chp_expand_2 FAILED                       
test_ARAX_workflows.py::test_exclude FAILED 

Is this a problem with my setup?

**Comment by chunyuma** [comment] 2021-04-26 20:31
@edeutsch，I'm working on these tests now.

**Comment by finnagin** [comment] 2021-04-26 20:52
@edeutsch I was seeing those errors but those are in expand I was talking about the fast **Overlay** tests.

**Comment by chunyuma** [comment] 2021-04-26 21:53
ok, now all `test_cohd_expand`, `test_dtd_expand` and `test_chp_expand` test pass.

**Comment by finnagin** [comment] 2021-04-26 22:51
Awesome! Thanks @chunyuma ! Looks like all the fast tests [are passing now](https://travis-ci.com/github/RTXteam/RTX/builds/224210484) but we still have a few slow tests failing. Looks like several slow overlay COHD tests are failing so far. Still running to see all that fail...

**Comment by finnagin** [comment] 2021-04-26 22:57
Specifically these ones so far:
```
test_ARAX_overlay.py::test_paired_concept_frequency_virtual FAILED       [ 50%]
test_ARAX_overlay.py::test_paired_concept_frequency_attribute FAILED     [ 51%]
test_ARAX_overlay.py::test_observed_expected_ratio_virtual FAILED        [ 51%]
test_ARAX_overlay.py::test_observed_expected_ratio_attribute FAILED      [ 52%]
test_ARAX_overlay.py::test_chi_square_virtual FAILED                     [ 53%]
test_ARAX_overlay.py::test_chi_square_attribute FAILED                   [ 53%]
test_ARAX_overlay.py::test_issue_840 FAILED                              [ 57%]
test_ARAX_overlay.py::test_overlay_clinical_info_no_ids FAILED    
```

**Comment by edeutsch** [comment] 2021-04-26 23:34
outstanding, many thanks, everyone! confirmed all nonslow nonexternal tests passing!

@amykglen is the NewFmt ARAX hitting the KG2 v1.1 endpoint too, presumably?

**Comment by amykglen** [comment] 2021-04-26 23:55
no, not yet. but if the code in NewFmt were rolled out to https://arax.ncats.io/api/rtxkg2/v1.1, then I could make ARAX start using that endpoint in `NewFmt` (I've used my `force_local` mechanism to test out the KG2 API-specific code, so think it should be working fine..).

**Comment by amykglen** [comment] 2021-04-27 00:06
we're still using other KPs' TRAPI 1.0 endpoints as well (`expand` converts their answers from 1.0 -> 1.1), since not all KPs will have finished standing up a TRAPI 1.1 endpoint yet. figuring I'll wait until the deadline has passed and then switch to using their 1.1 endpoints.

**Comment by edeutsch** [comment] 2021-04-27 00:13
you're right that other KPs have not switched to 1.1
The latest code from NewFmt is rolled out to the kg2 1.1 endpoint, so you could test to see if that works.

**Comment by chunyuma** [comment] 2021-04-27 00:31
> Specifically these ones so far:
> 
> ```
> test_ARAX_overlay.py::test_paired_concept_frequency_virtual FAILED       [ 50%]
> test_ARAX_overlay.py::test_paired_concept_frequency_attribute FAILED     [ 51%]
> test_ARAX_overlay.py::test_observed_expected_ratio_virtual FAILED        [ 51%]
> test_ARAX_overlay.py::test_observed_expected_ratio_attribute FAILED      [ 52%]
> test_ARAX_overlay.py::test_chi_square_virtual FAILED                     [ 53%]
> test_ARAX_overlay.py::test_chi_square_attribute FAILED                   [ 53%]
> test_ARAX_overlay.py::test_issue_840 FAILED                              [ 57%]
> test_ARAX_overlay.py::test_overlay_clinical_info_no_ids FAILED    
> ```

These failing tests should pass now!

**Comment by amykglen** [comment] 2021-04-27 00:51
> The latest code from NewFmt is rolled out to the kg2 1.1 endpoint, so you could test to see if that works.

awesome - ok, one issue (unearthed by all of today's work): resultify is complaining about a qnode that has a single curie but has `is_set=True`. the qnode starts out with `is_set=None/False`, but add_qnode() does this:
```
2021-04-26T17:44:12.384100 INFO: [] Adding a QueryNode to Message with input parameters {'key': 'n00', 'ids': ['MONDO:0015766'], 'name': None, 'categories': None, 'is_set': None, 'option_group_id': None}
2021-04-26T17:44:12.384370 WARNING: [] Specified ids '['MONDO:0015766']' is a list, but is_set was not set to true. It must be true in this context, so automatically setting to true. Avoid this warning by explictly setting to true.
```
should `add_qnode()` be adjusted so that `is_set=True` is forced only if `qnode.ids` has length **greater than one**?

**Comment by finnagin** [comment] 2021-04-27 03:06
All the slow tests pass now!

**Comment by edeutsch** [comment] 2021-04-27 03:11
> should add_qnode() be adjusted so that is_set=True is forced only if ids is a list that has length greater than one?

yes, you're right! I have just checked in a fix I think.

**Comment by edeutsch** [comment] 2021-04-27 03:13
I have just re-rolled out `NewFmt` to the two v1.1 deployments. @isbluis is working on the GUI so hopefully soon we'll be able to test with the GUI.

Thanks everyone!

**Comment by amykglen** [comment] 2021-04-27 04:33
awesome! I just tested out having Expand use the v1.1 KG2 endpoint, and all tests (including slow) passed, so I just pushed that to `NewFmt`.

**Comment by edeutsch** [comment] 2021-04-27 04:39
excellent! I just rolled out the latest `NewFmt` to both v1.1 endpoints.

**Comment by amykglen** [comment] 2021-04-28 21:57
ok, I created the 'meta knowledge graph' - it's on arax.ncats.io in the KG2.5.2 directory, called `kg2c_meta_kg.json`.  it's about 6 MB, with 56 meta nodes and 53,161 meta edges. let me know if there seem to be any issues with the format! (I think I got all the required pieces..)

**Comment by edeutsch** [comment] 2021-04-28 23:58
outstanding, thanks! Looks great and deployed!

Instead of using a browser, y'all may want to test with:
```
curl https://arax.ncats.io/api/rtxkg2/v1.1/meta_knowledge_graph > zz1.json
```

since it's a tad big.

**Comment by edeutsch** [comment] 2021-04-29 07:23
TRAPI 1.1 supporting GUI and back-end is deployed to NewFmt (except for Build-A-Graph part)

https://arax.ncats.io/NewFmt/

Please test and report.

**Comment by amykglen** [comment] 2021-05-06 22:05
when I go to https://arax.ncats.io/kg2NewFmt/, go to the JSON tab, click 'Example', and try to run that query, it gives an error:
```
An error was encountered while contacting the server (SyntaxError: Unexpected token < in JSON at position 0)
```
should that be working at this point?

**Comment by edeutsch** [comment] 2021-05-06 23:07
Yes, it should certainly be working. I repro'ed and have now fixed. Please try again. you might need to CTRL+REFRESH to make sure you have the latest JavaScript. I suspect this was a casualty of the ingest of `master`.

**Comment by amykglen** [comment] 2021-05-07 00:38
nice, looks good now!

**Comment by edeutsch** [comment] 2021-06-02 22:14
call it done!

**Closed by edeutsch** 2021-06-02 22:14 UTC
