### ISSUE TITLE
Dropping of KG1 impacts repurposing query

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1428] opened 2021-05-03 20:16 UTC
For the results here: https://arax.ncats.io/?r=8445, the query:
```
add_qnode(name=DOID:14330, key=n00)
add_qnode(category=biolink:Protein, is_set=true, key=n01)
add_qnode(category=biolink:ChemicalSubstance, key=n02)
add_qedge(subject=n00, object=n01, key=e00)
add_qedge(subject=n01, object=n02, key=e01, predicate=biolink:physically_interacts_with)
expand(edge_key=[e00,e01], kp=ARAX/KG1)  #<---KG1
overlay(action=compute_jaccard, start_node_key=n00, intermediate_node_key=n01, end_node_key=n02, virtual_relation_label=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_key=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, subject_qnode_key=n02, object_qnode_key=n00, virtual_relation_label=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```
returns 6 high quality results. However, dropping the KG1 kp and letting expand figure it out, results in https://arax.ncats.io/?r=8452 which has 3 very low quality results (water, antioxidant, and antagonists & inhibitors suggested as "drugs" that can treat Parkinson's).
```
add_qnode(name=DOID:14330, key=n00)
add_qnode(category=biolink:Protein, is_set=true, key=n01)
add_qnode(category=biolink:ChemicalSubstance, key=n02)
add_qedge(subject=n00, object=n01, key=e00)
add_qedge(subject=n01, object=n02, key=e01, predicate=biolink:physically_interacts_with)
expand(edge_key=[e00,e01])   #<---KG2 invoked
overlay(action=compute_jaccard, start_node_key=n00, intermediate_node_key=n01, end_node_key=n02, virtual_relation_label=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_key=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, subject_qnode_key=n02, object_qnode_key=n00, virtual_relation_label=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```
I don't really know where in the system the good results are being dropped (since, for example RASAGILINE lives in both KG1 and KG2, and the DTD model has a `treats` of it for Parkinson's above 0.8). So this might be a KG2 issue, a DTD issue, or even an expand issue!

**Comment by dkoslicki** [comment] 2021-05-03 20:18
Pinging KG2 team to start the investigation, but feel free to re-assign others depending on what is found out about this. Note: this is one of our workflow tests.

**Comment by amykglen** [comment] 2021-05-04 00:34
hmm - so I confirmed that you can indeed produce those same 6 chemical substances seen in the KG1 results using KG2: https://arax.ncats.io/?r=8489

so it must be somewhere in the overlaying/filtering that these are being dropped?

(those 3 results in https://arax.ncats.io/?r=8452 are only 3 out of about 8,000 chemical substances `expand` finds when it uses KG2, according to the log messages).

**Comment by amykglen** [comment] 2021-05-04 00:45
lowering the filter threshold for jaccard index begins to include some more interesting results: https://arax.ncats.io/?r=8496

my rather superficial guess is that this is a problem of 'hub' nodes watering down the rankings for what are actually good results?

**Comment by dkoslicki** [comment] 2021-05-04 02:57
(Looping in @finnagin for the overlay/filter), curious that hub nodes and the ranking shouldn't result in the truncation of results, given that neither exceeds the 15 max results asked for.

Maybe filter really is "to blame" given the understandable change in the denominator of Jaccard going KG1 to KG2. @finnagin , mind looking into it? It's kind of silly that `water` is the top result for KG2 as a repurposing target.

**Comment by saramsey** [comment] 2021-05-10 04:16
Thank you @amykglen for investigating. I agree that "water", "antioxidant", and "antagonists & inhibitors" are not what we would want to see as the top three results for this repositioning workflow.

**Comment by saramsey** [comment] 2021-05-10 04:16
Feel free to ping me if it turns out this is looking like a KG2 issue.

**Comment by dkoslicki** [comment] 2021-05-20 22:05
@finnagin Given the impending complete removal of KG1, can you please look into this one? It would be rather harmful to have “water” etc. come up in a drug repurposing query during the December demo.

**Comment by finnagin** [comment] 2021-05-21 10:52
I'm pretty sure that Amy is right in that this is a case of jaccard watering (lol!) down non super-connected nodes. Since the jaccard index value is (# of connected intermediate nodes)/(total # of intermediate nodes). 

Thus, if we add just 1 node with a huge number of connections it will not only be ranked highly but it will also cause the numerator for all other nodes to be diluted with the addition of a bunch of other valid intermediate nodes.

If you relax the jaccard  index filter cutoff then this adds in other results some of which are ranked higher due to their higher predict_drug_treats_disease score but then they are still listed lower in this query since we end the query by sorting the results by jaccard index only:
```
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```

**Comment by finnagin** [comment] 2022-02-02 21:14
Closing since the demo is now over and the cause for the missing curies was found.

**Closed by finnagin** 2022-02-02 21:14 UTC
