### ISSUE TITLE
Test build always fails?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2026] opened 2023-05-10 00:43 UTC
It seems to me that the test build always fails whenever I make a checkin. I don't know why. Following up on the links doesn't seem illuminating. I mostly just delete the messages, so they may not be serving a useful function. We might want to re-evaluate.

**Comment by amykglen** [comment] 2023-05-26 17:23
I think we're back to a functioning state... we've had 'Test Build passing' status for a few days now. changing the KG2 URL cicd.rtx.ai uses from v1.3 --> v1.4, plus all of the work done as part of the KG2.8.0.1c rollout seems to have done the trick.

**Comment by saramsey** [comment] 2023-08-02 21:45
Now that I have resolved [RTXteam/RTX issue](https://github.com/RTXteam/RTX/issues/2080) 2080 (increase size of root volume on `cicd.rtx.ai`), I am going to try to see if the pytest "Test Build" GitHub action is working. Logging my findings here.

**Comment by saramsey** [comment] 2023-08-02 21:47
Following the instructions in the Wiki page [CI system (via GitHub actions)](https://github.com/RTXteam/RTX/wiki/CI-system-(via-GitHub-actions)), it looks like the Test Build "self-hosted runner" process is running on `cicd.rtx.ai`:
```
ubuntu@ip-172-31-10-160:~/actions-runner$ sudo ./svc.sh status

/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service
● actions.runner.RTXteam-RTX.ARAXRunner.service - GitHub Actions Runner (RTXteam-RTX.ARAXRunner)
     Loaded: loaded (/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-01-12 01:00:32 UTC; 6 months 20 days ago
   Main PID: 462 (runsvc.sh)
      Tasks: 49 (limit: 9221)
     Memory: 341.0M
     CGroup: /system.slice/actions.runner.RTXteam-RTX.ARAXRunner.service
             ├─    462 /bin/bash /home/ubuntu/actions-runner/runsvc.sh
             ├─    504 ./externals/node12/bin/node ./bin/RunnerService.js
             ├─1514728 /home/ubuntu/actions-runner/bin/Runner.Listener run --startuptype service
             ├─1597265 /home/ubuntu/actions-runner/bin.2.307.1/Runner.Worker spawnclient 112 116
             ├─1597471 /usr/bin/bash -e /home/ubuntu/actions-runner/_work/_temp/c52c2019-b17c-4249-aac7-525b4cef1…
             ├─1597472 sudo docker build --no-cache=true --rm -t rtx:test DockerBuild/ -f DockerBuild/Merged-Dock…
             └─1597473 docker build --no-cache=true --rm -t rtx:test DockerBuild/ -f DockerBuild/Merged-Dockerfile

Aug 02 21:41:42 ip-172-31-10-160 sudo[1597449]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597449]: pam_unix(sudo:session): session closed for user root
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597457]:   ubuntu : TTY=unknown ; PWD=/home/ubuntu/actions-runner/_w…ges -q
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597457]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597457]: pam_unix(sudo:session): session closed for user root
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597464]:   ubuntu : TTY=unknown ; PWD=/home/ubuntu/actions-runner/_w…85b768
Aug 02 21:41:43 ip-172-31-10-160 sudo[1597464]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 02 21:41:47 ip-172-31-10-160 sudo[1597464]: pam_unix(sudo:session): session closed for user root
Aug 02 21:41:47 ip-172-31-10-160 sudo[1597472]:   ubuntu : TTY=unknown ; PWD=/home/ubuntu/actions-runner/_w…erfile
Aug 02 21:41:47 ip-172-31-10-160 sudo[1597472]: pam_unix(sudo:session): session opened for user root by (uid=0)
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by saramsey** [comment] 2023-08-02 21:48
It's been running for six months, so I think I will restart it.

**Comment by saramsey** [comment] 2023-08-02 21:49
Confirmed, it is not running now:
```
ubuntu@ip-172-31-10-160:~/actions-runner$ sudo ./svc.sh status

/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service
● actions.runner.RTXteam-RTX.ARAXRunner.service - GitHub Actions Runner (RTXteam-RTX.ARAXRunner)
     Loaded: loaded (/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2023-08-02 21:48:50 UTC; 16s ago
    Process: 462 ExecStart=/home/ubuntu/actions-runner/runsvc.sh (code=exited, status=0/SUCCESS)
   Main PID: 462 (code=exited, status=0/SUCCESS)
      Tasks: 7 (limit: 9221)
     Memory: 186.8M
     CGroup: /system.slice/actions.runner.RTXteam-RTX.ARAXRunner.service
             ├─1612522 sudo docker exec rtx_test bash -c cd /mnt/data/orangeboard/production/RTX/code/ARAX/test &…
             └─1612523 docker exec rtx_test bash -c cd /mnt/data/orangeboard/production/RTX/code/ARAX/test && pyt…

Aug 02 21:48:36 ip-172-31-10-160 systemd[1]: Stopping GitHub Actions Runner (RTXteam-RTX.ARAXRunner)...
Aug 02 21:48:36 ip-172-31-10-160 runsvc.sh[504]: Shutting down runner listener
Aug 02 21:48:36 ip-172-31-10-160 runsvc.sh[504]: Sending SIGINT to runner listener to stop
Aug 02 21:48:36 ip-172-31-10-160 runsvc.sh[504]: Sending SIGKILL to runner listener
Aug 02 21:48:36 ip-172-31-10-160 runsvc.sh[504]: Exiting...
Aug 02 21:48:49 ip-172-31-10-160 runsvc.sh[504]: 2023-08-02 21:48:49Z: Job Analyze (python) completed with …nceled
Aug 02 21:48:50 ip-172-31-10-160 runsvc.sh[504]: Runner listener exited with error code 0
Aug 02 21:48:50 ip-172-31-10-160 runsvc.sh[504]: Runner listener exit with 0 return code, stop the service,…eeded.
Aug 02 21:48:50 ip-172-31-10-160 systemd[1]: actions.runner.RTXteam-RTX.ARAXRunner.service: Succeeded.
Aug 02 21:48:50 ip-172-31-10-160 systemd[1]: Stopped GitHub Actions Runner (RTXteam-RTX.ARAXRunner).
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by saramsey** [comment] 2023-08-02 21:49
Starting the runner back up:
```
ubuntu@ip-172-31-10-160:~/actions-runner$ sudo ./svc.sh start

/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service
● actions.runner.RTXteam-RTX.ARAXRunner.service - GitHub Actions Runner (RTXteam-RTX.ARAXRunner)
     Loaded: loaded (/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-02 21:49:23 UTC; 11ms ago
   Main PID: 1612603 (runsvc.sh)
      Tasks: 2 (limit: 9221)
     Memory: 176.8M
     CGroup: /system.slice/actions.runner.RTXteam-RTX.ARAXRunner.service
             ├─1612603 /bin/bash /home/ubuntu/actions-runner/runsvc.sh
             └─1612606 /bin/bash /home/ubuntu/actions-runner/runsvc.sh

Aug 02 21:49:23 ip-172-31-10-160 systemd[1]: Started GitHub Actions Runner (RTXteam-RTX.ARAXRunner).
Aug 02 21:49:23 ip-172-31-10-160 runsvc.sh[1612603]: .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi…ap/bin
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by saramsey** [comment] 2023-08-02 21:49
Confirmed, it is now running:
```
ubuntu@ip-172-31-10-160:~/actions-runner$ sudo ./svc.sh status

/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service
● actions.runner.RTXteam-RTX.ARAXRunner.service - GitHub Actions Runner (RTXteam-RTX.ARAXRunner)
     Loaded: loaded (/etc/systemd/system/actions.runner.RTXteam-RTX.ARAXRunner.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-02 21:49:23 UTC; 16s ago
   Main PID: 1612603 (runsvc.sh)
      Tasks: 23 (limit: 9221)
     Memory: 250.5M
     CGroup: /system.slice/actions.runner.RTXteam-RTX.ARAXRunner.service
             ├─1612603 /bin/bash /home/ubuntu/actions-runner/runsvc.sh
             ├─1612606 ./externals/node12/bin/node ./bin/RunnerService.js
             └─1612613 /home/ubuntu/actions-runner/bin/Runner.Listener run --startuptype service

Aug 02 21:49:23 ip-172-31-10-160 systemd[1]: Started GitHub Actions Runner (RTXteam-RTX.ARAXRunner).
Aug 02 21:49:23 ip-172-31-10-160 runsvc.sh[1612603]: .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi…ap/bin
Aug 02 21:49:24 ip-172-31-10-160 runsvc.sh[1612606]: Starting Runner listener with startup type: service
Aug 02 21:49:24 ip-172-31-10-160 runsvc.sh[1612606]: Started listener process, pid: 1612613
Aug 02 21:49:24 ip-172-31-10-160 runsvc.sh[1612606]: Started running service
Aug 02 21:49:25 ip-172-31-10-160 runsvc.sh[1612606]: √ Connected to GitHub
Aug 02 21:49:25 ip-172-31-10-160 runsvc.sh[1612606]: Current runner version: '2.307.1'
Aug 02 21:49:25 ip-172-31-10-160 runsvc.sh[1612606]: 2023-08-02 21:49:25Z: Listening for Jobs
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by saramsey** [comment] 2023-08-02 21:51
Now I want to manually run the Test Build workflow. I'm going to try to follow the instructions on the GitHub Docs page [Manually running a workflow](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow).

**Comment by saramsey** [comment] 2023-08-02 21:53
Looks like the "Test Build" GitHub Action doesn't have a `workflow_dispatch` event trigger:

<img width="1276" alt="Screenshot 2023-08-02 at 2 52 17 PM" src="https://github.com/RTXteam/RTX/assets/5562107/b40c7cce-9a8b-4267-ae41-d8314eec6a44">

**Comment by saramsey** [comment] 2023-08-02 21:54
So, for using the `workflow_dispatch` mechanism, the "Test Build" workflow must (per the GitHub Docs documentation linked above) "be in the default branch". Checking...

**Comment by saramsey** [comment] 2023-08-02 21:55
OK, it looks like the `pytest.yaml` that corresponds to this GitHub action is indeed in the `master` branch:
<img width="1256" alt="Screenshot 2023-08-02 at 2 54 34 PM" src="https://github.com/RTXteam/RTX/assets/5562107/5980e453-0bdc-46a1-ace9-625375de4909">

**Comment by saramsey** [comment] 2023-08-02 21:56
Now moving to the [`workflow_dispatch` section of the GitHub docs page "Using workflows"](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)

**Comment by saramsey** [comment] 2023-08-02 22:04
See commit 79084ba:

<img width="1512" alt="Screenshot 2023-08-02 at 3 04 18 PM" src="https://github.com/RTXteam/RTX/assets/5562107/38e54249-1fa7-4db0-b7e3-f9cf8a8c3ced">

**Comment by saramsey** [comment] 2023-08-02 22:06
Due to the previous commit, now there is a "Run workflow" button on the "Test Build" workflow under "Actions":

<img width="1518" alt="Screenshot 2023-08-02 at 3 05 50 PM" src="https://github.com/RTXteam/RTX/assets/5562107/4639f830-d29a-401b-ac18-05bbb1f8ee92">

**Comment by saramsey** [comment] 2023-08-02 22:21
So the tests seem to be working, but it is failing on a specific test:

<img width="794" alt="Screenshot 2023-08-02 at 3 20 51 PM" src="https://github.com/RTXteam/RTX/assets/5562107/a19b229f-544a-48eb-8476-38f858ff6c08">

**Comment by saramsey** [comment] 2023-08-02 22:36
I've managed to reproduce this test, as user `ubuntu`, on `cicd.rtx.ai`, running the following command (with `ubuntu` being in the directory `/home/ubuntu/RTX/code/ARAX/test`):
```
/home/ubuntu/sar-venv/bin/pytest -vs test_ARAX_connect.py::test_connect_acetaminophen_to_ptgs1
```
It produces the following error:
```
=============================================================================== FAILURES ===============================================================================
_________________________________________________________________ test_connect_acetaminophen_to_ptgs1 __________________________________________________________________

    def test_connect_acetaminophen_to_ptgs1():
        query = {"operations": {"actions": [
                "create_message",
                "add_qnode(ids=CHEMBL.COMPOUND:CHEMBL112, key=n00)",
                "add_qnode(ids=UniProtKB:P23219, key=n01)",
                "connect(action=connect_nodes)",
                "resultify(ignore_edge_direction=true, debug=true)",
                "return(message=true, store=false)"
            ]}}
        [response, message] = _do_arax_query(query)
>       assert response.status == 'OK'
E       AssertionError: assert 'ERROR' == 'OK'
E         - OK
E         + ERROR

test_ARAX_connect.py:92: AssertionError
=========================================================================== warnings summary ===========================================================================
../../../../sar-venv/lib/python3.8/site-packages/connexion/decorators/validation.py:16
../../../../sar-venv/lib/python3.8/site-packages/connexion/decorators/validation.py:16
  /home/ubuntu/sar-venv/lib/python3.8/site-packages/connexion/decorators/validation.py:16: DeprecationWarning: Accessing jsonschema.draft4_format_checker is deprecated and will be removed in a future release. Instead, use the FORMAT_CHECKER attribute on the corresponding Validator.
    from jsonschema import Draft4Validator, ValidationError, draft4_format_checker

../../../../sar-venv/lib/python3.8/site-packages/connexion/json_schema.py:16
../../../../sar-venv/lib/python3.8/site-packages/connexion/json_schema.py:16
  /home/ubuntu/sar-venv/lib/python3.8/site-packages/connexion/json_schema.py:16: DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
    from jsonschema import Draft4Validator, RefResolver

../../../../sar-venv/lib/python3.8/site-packages/connexion/json_schema.py:17
  /home/ubuntu/sar-venv/lib/python3.8/site-packages/connexion/json_schema.py:17: DeprecationWarning: jsonschema.exceptions.RefResolutionError is deprecated as of version 4.18.0. If you wish to catch potential reference resolution errors, directly catch referencing.exceptions.Unresolvable.
    from jsonschema.exceptions import RefResolutionError, ValidationError  # noqa

../ARAXQuery/ARAX_query_tracker.py:27
  /home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_query_tracker.py:27: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

../ResponseCache/response_cache.py:49
  /home/ubuntu/RTX/code/ARAX/ARAXQuery/../ResponseCache/response_cache.py:49: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

test_ARAX_connect.py: 21 warnings
  /home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/Expand/trapi_querier.py:240: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
    async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False)) as session:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================= short test summary info ========================================================================
FAILED test_ARAX_connect.py::test_connect_acetaminophen_to_ptgs1 - AssertionError: assert 'ERROR' == 'OK'
=================================================================== 1 failed, 28 warnings in 33.14s ====================================================================
```

**Comment by saramsey** [comment] 2023-08-02 22:38
Looks like there is some issue with NetworkX:
```
  - 2023-08-02T22:37:53.007048 ERROR: [UncaughtARAXiError] An uncaught error occurred: module 'networkx' has no attribute 'to_numpy_matrix': ['Traceback (most recent call last):\n', '  File "/home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 832, in execute_processing_plan\n    ranker.aggregate_scores_dmk(response)\n', '  File "/home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 616, in aggregate_scores_dmk\n    ranks_list = list(map(_quantile_rank_list,\n', '  File "/home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 617, in <lambda>\n    map(lambda scorer_func: _score_result_graphs_by_networkx_graph_scorer(kg_edge_id_to_edge,\n', '  File "/home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 162, in _score_result_graphs_by_networkx_graph_scorer\n    return nx_graph_scorer(result_graphs_nx)\n', '  File "/home/ubuntu/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 135, in _score_networkx_graphs_by_longest_path\n    adj_matrix = nx.to_numpy_matrix(result_graph_nx)\n', "AttributeError: module 'networkx' has no attribute 'to_numpy_matrix'\n"]
```

**Comment by saramsey** [comment] 2023-08-02 22:51
I'm setting up python3.9 on `cicd.rtx.ai`, so we are running the same major and minor version of python that we are running for the ARAX flask service under the `devED` DEVAREA inside the `rtx1` container on `arax.ncats.io`. Installing it on `cicd.rtx..ai` in directory `/home/ubuntu/venv3.9`.

**Comment by saramsey** [comment] 2023-08-02 22:54
Needed to do `sudo apt-get install python3.9-dev`

**Comment by saramsey** [comment] 2023-08-02 22:54
Installing the deadsnakes `python3.9` via `apt-get`.

**Comment by saramsey** [comment] 2023-08-02 23:01
So, `test_ARAX_connect.py::test_connect_acetaminophen_to_ptgs1` is passing in the host OS:
```
(venv3.9) ubuntu@ip-172-31-10-160:~/RTX/code/ARAX/test$ pytest -v test_ARAX_connect.py
========================================== test session starts ===========================================
platform linux -- Python 3.9.17, pytest-7.2.2, pluggy-1.2.0 -- /home/ubuntu/venv3.9/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/ubuntu/RTX/code/ARAX/test
plugins: cov-4.1.0
collected 7 items

test_ARAX_connect.py::test_connect_acetaminophen_to_ptgs1 PASSED                                   [ 14%]
test_ARAX_connect.py::test_connect_nodes_1_hop SKIPPED (need --runslow option to run)              [ 28%]
test_ARAX_connect.py::test_connect_nodes_2_hop SKIPPED (need --runslow option to run)              [ 42%]
test_ARAX_connect.py::test_connect_nodes_subgraph_2_hop SKIPPED (need --runslow option to run)     [ 57%]
test_ARAX_connect.py::test_connect_nodes_3_disconnected_nodes SKIPPED (need --runslow option t...) [ 71%]
test_ARAX_connect.py::test_1881 SKIPPED (need --runslow option to run)                             [ 85%]
test_ARAX_connect.py::test_none_object SKIPPED (need --runslow option to run)                      [100%]

============================================ warnings summary ============================================
```
and inside the

**Comment by saramsey** [comment] 2023-08-02 23:05
Now testing inside the `rtx_test` container:
```
ubuntu@ip-172-31-10-160:~$ sudo docker exec -it rtx_test bash
root@6e8a53a619bc:/# cd /mnt/data/orangeboard/production/RTX/code/ARAX/test && pytest -v --disable-pytest-warnings test_ARAX_connect.py::test_connect_acetaminophen_to_ptgs1
```

**Comment by saramsey** [comment] 2023-08-02 23:06
Running a Test Build manually via GitHub:

<img width="1174" alt="Screenshot 2023-08-02 at 4 06 17 PM" src="https://github.com/RTXteam/RTX/assets/5562107/6b89c04f-7ef0-4aeb-8c60-2912b15fd903">

**Comment by saramsey** [comment] 2023-08-02 23:08
Also seeing this in the Test Build log:

> error_code: UncaughtARAXiError   message: An uncaught error occurred: Timed out waiting for SmartAPI cache creation; perhaps MAX_TOTAL_WAIT_FOR_CACHE_SEC value was too small: 60.0: ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 788, in execute_processing_plan\n    connect.apply(response, action[\'parameters\'])\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_connect.py", line 196, in apply\n    getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])()  # thank you [https://stackoverflow.com/questions/11649848/call-methods-by-string\n](https://stackoverflow.com/questions/11649848/call-methods-by-string/n)', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_connect.py", line 402, in __connect_nodes\n    new_response = expander.apply(new_response, expand_params, mode=mode)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 187, in apply\n    kp_selector = KPSelector(kg2_mode=True, log=log) if mode == "RTXKG2" else KPSelector(log=log)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 27, in __init__\n    self.meta_map, self.kp_urls, self.kps_excluded_by_version, self.kps_excluded_by_maturity = self._load_cached_kp_info()\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 38, in _load_cached_kp_info\n    smart_api_info, meta_map = kp_cacher.load_kp_info_caches(self.log)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_info_cacher.py", line 148, in load_kp_info_caches\n    raise Exception("Timed out waiting for SmartAPI " +\n', 'Exception: Timed out waiting for SmartAPI cache creation; perhaps MAX_TOTAL_WAIT_FOR_CACHE_SEC value was too small: 60.0\n']

**Comment by saramsey** [comment] 2023-08-02 23:09
I wonder if the `cicd.rtx.ai` instance is so slow that we need to increase `MAX_TOTAL_WAIT_FOR CACHE_SEC`?

**Closed** 2023-08-02 23:30 UTC
