### ISSUE TITLE
Hilarious synonymizer problem: MICE the gene

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1410] opened 2021-04-23 19:57 UTC
The gene MICE is being conflated with _Mus musculus_ in the second result of https://arax.ncats.io/?r=7825 . Looking at the [URI](https://www.ncbi.nlm.nih.gov/gene/4280), it does really appear to be a human gene with the symbol MICE

**Comment by saramsey** [comment] 2021-04-23 19:59
This actually violates human gene nomenclature guidelines:

<img width="236" alt="Screen Shot 2021-04-23 at 12 59 13 PM" src="https://user-images.githubusercontent.com/5562107/115923848-bc0a2180-a433-11eb-948a-028c73ec6c36.png">

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7494048/

**Comment by dkoslicki** [comment] 2021-04-23 20:02
Interesting! An issue to report to NCBI or whoever controls gene symbols?

**Comment by saramsey** [comment] 2021-04-23 20:04
I remember there is a gene *T*. That's right, just the letter T. We had lots of fun with that.

**Comment by saramsey** [comment] 2021-04-23 20:18
Complaint submitted to HGNC:

<img width="982" alt="Screen Shot 2021-04-23 at 1 17 37 PM" src="https://user-images.githubusercontent.com/5562107/115925636-4fdced00-a436-11eb-8d74-d14707e377c0.png">

**Comment by edeutsch** [comment] 2021-04-23 20:35
I'm thinking the tidiest thing I can do is change the name of all entities here:
https://arax.ncats.io/?term=Mice
with name "mice" that correspond to plural "mouse" to something like "Mice (pl. mouse)"

or alternatively I could rename the genes to have a name "MICE" to "MICE (gene)" or something.

suggestions?

**Comment by dkoslicki** [comment] 2021-04-23 21:28
@edeutsch Either is fine with me, but perhaps we could go with MICE (gene) since that’s the “problem child”

**Comment by saramsey** [comment] 2021-04-26 15:31
HGNC responded:
> Hi Stephen
> 
> Actually the "MICE" gene symbol was approved in 1994, so it's definitely
> not new.
> 
> Obviously our guidelines have changed quite a bit since the 90s, but of
> course we agree this symbol is far from ideal - however, as it lies in
> the MHC region we have to consult with the HLA nomenclature committee if
> we wanted to change it, and in fact that process is already underway. If
> they have no objections to the symbol changing we were planning to add a
> "P" (MICEP) to make it clear this is a pseudogene.
>
> Thanks for your interest in our work.
>
> Elspeth

**Comment by amykglen** [comment] 2023-05-03 22:56
looks like this conflation no longer appears in the new synonymizer (#2003):

Cluster for HGNC:7094 (NCBIGene:4280) has 3 nodes:

| id            | category   | name      | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:--------------|:-----------|:----------|:---------|:------------|:-----------------|
| HGNC:7094     | Gene       | MICE      | X        | X           |                  |
| NCBIGene:4280 | Gene       | MICE      | X        | X           | X                |
| UMLS:C1417166 | Gene       | MICE gene | X        | X           |                  |

Cluster for PSY:31270 (NCBITaxon:10088) has 4 nodes:

| id              | category      | name   | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:----------------|:--------------|:-------|:---------|:------------|:-----------------|
| MESH:D051379    | OrganismTaxon | Mice   | X        | X           |                  |
| NCBITaxon:10088 | OrganismTaxon | Mus    | X        | X           | X                |
| PSY:31270       | OrganismTaxon | Mice   |          | X           |                  |
| UMLS:C0026809   | OrganismTaxon | Mus    | X        | X           |                  |

the SRI seems to put each of the ENSEMBL:ENSG identifiers for MICE the gene into its own cluster...

**Comment by amykglen** [comment] 2023-05-25 22:54
confirmed fixed on our dev instances:

https://arax.ncats.io/devLM/?term=HGNC:7094
https://arax.ncats.io/devLM/?term=NCBITaxon:10088

**Closed by amykglen** 2023-05-25 22:54 UTC
Labels: node synonymizer, verify in next deployment, conflation
