### ISSUE TITLE
should is_set be TRUE by default for all intermediate nodes?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#737] opened 2020-05-13 04:32 UTC
forking this question from #731 where it is discussed at length

**Comment by saramsey** [comment] 2020-05-13 04:37
Quoting @edeutsch from #731:

> yes, I would define intermediate node as a node with two or more edges.
> 
> Come to think of it, I wonder how my code would react if even end-nodes has two edges because there were multiple edges between all nodes. Anyway, I am mostly concerned about relatively simple cases for now.
> 
> I added some code in the QueryGraphInfo component that forces all intermediate nodes to have is_set=true. I'm not certain this is good long-term behavior and something we should ponder over the next coming months, but I think it will prevent some degree of huge result sets for now.

Hi @edeutsch what if the user specifies is_set=false in the DSL, like this?
```
add_qnode(id=n00)
add_qnode(id=n01, is_set=false)
add_qnode(id=n02)
add_qedge(source=n00, target=n01)
add_qedge(source=n01, target=n02)
does the updated code now override it?
```

**Comment by amykglen** [comment] 2020-05-13 19:06
re: [this comment](https://github.com/RTXteam/RTX/issues/735#issuecomment-628151213) from @edeutsch:
> Thanks, @amykglen. This underscores the is_set=true problem. My added code (#737) forces intermediate nodes to be is_set=true (only for incoming query_graphs, NOT for explicit DSL).

Ah, ok, so technically the `is_set=false` in the DSL @saramsey [posted above](https://github.com/RTXteam/RTX/issues/737#issuecomment-627740503) would **not** be overriden, because it's DSL (and not a query graph).

**Comment by edeutsch** [comment] 2020-05-13 20:23
hmm, I am not certain. I think the way the code path works is that the is_set fixing only happens when the input is an existing query_graph. When the query_graph is built during DSL execution, then this code is not hit (I think. hedging a little)

**Comment by saramsey** [comment] 2020-05-14 21:02
OK it would be good to verify that  hunch. I think it would be potentially confusing to a user if an explicit `is_set` specification in the DSL was silently overridden.

**Comment by edeutsch** [comment] 2020-05-15 03:39
confirmed.

add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=[e00,e01], kp=ARAX/KG1)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)

leads to sets. Removing the is_set=true leads to paths:

add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=protein, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=[e00,e01], kp=ARAX/KG1)
overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_id=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_edge_type=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=probability_drug_treats, direction=descending, max_results=15)

**Comment by finnagin** [comment] 2022-02-01 21:33
@edeutsch @amykglen @saramsey is this still relevant or should we close?

**Comment by edeutsch** [comment] 2022-02-01 21:35
ancient history. we no longer do any is_set adjustments anywhere. closing.

**Closed by edeutsch** 2022-02-01 21:35 UTC
Labels: question
