### ISSUE TITLE
implement a fastNGD

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#654] opened 2020-02-28 18:59 UTC
DMK Note: at the end, I call NGD in `overlay` via:
```
from NormGoogleDistance import NormGoogleDistance as NGD
ngd_value = NGD.get_ngd_for_all([source_curie, target_curie], [source_name, target_name])
```

**Comment by saramsey** [comment] 2020-02-28 19:02
we need this implemented in case NCATS decides to test our DSL NGD functionality for a graph for which we had not previously run the NGD overlay

**Comment by saramsey** [comment] 2020-02-28 19:02
make sure that the pickledb works in python 3.7.3 on ubuntu 18.04

**Comment by saramsey** [comment] 2020-02-28 19:11
@finnagin suggests that (AFTER THE DEMO) we implement natural language search. This is a great idea but would involve full-text indexing of pubmed abstracts.

**Comment by edeutsch** [comment] 2020-02-28 19:34
Note that the Python 3.7.3 on arax.rtx.ai is custom compiled by me and not part of an Ubuntu package. Somehow I was under the impression that there wasn't one available. Although I just did an apt list and it seems that Python 3.7.6 is an available Ubuntu 18 package. Maybe I should upgrade to that.. Perhaps only if there are problems.

**Comment by amykglen** [comment] 2020-02-28 23:28
**Summary of the work done so far toward a fast NGD:**

We have two PickleDBs, both currently living on pubmed.rtx.ai (/home/ubuntu):

`curie-to-mesh.db` (<1MB):
- generated using two scripts (not yet pushed) - one from Finn that gets the mappings using OxO and puts them in a TSV, and one from Steve that loads that TSV into a PickleDB (which I lightly edited to convert 'MeSH:' to 'MESH:')
- key/value pairs look like this: `"UBERON:0001687": ["MESH:D013199"]`

`mesh-to-pmid.db` (~700MB):
- generated using [this script](https://github.com/RTXteam/RTX/blob/pickle-ngd/code/ARAX/ARAXQuery/Overlay/pmid_mapper.py), which runs through all the pubmed 'baseline' xml files and maps each MESH term in `curie-to-mesh.db` to its corresponding PMIDs (took ~1.5 hours to run)
- key/value pairs look like this: `"MESH:D013199": ["PMID:15513522", "PMID:12934439"]`

**Remaining work to do (I think):**

- write some code that takes in a 'whatever' curie and returns all its corresponding PMIDs, using these two PickleDBs
- adjust the compute ngd code Overlay uses so that it first tries to use this PickleDB method to get PMID sets, but defaults to Finn's current ngd implementation if it can't find an answer

I just **created a new sub-branch** we can use for this: `pickle-ngd` (though I'm going to finish up working on the KG2 `Expand` powers before doing more on this).

**Comment by saramsey** [comment] 2020-02-28 23:55
thank you @amykglen

**Comment by saramsey** [comment] 2020-02-29 00:00
> Note that the Python 3.7.3 on arax.rtx.ai is custom compiled by me and not part of an Ubuntu package. Somehow I was under the impression that there wasn't one available. Although I just did an apt list and it seems that Python 3.7.6 is an available Ubuntu 18 package. Maybe I should upgrade to that.. Perhaps only if there are problems.

Before March 17th, I suppose there is an argument to be made that "if it ain't broke, don't fix it".  After the demo, I definitely favor a prebuilt python3 distribution from a reproducibility standpoint.

**Comment by edeutsch** [comment] 2020-02-29 01:11
OK!

**Comment by dkoslicki** [comment] 2020-02-29 03:17
> > Note that the Python 3.7.3 on arax.rtx.ai is custom compiled by me and not part of an Ubuntu package. Somehow I was under the impression that there wasn't one available. Although I just did an apt list and it seems that Python 3.7.6 is an available Ubuntu 18 package. Maybe I should upgrade to that.. Perhaps only if there are problems.
> 
> Before March 17th, I suppose there is an argument to be made that "if it ain't broke, don't fix it". After the demo, I definitely favor a prebuilt python3 distribution from a reproducibility standpoint.

On my end, much success has been had with:
```
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash Miniconda3-latest-Linux-x86_64.sh  # and go through install process
$ conda create -y -n RTX python=3.7.3
$ conda activate RTX
$ git clone https://github.com/RTXteam/RTX.git
$ cd RTX
$ pip install -r requirements.txt 
```
Then follow [these directions](https://github.com/RTXteam/RTX/wiki/Dev-info#setting-up-mysql-and-initializing-for-local-dev-work-on-arax). And a fresh python 3.7.3 (or whatever flavor you like) is up and running.

But I'm all for "if it ain't broke...." just offering a suggestion if something does break

**Comment by saramsey** [comment] 2020-02-29 06:13
Just pushed a new version of `NormGoogleDistance.py` to branch `pickle-ngd`. None of the existing methods have been modified. But now there is a new *instance* method of the class `NormGoogleDistance` called `get_ngd_for_all_fast` that has the same calling signature as the static class method `get_ngd_for_all`, except the former method is an instance method so of course it has `self` as a first argument. The `get_ngd_for_all_fast` method needs to be an instance method so that we only have to load the pickleDB databases *once* during the lifetime of the lifetime of the `NormGoogleDistance` object. Example tests shown here:
```
   ngd = NormGoogleDistance()
    assert abs(0.3901010209565451 - ngd.get_ngd_for_all_fast(['DOID:10763', 'DOID:6713'], [None, None])) < 1e-10
```
if the pickleDB lookups don't work, the `get_ngd_for_all_fast` method just falls back on calling the static class method `get_ngd_for_all`.  Just to be clear, this is all in the `pickle-ngd` branch.

**Comment by saramsey** [comment] 2020-02-29 06:15
I see that in the `pickle-ngd` branch, `pickledb` is already in the top-level `requirements.txt` file. So evidently there is no need for me to add it.

**Comment by saramsey** [comment] 2020-02-29 06:16
Just to be clear -- if you create a new `NormGoogleDistance` each time you want to call `get_ngd_for_all_fast`, the performance will be *terrible*. You need to create an instance of `NormGoogleDistance` (call it `ngd`) once at module level in whatever calling module you are using, and then use the stored `ngd` instance object every time you want to do a NGD lookup.

**Comment by saramsey** [comment] 2020-02-29 06:18
also, I didn't check any of the nice scripts that Amy and Finn wrote to generate the data for the pickleDB files, into this branch. @finnagin  and @amykglen can you figure out where in the code-base those scripts should go, and please check those scripts into the `pickle-ngd` branch? Thank you.

**Comment by saramsey** [comment] 2020-02-29 06:24
tagging @dkoslicki as I think it is ready for your review (again, in the `pickle-ngd` branch)

**Comment by saramsey** [comment] 2020-02-29 06:28
in order to test it, you'll need to install the two pickledb files (`curie_to_mesh.db` and `mesh_to_pmid.db`) in the same directoroy as `NormGoogleDistance.py` (i.e., in `kg-construction`). You can get those pickledb files from `/home/ubuntu` on `arax.rtx.ai`.

**Comment by dkoslicki** [comment] 2020-02-29 17:56
@saramsey I’ll see if I can get to testing this afternoon.

**Comment by dkoslicki** [comment] 2020-02-29 19:33
@saramsey @finnagin Ran into this error:
```
 File "/home/dkoslicki/Data/Repos/RTX/code/ARAX/ARAXQuery/Overlay/compute_ngd.py", line 132, in compute_ngd
    ngd_value = self.NGD.get_ngd_for_all_fast([source_curie, target_curie], [source_name, target_name])
  File "/home/dkoslicki/Data/Repos/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 74, in get_ngd_for_all_fast
    return NormGoogleDistance.compute_multiway_ngd_from_counts(*counts_res)
  File "/home/dkoslicki/Data/Repos/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 56, in compute_multiway_ngd_from_counts
    return (max([math.log(count) for count in marginal_counts]) - math.log(joint_count)) / \
  File "/home/dkoslicki/Data/Repos/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 56, in <listcomp>
    return (max([math.log(count) for count in marginal_counts]) - math.log(joint_count)) / \
ValueError: math domain error
```
Trying a fix on my end...

**Comment by dkoslicki** [comment] 2020-02-29 19:49
Fixing via
```python
@staticmethod
    def compute_multiway_ngd_from_counts(marginal_counts: List[int],
                                         joint_count: int) -> float:
        # Make sure that things are within the right domain for the logs
        # Should also make sure things are not negative, but I'll just do this with a ValueError
        if None in marginal_counts:
            return math.nan
        elif 0 in marginal_counts or 0. in marginal_counts:
            return math.nan
        elif joint_count == 0 or joint_count == 0.:
            return math.nan
        else:
            try:
                return (max([math.log(count) for count in marginal_counts]) - math.log(joint_count)) / \
                   (math.log(NGD_NORMALIZER) - min([math.log(count) for count in marginal_counts]))
            except ValueError:
                return math.nan
```
in `overlay`

**Comment by dkoslicki** [comment] 2020-02-29 20:26
@saramsey @amykglen  @finnagin 
Got the code working, fixes pushed to `overlay`. Feel free to merge `overlay` into `pickle-ngd`
**Analysis**
Using old code:
```
"add_qnode(curie=DOID:1936, id=n00)",  # Atherosclerosis
"add_qnode(type=phenotypic_feature, is_set=True, id=n01)",
"add_qedge(source_id=n00, target_id=n01, id=e00, type=has_phenotype)",
"expand(edge_id=e00)",
"overlay(action=compute_ngd)"
```
163 phenotypes, takes **6min 19 sec**

Using new code:
```
"add_qnode(curie=DOID:10223, id=n00)",  # <----- new DOID since need to avoid now cached results
"add_qnode(type=phenotypic_feature, is_set=True, id=n01)",
"add_qedge(source_id=n00, target_id=n01, id=e00, type=has_phenotype)",
"expand(edge_id=e00)",
"overlay(action=compute_ngd)"
```
156 phenotypes, takes  **3min 17 sec**

**Conclusion**
It's faster, but lot's of db misses. 
Examples:
DOID:4448-->phenotypic_feature; then overlay ngd: 68 hits to db, 90 fallback to old method
DOID:10223-->phenotypic_feature; then overlay ngd:  107 hits to db,  49 fallback to old method
DOID:12384-->phenotypic_feature; then overlay ngd:  94 hits to db, 61 fallback to old method

Only tested with DOID's and HP's for simplicity, but this is probably due to the issue of mapping an arbitrary CURIE to MeSH is a hard one. But when it does get a db hit, it's super fast! But when it misses, it's still very, very slow.

Can give a list of CURIE's leading to db misses (like 'HP:0007769'/"Peripheral retinal degeneration") if it's helpful.

**Idea**
Use the "normalizer" https://nodenormalization-sri.renci.org/apidocs/#/Interfaces/get_get_normalized_nodes
If our (curie1) is not in curie_to_mesh.db, but there is an equivalent synonym (curie2) according to the normalizer where (curie2) is in the curie_to_mesh.db, then update curie_to_mesh.db by using (curie1) -> "MeSH term associated with (curie2)"
Might or might not work. Not every CURIE is going to have a MeSH term directly associated with it.

**Comment by saramsey** [comment] 2020-02-29 20:49
Ah, sorry about the `ValueError`. Good catch.

**Comment by amykglen** [comment] 2020-03-05 00:35
Ok, I'm going to resume work on this to see if we can decrease the number of misses - plan (from Steve via email) is to write:

> a python script that looks through KG2 for CURIEs of the following core types (HP, DOID, OMIM, Reactome, UniProtKB, ChEMBL, etc.) that do *not* map to a MESH ID by the current pickleDB, but that *can* be mapped to a MESH ID in KG2 via one-hop (either by an equivalent_to or close_match relationship in either direction?) or that *can* be mapped to another CURIE in KG2 that *is* mappable to a MESH term in the pickleDB

Will start by just counting how many CURIEs this script would catch.

(And after this KG2 script, we also plan to look into using the 'normalizer' as David suggested above.)

**Comment by amykglen** [comment] 2020-03-05 18:08
Hmm, so initial counts of new curie->mesh mappings found using one of these two methods (in kg2endpoint2)
```
1. (n)-[equivalent_to or close_match]-(MESH)
2. (n)-[equivalent_to or close_match]-(curie that IS mapped already in curie_to_mesh.db)
```
are as follows (for 'core types'):
```
  Total new 'DOID:' mappings: 967
  Total new 'HP:' mappings: 1
  Total new 'OMIM:' mappings: 14
  Total new 'REACT:' mappings: 0
  Total new 'UniProtKB:' mappings: 0
  Total new 'CHEMBL' mappings: 0
  Total new 'GO:' mappings: 50
  Total new 'NCBIGene:' mappings: 976
  Total new 'CL:' mappings: 0
  Total new 'UBERON:' mappings: 1
  Total new 'KEGG:' mappings: 0
  Total new 'MONDO:' mappings: 10644

IN TOTAL: 12653 new curie->mesh mappings found. (693 of which are for curies in KG1)
```

Worth noting that method 1. only produced anything for 'MONDO' nodes, which makes sense given that these are the only 'equivalent_to'/'close_match' mappings to mesh terms in kg2endpoint2:
```
match (n)-[r]-(m) where m.id starts with "MESH:" and (r.simplified_edge_label="close_match" or r.simplified_edge_label="equivalent_to") return count(distinct n), n.provided_by order by count(distinct n) desc
```
![Screen Shot 2020-03-05 at 11 04 48 AM](https://user-images.githubusercontent.com/49423686/76011053-275fff80-5ed1-11ea-8ddd-e7bc67af90dd.png)

**Comment by amykglen** [comment] 2020-03-08 00:37
So I looked a bit into the SRI team's [node normalizer](https://nodenormalization-sri.renci.org/apidocs/#/), and it turns out that the synonyms it returns for a curie can include MESH terms themselves, as well as other equivalent curies... did some counting to get an idea of coverage - here are how many unmapped KG1 curies (meaning, those not yet in `curie_to_mesh.db`) would be caught with this tool:
```
Found new MESH mappings for...
    1 of 47197 unmapped GO nodes
    417 of 9965 unmapped HP nodes
    5999 of 17739 unmapped KEGG.COMPOUND nodes
    14 of 1841 unmapped OMIM nodes
    0 of 20514 unmapped UniProtKB nodes
    1374 of 2226 unmapped CHEMBL.COMPOUND nodes
    690 of 6531 unmapped DOID nodes
    0 of 2215 unmapped REACT nodes
    19 of 544 unmapped UBERON nodes
    0 of 1697 unmapped NCBIGene nodes
    2 of 42 unmapped CL nodes
    0 of 1 unmapped AQTLTrait nodes

In total, found new mappings for 8516 of 110512 unmapped KG1 nodes
```
So that would increase `curie_to_mesh.db`'s coverage of KG1 nodes **from 11% to 18%**.

To get these counts, I sent all of the unmapped KG1 curies to the normalizer (in batches - to `/get_normalized_nodes`), and looked to see which curies' `equivalent_identifers` included a MESH term **or** a curie that is already mapped to a MESH term in `curie-to-mesh.db`.

Also, it may be worth noting that, from what I can tell, the normalizer API seems pretty fast... might be reasonable to use it directly in computing ngd (if desired), rather than extracting and storing data from it in `curie_to_mesh.db`...

**Comment by edeutsch** [comment] 2020-03-08 20:22
My initial reactions was "wow, 11%/18% is *really* low!" But on further thought, I suppose it's not unreasonable that MeSH wouldn't have entries for the UniProtKB entries. One interesting question is for each category, how many total entries are there. I just looked for UniProtKB and it's 26957. So the implication is that there are MeSH headings for 6000 UniProtKBs? Which is interesting, I would not have guessed that.

Other random thought: I wonder if we could use SemMedDB to help compute more NGDs? It also has PMID to concept mappings, does it? And maybe greater coverage of concepts in our KG?

**Comment by dkoslicki** [comment] 2020-03-08 20:38
The only issue with SemMedDB is we get triples of (subject, object, predicate) from SemMedDB, so we would need to decide if we ignore the predicate part (which seems like it could be biologically unrealistic in certain cases). But other than that, we definitely could do NGD but on SemMedDB.

One potential downside of using SemMedDB is that, while the NCBI MeSH term version counts terms as co-occuring if terms show up anywhere in the abstract, SemMedDB would only count things as co-occuring if they show up in the same (or nearby?) sentences, since that's how it derives its (s,o,p) triplets.

**Comment by edeutsch** [comment] 2020-03-08 21:18
For each of those triples, do we also know which PMID the information comes from? I thought we would. But now I'm not sure. I was thinking that if each triple has a PMID association, then we can aggregate all the subjects and all the objects and the PMIDs they come from, and ignore the predicates as you say.

**Comment by dkoslicki** [comment] 2020-03-09 18:19
@finnagin would know if we get PMID's with SemMedDB as he's worked extensively with that.

**Comment by amykglen** [comment] 2020-03-09 21:38
I believe we do get PMIDs for SemMedDB edges in KG2

![Screen Shot 2020-03-09 at 2 29 32 PM](https://user-images.githubusercontent.com/49423686/76258017-65825980-6218-11ea-8074-f7e907db03be.png)

but I think SemMedDB subjects/objects are only given as CUIs or NCBIGene IDs, so we'd have to figure out how to map other curies to those (?)

![Screen Shot 2020-03-09 at 3 36 15 PM](https://user-images.githubusercontent.com/49423686/76259682-c8c1bb00-621b-11ea-97a2-4efc0613de6d.png)

**Comment by edeutsch** [comment] 2020-03-09 21:53
hmm, may be tricky to integrate it with the NCBI-curated information.

**Comment by amykglen** [comment] 2020-03-10 15:36
ok! will plan to consult Finn. yeah, I get the PMID portion (PMIDs are definitely provided for each triple in SemMedDB's ['predication' table](https://skr3.nlm.nih.gov/SemMedDB/dbinfo.html), and I understand how we could assign those PMIDs to SemMedDB 'nodes'), but what I'm not sure of is where the connection between nodes in **our** knowledge graph (which we're trying to assign PMIDs to) and the nodes in SemMedDB would come from (since SemMedDB nodes are only CUIs and NCBIGenes, and our knowledge graph(s) include a lot of other kinds of nodes as well).

**Comment by edeutsch** [comment] 2020-03-10 16:15
I have an idea for a translator. I will see if I can create this.

**Comment by edeutsch** [comment] 2020-03-11 08:10
The KGNodeIndex enhancements described in the other issue might do a nice job translating CUIs for you.

**Comment by saramsey** [comment] 2020-04-22 23:03
Can we close this issue?

**Comment by edeutsch** [comment] 2020-04-22 23:25
I think yes

**Comment by amykglen** [comment] 2020-04-23 00:29
If we do close it we may want to open another issue to enhance curie->mesh coverage, since we don't have a truly "fast" NGD yet because of that.. (only 10% coverage of kg1 nodes in the current version) - though we've identified multiple avenues for doing so that need to be explored and/or implemented.

**Comment by dkoslicki** [comment] 2020-04-29 20:33
@amykglen Since the interim pickleDB has been implemented, I would vote: yes, go ahead and close this one and open a new issue mentioning that we have only 10% coverage of kg1 nodes in the current version (see #719 ), and consider if we can ETL/utilize Text Mining Provider (PI: Bill Baumgartner) as a larger(?)/better(?) SemMedDB/NCBIeUtils alternative

**Comment by edeutsch** [comment] 2020-04-29 20:38
Somewhere I mentioned that it would be nice to have different urls for FastNGD vs. eutils NGD so that we can verify that this is actually working on /beta. Or do we have other direct confirmation that FastNGD is actually working as well as it can on /beta?

**Comment by dkoslicki** [comment] 2020-04-29 20:39
> Somewhere I mentioned that it would be nice to have different urls for FastNGD vs. eutils NGD so that we can verify that this is actually working on /beta. Or do we have other direct confirmation that FastNGD is actually working as well as it can on /beta?

I think @finnagin or @amykglen may be able to answer that

**Comment by amykglen** [comment] 2020-04-30 14:07
Yes - I am planning to add logging so we can see how often fastNGD is utilized - Finn and I confirmed with @dkoslicki that it's ok to edit the overlay code to do this. I was just waiting to hear if it's ok to do this directly in master?

**Comment by dkoslicki** [comment] 2020-04-30 14:39
@amykglen I think doing it on master makes sense, considering it wants to be tested in production/beta anyways, so will need to be rolled out there from master in any case.

**Comment by amykglen** [comment] 2020-04-30 15:25
Cool! Ok, made it so that now a `debug` message like this is logged after `compute_ngd` is done:
```
DEBUG: Used fast NGD for 0 edges, back-up NGD method for 80
```
Ready to roll out to beta and test.

**Comment by edeutsch** [comment] 2020-04-30 15:42
rolled out to /beta!

**Comment by edeutsch** [comment] 2020-04-30 15:49
the code I tried certainly printed out that note:
2020-04-30 15:46:38.978576 INFO:    Computing the normalized Google distance: weighting edges based on source/target node co-occurrence frequency in PubMed abstracts   
2020-04-30 15:46:38.978583 INFO:    Converting CURIE identifiers to human readable names   2020-04-30 15:46:38.978621 WARNING:    Utilizing API calls to NCBI eUtils, so this may take a while...   2020-04-30 15:47:08.995286 INFO:    NGD values successfully added to edges   
2020-04-30 15:47:08.995306 DEBUG:    Used fast NGD for 0 edges, back-up NGD method for 64

Can we find an example that shows FastNGD proving more than 0 result?

**Comment by amykglen** [comment] 2020-04-30 15:50
Yeah, my first try also didn't use fast NGD at all - working on finding one now!

**Comment by amykglen** [comment] 2020-04-30 15:52
Ok, found one (here: https://arax.rtx.ai/beta/?m=1776) using this query:
```
add_qnode(curie=DOID:14330, id=n00)
add_qnode(type=phenotypic_feature, is_set=True, id=n01)
add_qedge(source_id=n01, target_id=n00, id=e00)
expand(edge_id=e00)
overlay(action=compute_ngd)
```

```
   2020-04-30 15:49:39.609953 INFO:    Computing the normalized Google distance: weighting edges based on source/target node co-occurrence frequency in PubMed abstracts
   2020-04-30 15:49:39.609960 INFO:    Converting CURIE identifiers to human readable names
   2020-04-30 15:49:39.610088 WARNING:    Utilizing API calls to NCBI eUtils, so this may take a while...
   2020-04-30 15:51:26.448595 INFO:    NGD values successfully added to edges
   2020-04-30 15:51:26.448627 DEBUG:    Used fast NGD for 81 edges, back-up NGD method for 47
```

**Comment by edeutsch** [comment] 2020-04-30 20:10
okay, it looks like this is all good and done and rolled out, thanks!

The only thing that still puzzles me is why the hit rate is low. Just for my own understanding, can someone explain the reason here? Or point me to a link if it already explained somewhere? I was under the impression that NCBI was basically just taking all the keywords from all PubMed articles, mapping those to a set of terms, and then making that available in eutils. And I was under the impression that we just did the same thing. So... I was thinking that our coverage should be the same. Roughly. Why is our coverage (apparently?) so much less? Is it that NCBI is not just using keywords but rather are also parsing abstract text (and maybe full articles?) for additional concepts that are not in the keywords?

**Comment by amykglen** [comment] 2020-04-30 22:23
So we have no problem mapping MESH terms to PubMed articles (the pickledb system can provide essentially the same coverage as NCBIeUtils for that) - the problem is in mapping arbitrary curies (e.g., "DOID:14330") to MESH terms (so that they can then be mapped to PubMed articles). (David explained these two halves of the problem in slack [here](https://isb-ncats.slack.com/archives/CTD9V3YR2/p1582162516005400).)

I believe our initial attempt at the curie -> MESH mappings used OxO to grab as many of the mappings as we could for KG1 nodes (@saramsey and @finnagin know more about this part than I do), because we couldn't find a data dump for NCBI eUtils. But we've since identified potential methods for improvement that just need to be explored/done (like utilizing your KGNodeIndex synonym method)...

**Comment by edeutsch** [comment] 2020-04-30 23:59
aha, great, thanks for the summary. So all PubMed article keywords are in the form of MeSH terms, and the mapping of MeSH terms to our curies needs work and can be much better.

1) But once we can perform highly effective mapping from MeSH terms to our curies, then FastNGD should be nearly as effective as eutils?

2) When we reach that point, then there's no point in falling back to eutils because our coverage will be just as good and if FastNGD can't find it, then slow eutils won't find it and we don't want to spend lots of time with no additional hits?

**Comment by amykglen** [comment] 2020-05-01 00:44
Yes, I believe all of that is correct!

So I suppose I'll open another issue as David suggested above for improving curie -> mesh mappings, and then we can close this issue and #715?

**Comment by edeutsch** [comment] 2020-05-01 01:35
sounds good, thanks.

**Closed** 2020-05-01 14:57 UTC
Labels: ARAX demo, enhancement, high priority
