### ISSUE TITLE
A list of examples for improving NodeSynonymizer

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1252] opened 2021-02-10 22:06 UTC
Hi @edeutsch, here are several examples for you to improve the NodeSynonymizer:

1. There are around 53,441 nodes in KG2.5.1C of which the category!=`biolink:Disease`/`biolink:PhenotypicFeature`/`biolink:DiseaseOrPhenotypicFeature` but the `all_categories` attribute has these categories. Some of them should not belong to one of `biolink:Disease`/`biolink:PhenotypicFeature`/`biolink:DiseaseOrPhenotypicFeature`. These nodes can be queried by using DSL command: `match (n) where ((n.category<>'biolink:Disease' and n.category<>'biolink:PhenotypicFeature' and n.category<>'biolink:DiseaseOrPhenotypicFeature') and ('biolink:Disease' in n.all_categories or 'biolink:PhenotypicFeature' in n.all_categories or 'biolink:DiseaseOrPhenotypicFeature' in n.all_categories)) return n.id, n.category, n.all_categories limit 25`. I list a few of them below for reference:

n.id | n.category | n.all_categories
-- | -- | --
"biolink:GenotypicSex" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:PhenotypicFeature"]
"biolink:Outcome" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:PhenotypicFeature"]
"biolink:phase" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:InformationContentEntity", "biolink:NamedThing", "biolink:Attribute", "biolink:PhenotypicFeature"]
"biolink:volume" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:InformationContentEntity", "biolink:Procedure", "biolink:Publication", "biolink:Attribute", "biolink:NamedThing", "biolink:QuantityValue", "biolink:PhenotypicFeature", "biolink:PhysicalEntity"]
"biolink:manifestation_of" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:InformationContentEntity", "biolink:PhenotypicFeature", "biolink:QuantityValue"]
"biolink:located_in" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:PhenotypicFeature"]
"biolink:PhenotypicSex" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:PhenotypicFeature"]
"UniProtKB:P61278" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P01588" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:Gene", "biolink:Protein", "biolink:ChemicalSubstance", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P01308" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature"]
"UniProtKB:P30046" | "biolink:Protein" | ["biolink:NamedThing", "biolink:ChemicalSubstance", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature"]
"CHEBI:35940" | "biolink:ChemicalSubstance" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:GenomicEntity", "biolink:Protein", "biolink:PhenotypicFeature"]
"UniProtKB:P00451" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P00740" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance", "biolink:Cell", "biolink:Metabolite"]
"UniProtKB:P08709" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance", "biolink:Metabolite"]
"CHEBI:7872" | "biolink:ChemicalSubstance" | ["biolink:MolecularEntity", "biolink:Drug", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Procedure", "biolink:Phenomenon", "biolink:ChemicalSubstance", "biolink:NamedThing", "biolink:Protein", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P61626" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Drug", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:Phenomenon", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"GO:0035176" | "biolink:BiologicalProcess" | ["biolink:OntologyClass", "biolink:Activity", "biolink:BiologicalProcess", "biolink:PhenotypicFeature"]
"UMLS_STY:T033" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Procedure", "biolink:PhenotypicFeature"]
"UMLS_STY:T088" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Carbohydrate", "biolink:NamedThing", "biolink:PhenotypicFeature"]
"UMLS_STY:T087" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Protein", "biolink:NamedThing", "biolink:AnatomicalEntity", "biolink:PhenotypicFeature"]
"UniProtKB:P01185" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UMLS:C0033631" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P00742" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P04275" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:AnatomicalEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:Drug", "biolink:ChemicalSubstance"]

2. There are around 58,802 nodes in KG2.5.1C of which the category!=`biolink:Drug`/`biolink:ChemicalSubstance` but the `all_categories` attribute has these categories. These nodes can be queried by using DSL command: `match (n) where ((n.category<>'biolink:Drug' and n.category<>'biolink:ChemicalSubstance') and ('biolink:Drug' in n.all_categories or 'biolink:ChemicalSubstance' in n.all_categories)) return n.id, n.category, n.all_categories limit 25`. I list a few of them below for reference:

n.id | n.category | n.all_categories
-- | -- | --
"biolink:Drug" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Procedure", "biolink:Drug"]
"biolink:has_part" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Attribute", "biolink:NamedThing", "biolink:Drug", "biolink:RelationshipType"]
"biolink:Food" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:NamedThing", "biolink:Procedure", "biolink:BiologicalEntity", "biolink:ChemicalSubstance"]
"biolink:types/Date" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Drug", "biolink:InformationContentEntity", "biolink:Procedure", "biolink:Attribute", "biolink:QuantityValue"]
"biolink:Agent" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:NamedThing", "biolink:ChemicalSubstance", "biolink:Attribute"]
"biolink:Transcript" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:ChemicalSubstance", "biolink:NamedThing", "biolink:GeneProduct"]
"biolink:part_of" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:Attribute", "biolink:Drug", "biolink:RelationshipType", "biolink:AnatomicalEntity"]
"biolink:Genome" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:InformationContentEntity", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:NamedThing", "biolink:ChemicalSubstance"]
"biolink:filler" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:NamedThing", "biolink:ChemicalSubstance"]
"biolink:Metabolite" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:ChemicalSubstance", "biolink:Procedure", "biolink:NamedThing", "biolink:Metabolite"]
"biolink:Gene" | "biolink:OntologyClass" | ["biolink:OntologyClass", "biolink:GenomicEntity", "biolink:Procedure", "biolink:NamedThing", "biolink:ChemicalSubstance"]
"UMLS:C0039419" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:ChemicalSubstance"]
"MESH:D014612" | "biolink:MolecularEntity" | ["biolink:MolecularEntity", "biolink:Procedure", "biolink:ChemicalSubstance", "biolink:NamedThing"]
"UMLS:C0205997" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:ChemicalSubstance"]
"UMLS:C0003240" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:Drug"]
"UMLS:C0020656" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:InformationContentEntity", "biolink:Protein", "biolink:ChemicalSubstance", "biolink:QuantityValue"]
"UMLS:C0041931" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:Drug"]
"UniProtKB:P61278" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UMLS:C0065760" | "biolink:MolecularEntity" | ["biolink:MolecularEntity", "biolink:Drug"]
"ATC:G03FA06" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:ChemicalSubstance"]
"UMLS:C0040905" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:Drug"]
"UMLS:C0011892" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:Drug"]
"UMLS:C0304541" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:ChemicalSubstance"]
"UniProtKB:P01588" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:Gene", "biolink:Protein", "biolink:ChemicalSubstance", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UMLS:C1328071" | "biolink:MolecularEntity" | ["biolink:MolecularEntity", "biolink:Drug", "biolink:ChemicalSubstance"]

3. There are around 532 nodes in KG2.5.1C which have a synonym which are both `biolink:Disease`/`biolink:PhenotypicFeature`/`biolink:DiseaseOrPhenotypicFeature` and `biolink:Drug`/`biolink:ChemicalSubstance`. These nodes can be queried by using DSL command: `match (n) where (('biolink:Disease' in n.all_categories or 'biolink:PhenotypicFeature' in n.all_categories or 'biolink:DiseaseOrPhenotypicFeature' in n.all_categories) and ('biolink:Drug' in n.all_categories or 'biolink:ChemicalSubstance' in n.all_categories)) return n.id, n.category, n.all_categories limit 25`. I list a few of them below for reference:

n.id | n.category | n.all_categories
-- | -- | --
"UniProtKB:P61278" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P01588" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:Gene", "biolink:Protein", "biolink:ChemicalSubstance", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P01308" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:Procedure", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature"]
"UniProtKB:P30046" | "biolink:Protein" | ["biolink:NamedThing", "biolink:ChemicalSubstance", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:PhenotypicFeature"]
"CHEBI:35940" | "biolink:ChemicalSubstance" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:GenomicEntity", "biolink:Protein", "biolink:PhenotypicFeature"]
"UniProtKB:P00451" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P00740" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance", "biolink:Cell", "biolink:Metabolite"]
"UniProtKB:P08709" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance", "biolink:Metabolite"]
"CHEBI:7872" | "biolink:ChemicalSubstance" | ["biolink:MolecularEntity", "biolink:Drug", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Procedure", "biolink:Phenomenon", "biolink:ChemicalSubstance", "biolink:NamedThing", "biolink:Protein", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P61626" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Drug", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:Phenomenon", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"OMIM:MTHU003378" | "biolink:PhenotypicFeature" | ["biolink:ChemicalSubstance", "biolink:PhenotypicFeature", "biolink:NamedThing", "biolink:Disease", "biolink:Procedure", "biolink:DiseaseOrPhenotypicFeature", "biolink:PhysiologicalProcess", "biolink:PhysicalEntity", "biolink:Drug"]
"MONDO:0012860" | "biolink:Disease" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:Procedure", "biolink:Phenomenon", "biolink:Disease", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UniProtKB:P01185" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Drug", "biolink:ChemicalSubstance", "biolink:AnatomicalEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"UMLS:C0033631" | "biolink:NamedThing" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"MONDO:0005812" | "biolink:Disease" | ["biolink:ChemicalSubstance", "biolink:Disease", "biolink:NamedThing"]
"UniProtKB:P00742" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P04275" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:AnatomicalEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:Drug", "biolink:ChemicalSubstance"]
"UniProtKB:P09683" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:Drug", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:ChemicalSubstance", "biolink:NamedThing", "biolink:PhenotypicFeature", "biolink:Metabolite"]
"CHEBI:16526" | "biolink:ChemicalSubstance" | ["biolink:ChemicalSubstance", "biolink:Drug", "biolink:Procedure", "biolink:DiseaseOrPhenotypicFeature", "biolink:PhenotypicFeature", "biolink:Phenomenon"]
"UniProtKB:P02768" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:Procedure", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Drug", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"UniProtKB:P01270" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Drug", "biolink:AnatomicalEntity", "biolink:Gene", "biolink:Protein", "biolink:GenomicEntity", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance", "biolink:Metabolite"]
"UniProtKB:P06276" | "biolink:Protein" | ["biolink:NamedThing", "biolink:MolecularEntity", "biolink:Procedure", "biolink:Gene", "biolink:Protein", "biolink:Disease", "biolink:PhenotypicFeature", "biolink:ChemicalSubstance"]
"SNOMED:91555003" | "biolink:PhenotypicFeature" | ["biolink:NamedThing", "biolink:BiologicalEntity", "biolink:DiseaseOrPhenotypicFeature", "biolink:PhenotypicFeature", "biolink:Drug"]
"UniProtKB:P01275" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:Procedure", "biolink:NamedThing", "biolink:Drug", "biolink:AnatomicalEntity", "biolink:GenomicEntity", "biolink:Gene", "biolink:Protein", "biolink:ChemicalSubstance", "biolink:PhenotypicFeature"]
"UniProtKB:P09848" | "biolink:Protein" | ["biolink:MolecularEntity", "biolink:NamedThing", "biolink:Gene", "biolink:Protein", "biolink:Procedure", "biolink:PhenotypicFeature", "biolink:Drug", "biolink:ChemicalSubstance"]

**Comment by amykglen** [comment] 2021-02-10 22:39
some more examples for @edeutsch  - here are the 16 nodes in KG2.5.1c that have both `biolink:Drug` and `biolink:Disease` in their `all_categories`:

n.id | n.name | n.all_names
-- | -- | --
"OMIM:MTHU003378" | "Polyuria" | ["Osmotic diuresis", "diuretic", "Polyuria", "Polyuric state", "polyuria", "Diuretics", "Diuresis", "Diuretic"]
"MONDO:0012860" | "thrombophilia due to protein C deficiency, autosomal recessive" | ["Thrombophilia, Hereditary, Due To Protein C Deficiency, Autosomal Dominant", "Thrombophilia, Hereditary, Due To Protein C Deficiency, Autosomal Recessive", "Protein C", "protein C", "Protein c", "THROMBOPHILIA DUE TO PROTEIN C DEFICIENCY, AUTOSOMAL RECESSIVE; THPH4", "thrombophilia due to protein C deficiency, autosomal recessive"]
"DRUGBANK:DB10572" | "Corn" | ["corn", "Corn"]
"UniProtKB:P22301" | "IL-10" | ["Seronegative rheumatoid arthritis", "Interleukin-10", "Rheumatoid arthritis flare up", "Rheumatoid arthropathies", "Monoarthritic rheumatoid arthritis", "interleukin-10 (human)", "Rheumatoid Arthritis", "Arthritis, Rheumatoid", "RHEUMATOID ARTHRITIS; RA", "Interleukin 10", "interleukin-10", "Seropositive rheumatoid arthritis", "Rheumatoid arthritis aggravated", "Spinal rheumatoid arthritis", "Rheumatoid arthropathy", "Rheumatoid arthritis", "rheumatoid arthritis", "interleukin 10", "IL-10", "interleukin 10 [Source:HGNC Symbol;Acc:HGNC:5962]"]
"UniProtKB:P41159" | "LEP" | ["LEP", "Leptin", "Obesity due to congenital leptin deficiency", "leptin (human)", "leptin", "leptin [Source:HGNC Symbol;Acc:HGNC:6553]", "Leptin deficiency or dysfunction", "obesity due to congenital leptin deficiency"]
"UniProtKB:P05305" | "ET-1" | ["AURICULOCONDYLAR SYNDROME 3; ARCND3", "auriculocondylar syndrome 3", "Endothelin 1", "endothelin 1 [Source:HGNC Symbol;Acc:HGNC:3176]", "endothelin-1 (human)", "endothelin 1", "ET-1", "endothelin-1", "Endothelin-1"]
"UniProtKB:P15502" | "ELN" | ["elastin", "elastin (human)", "cutis laxa, autosomal dominant 1", "Elastin", "elastin [Source:HGNC Symbol;Acc:HGNC:3327]", "CUTIS LAXA, AUTOSOMAL DOMINANT 1; ADCL1", "autosomal dominant cutis laxa 1", "ELN"]
"UniProtKB:P07225" | "PROS1" | ["Protein S", "Protein s", "vitamin K-dependent protein S", "protein S [Source:HGNC Symbol;Acc:HGNC:9456]", "thrombophilia due to protein S deficiency, autosomal recessive", "THROMBOPHILIA DUE TO PROTEIN S DEFICIENCY, AUTOSOMAL RECESSIVE; THPH6", "protein S", "PROS1", "vitamin K-dependent protein S (human)", "Vitamin K-Dependent Protein S"]
"UniProtKB:P04040" | "CAT" | ["catalase", "acatalasia", "Acatalasemia", "catalase [Source:HGNC Symbol;Acc:HGNC:1516]", "catalase (human)", "Cat", "Acatalasia", "Catalase", "CAT"]
"MONDO:0020169" | "rare disorder with ptosis" | ["Ophthalmic Solution", "Mechanical ptosis", "Ptosis", "Eye solution", "Myogenic ptosis", "Aponeurotic ptosis", "ptosis", "Eyelid ptosis", "rare disorder with ptosis", "Prolapse", "Ptosis of eyelid", "Levator dehiscence", "ptosis (disease)", "Blepharoptosis", "Ophthalmic Solutions", "Eye drop", "Paralytic ptosis"]
"MONDO:0005800" | "hordeolum" | ["hordeolum", "Hordeolum externum", "hordeolum externum", "Hordeolum", "External hordeolum", "Stye"]
"MONDO:0005683" | "brucellosis" | ["Brucella melitensis", "Brucellosis", "Infection due to Brucella abortus", "Brucella suis", "brucellosis", "Brucella abortus", "Brucella canis"]
"MONDO:0018076" | "tuberculosis" | ["Tuberculous", "Primary tuberculous complex, unspecified examination", "tuberculosis", "Sequelae of tuberculosis", "Other primary progressive tuberculosis, confirmed by animal inoculation", "Tuberculosis NOS aggravated", "Tuberculous Abscess", "Other primary progressive tuberculosis, confirmed by bacterial culture", "Primary tuberculous complex, confirmed by bacterial culture", "Late effects of tuberculosis of other specified organs", "Mycobacterium tuberculosis", "Tuberculosis, postpartum", "Primary tuberculous infection, unspecified type, confirmed histologically", "Primary tuberculous complex", "Primary tuberculous complex confirmed histologically", "Mycobacterium tuberculosis infection reactivated", "Primary tuberculous infection, unspecified type, unspecified examination", "Chronic tuberculosis", "Active tuberculosis", "Tuberculosis", "Old tuberculosis", "Tuberculosis, antepartum", "Other primary progressive tuberculosis, confirmed histologically", "Primary tuberculous infection, unspecified type", "Primary tuberculous infection, unspecified type, confirmed by bacterial culture", "Primary tuberculous complex, tubercle bacilli found (in sputum) by microscopy", "Primary tuberculous complex, confirmed by animal inoculation", "Tuberculous abscess"]
"UMLS:C0302361" | "Shigella sonnei" | ["Shigella sonnei"]
"MESH:D000432" | "Methanol" | ["Methanol", "Methyl Alcohol", "METHYL ALCOHOL", "methanol"]
"UMLS:C0393947" | "Cholinergic crisis" | ["Increased gastric tonus", "Cholinergic Agents", "Cholinergic syndrome", "cholinergic drug", "Cholinergic crisis"]

**Comment by finnagin** [comment] 2022-02-02 01:43
@edeutsch @amykglen @chunyuma is this still relevant?

**Comment by chunyuma** [comment] 2022-02-02 01:47
I checked some of them and this problem seems to be fixed in the latest version of kg2c now.

**Comment by finnagin** [comment] 2022-02-02 05:46
Awesome, closing then.

**Closed by finnagin** 2022-02-02 05:46 UTC
Labels: node synonymizer, conflation
