### ISSUE TITLE
Node not normalized correctly

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1971] opened 2023-03-07 17:18 UTC
We have this CURIE: `PUBCHEM.COMPOUND:225609` which our node synonymizer says is synonymous to `PUBCHEM.COMPOUND:31378`, it says this info comes from the SRI NN, but at the very top, it has a blank SRI_NN. 
![image](https://user-images.githubusercontent.com/6362936/223498351-46fde2e5-3f4a-416e-8ef7-f237c864bf86.png)
Note also, the SRI_NN says that `PUBCHEM.COMPOUND:225609` is _not_ synonymous to `PUBCHEM.COMPOUND:31378`, but we think it is?!
![image](https://user-images.githubusercontent.com/6362936/223498550-69975228-2ef1-4237-8dcc-cc78acb41e5f.png)

Are we not hitting the SRI_NN? Or why does the none synonymizer thinks the NN says they are equivalent, when the NN says they are not?

**Comment by amykglen** [comment] 2023-03-07 23:50
not sure if this is a cause, but if I recall correctly, our SRI data might be a bit out of date; I think when we did the KG2.8.0c build, the SRI didn't yet have working Biolink 3.0 versions of the endpoints we needed, so I think we used cached SRI info (maybe from KG2.7.6?) @sundareswarpullela would know the details I think

**Comment by edeutsch** [comment] 2023-03-08 03:14
I don't know know what the cause here is, The most likely scenario is that they started out as 2 separate clusters, each with their own pubchem id from NN, but then some resource within RTX-KG2 called them the same or had a common name and the two clusters were merged, thus merging the 2 NN nodes. Thus, probably NN didn't call them the same, but they were in separate clusters that got merged (probably based on questionable data in KG2)

There was a time when we were far more comprehensive than SRI NN, but I'm thinking that they have probably surpassed us now in quality of clusters, although we are still overall larger.

The currently deployed NodeSynonymizer build process consults SRI NN and merges its information into our primary information source, KG2. So Nodesynonymizer is "KG2 centered" rather than "NN centered". But maybe that should now change.

I am now thinking that it may be time to re-design the NodeSynonymizer to * begin * with the SRI NN and never merge its clusters, and only merge in the RTX-KG2 information into the SRI NN scaffold of clusters. New clusters would be added for where we have additional concepts. There would be a few cases where we have overlapping names and synonyms, but I guess we would just make some least-bad decisions here.

I think such a product would vastly reduce these discrepancies that our current system has with SRI NN.

Does that seem reasonable? or other ideas?

Shall I do that or is someone working on this?

**Comment by dkoslicki** [comment] 2023-03-08 14:49
I do think that's reasonable: the UI is using only the NN to merge results, so I foresee lots more of these issues if we continue with the KG2-centric approach. I don't know of anyone else who's working on this, but @sundareswarpullela might know more.

**Comment by sundareswarpullela** [comment] 2023-03-08 15:23
Yeah so I used the data from https://nodenorm.ci.transltr.io/1.3/get_semantic_types endpoint that returned a list of semantic_types and build the latest synonymizer with it. Maybe that it being a CI endpoint, didn't return the complete data and was pointing to some test db internally is what is causing the issue? I'm not really sure though.

**Comment by amykglen** [comment] 2023-03-08 16:18
I'm working on a new synonymizer - I hadn't yet thought of disallowing the breaking up of the SRI's clusters, but that'd be pretty easy to incorporate. I'll try that out. I agree it makes sense to lean heavily on them given that they're the standard in Tranlsator.

more details on my learnings so far in today's AHM (I'll share a write-up for Eric too, who won't be there)

**Comment by amykglen** [comment] 2023-05-03 18:00
ok, in the latest version of the new synonymizer (#2003), I think this issue is sorted out

the SRI considers PUBCHEM.COMPOUND:225609 (fludrocortisone acetate) **NOT** synonymous with PUBCHEM.COMPOUND:31378 (fludrocortisone), so there are two separate clusters for these concepts:

Cluster for PUBCHEM.COMPOUND:225609 has 15 nodes:

| id                                   | category       | name                    | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:---------------|:------------------------|:---------|:------------|:-----------------|
| CAS:514-36-3                         | SmallMolecule  |                         | X        |             |                  |
| CHEBI:5102                           | SmallMolecule  | fludrocortisone acetate | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL1201010        | SmallMolecule  | FLUDROCORTISONE ACETATE | X        | X           |                  |
| DrugCentral:1191                     | SmallMolecule  | fludrocortisone acetate | X        | X           |                  |
| INCHIKEY:SYWHXTATXSMDSB-GSLJADNHSA-N | SmallMolecule  |                         | X        |             |                  |
| KEGG.COMPOUND:C08186                 | SmallMolecule  | Fludrocortisone acetate | X        | X           |                  |
| KEGG.DRUG:D00986                     | Drug           |                         |          | X           |                  |
| MESH:C034635                         | SmallMolecule  | fludrocortisone acetate | X        | X           |                  |
| NCIT:C1103                           | Drug           | Fludrocortisone Acetate |          | X           |                  |
| PDQ:CDR0000039243                    | ChemicalEntity | fludrocortisone acetate |          | X           |                  |
| PUBCHEM.COMPOUND:225609              | SmallMolecule  | Fludrocortisone acetate | X        |             | X                |
| RXNORM:165516                        | Drug           | fludrocortisone acetate |          | X           |                  |
| UMLS:C0616274                        | SmallMolecule  | fludrocortisone acetate | X        | X           |                  |
| UNII:V47IF0PVH4                      | SmallMolecule  | FLUDROCORTISONE ACETATE | X        |             |                  |
| VANDF:4017621                        | ChemicalEntity | Fludrocortisone acetate |          | X           |                  |

Cluster for PUBCHEM.COMPOUND:31378 has 20 nodes:

| id                                   | category       | name            | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:---------------|:----------------|:---------|:------------|:-----------------|
| ATC:H02AA02                          | ChemicalEntity | fludrocortisone |          | X           |                  |
| CAS:127-31-1                         | SmallMolecule  |                 | X        |             |                  |
| CHEBI:50885                          | SmallMolecule  | fludrocortisone | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL1201388        | SmallMolecule  | FLUDROCORTISONE | X        | X           |                  |
| DRUGBANK:DB00687                     | SmallMolecule  | Fludrocortisone | X        | X           |                  |
| GTOPDB:2873                          | SmallMolecule  | fludrocortisone | X        |             |                  |
| HMDB:HMDB0014825                     | SmallMolecule  | Fludrocortisone | X        | X           |                  |
| INCHIKEY:AAXVEMMRQDVLJB-BULBTXNYSA-N | SmallMolecule  |                 | X        |             |                  |
| KEGG.COMPOUND:C07004                 | SmallMolecule  | Fludrocortisone | X        | X           |                  |
| KEGG.DRUG:D07967                     | Drug           |                 |          | X           |                  |
| LOINC:LP35868-6                      | ChemicalEntity | Fludrocortisone |          | X           |                  |
| LOINC:MTHU018755                     | ChemicalEntity | Fludrocortisone |          | X           |                  |
| MESH:D005438                         | SmallMolecule  | Fludrocortisone | X        | X           |                  |
| NCIT:C71629                          | Drug           | Fludrocortisone |          | X           |                  |
| NDDF:004953                          | ChemicalEntity | fludrocortisone |          | X           |                  |
| PUBCHEM.COMPOUND:31378               | SmallMolecule  | Fludrocortisone | X        |             | X                |
| RXNORM:4452                          | Drug           | fludrocortisone |          | X           |                  |
| UMLS:C0016280                        | SmallMolecule  | fludrocortisone | X        | X           |                  |
| UNII:U0476M545B                      | SmallMolecule  | FLUDROCORTISONE | X        |             |                  |
| VANDF:4019758                        | ChemicalEntity | Fludrocortisone |          | X           |                  |

**Comment by amykglen** [comment] 2023-05-24 22:58
fixed on /test!

fludrocortisone acetate:
https://arax.ncats.io/test/?term=PUBCHEM.COMPOUND:225609
fludrocortisone:
https://arax.ncats.io/test/?term=PUBCHEM.COMPOUND:31378

@dkoslicki - is there a corresponding NCATSTranslator/Feedback issue we need to close?

**Comment by amykglen** [comment] 2023-05-25 23:01
I posted a comment in https://github.com/NCATSTranslator/Feedback/issues/145 letting them know this conflation is fixed - closing

**Closed by amykglen** 2023-05-25 23:01 UTC
Labels: bug, node synonymizer, verify in next deployment, conflation
