### ISSUE TITLE
Mysterious resultify error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#731] opened 2020-05-01 18:51 UTC
Input:
```
 elif params.example_number == 2018211470:  # Trung's query: https://github.com/NCATSTranslator/Relay/blob/master/tr_sys/tr_ars/ars_query.json
        # no reasoning
        query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=MONDO:0005737, id=n0, type=disease)",
            "add_qnode(type=protein, id=n1)",
            "add_qnode(type=disease, id=n2)",
            "add_qedge(source_id=n0, target_id=n1, id=e0)",
            "add_qedge(source_id=n1, target_id=n2, id=e1)",
            "expand(edge_id=[e0,e1], kp=ARAX/KG2)",
            "resultify()",
            "return(message=true, store=false)"
```

Last bit of the result:
```
2020-05-01 10:55:53.288574 DEBUG: Merging results into Message.KnowledgeGraph
  - 2020-05-01 10:55:53.288845 INFO: After Expand, Message.KnowledgeGraph has 54 nodes and 100 edges
  - 2020-05-01 10:55:53.288883 INFO: Processing action 'resultify' with parameters {'': 'true'}
  - 2020-05-01 10:55:53.288982 ERROR: 'MONDO:0005737'
  - 2020-05-01 10:55:53.288993 DEBUG: Applying Resultifier to Message with parameters {'': 'true'}
```

High prio since this is (like) the query that Trung wants to hit ARAX with. Assigning multiple people in case they have any input.

**Comment by dkoslicki** [comment] 2020-05-01 18:56
Clarifying: high prio as in "within the next week or so"

**Comment by dkoslicki** [comment] 2020-05-01 18:59
Error is being thrown in [this line](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_resultify.py#L200)

**Comment by dkoslicki** [comment] 2020-05-01 19:46
@amykglen if you want to look into this, the debug and example commands are on the branch `731` as noted in 2d10de1.

Looks like the synonyms are just not showing up in the KG:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=MONDO:0005737, id=n0, type=disease)",
            "add_qnode(type=protein, id=n1)",
            "add_qedge(source_id=n0, target_id=n1, id=e0)",
            "expand(edge_id=[e0], kp=ARAX/KG2)",
            "return(message=true, store=true)"
```
Gives KG nodes of:
```
[x.id for x in message.knowledge_graph.nodes]
Out[5]: 
['UniProtKB:P49591',
 'UniProtKB:P43626',
 'UniProtKB:P43627',
 'UniProtKB:P43628',
 'UniProtKB:Q99706',
 'UniProtKB:Q8N109',
 'UniProtKB:Q8NHK3',
 'UniProtKB:Q14954',
 'UniProtKB:P43631',
 'UniProtKB:Q14952',
 'UniProtKB:P43632',
 'UniProtKB:Q14953',
 'UniProtKB:P43629',
 'UniProtKB:P43630',
 'UniProtKB:Q8N743',
 'UniProtKB:Q14943',
 'UniProtKB:P61573',
 'UniProtKB:O15118',
 'UniProtKB:A8MWS1']
```
while:
```
INFO: Expanding edge e0 using ARAX/KG2
  - 2020-05-01 12:37:00.776708 DEBUG: Looking for query nodes to use curie synonyms for
  - 2020-05-01 12:37:00.776947 INFO: Using equivalent curies for node MONDO:0005737:
 ['CHV:0000027699', 'MEDDRA:10055245', 'NCIT:C36171', 'EFO:0007243', 'Orphanet:319218', 'MONDO:0005737', 'DOID:4325']
```

**Comment by dkoslicki** [comment] 2020-05-01 20:13
@amykglen Looks like the problem is [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/kg_querier.py#L171-L175) in `kg_querier.py`:
```
if synonym_handling == 'map_back' and qnode_id in synonym_usages_dict:
# Only keep the node corresponding to the original curie (discard synonym nodes)
original_curie = synonym_usages_dict[qnode_id].get('original_curie')
if swagger_node.id == original_curie:
    self.final_kg['nodes'][swagger_node.id] = swagger_node
```
As sometimes the `original_curie` doesn't actually get returned in the `results_table`

**Comment by dkoslicki** [comment] 2020-05-01 20:15
@amykglen use `python ARAX_query.py 2018211470` to reproduce the problem I'm talking about in a049342a.

Btw, you may want to do your fixes in the `expander` branch as the `731` branch is just for showing stuff (and will be deleted after you apply the fixes)

**Comment by saramsey** [comment] 2020-05-04 04:03
thank you @dkoslicki for the excellent deep-dive on this issue

**Comment by saramsey** [comment] 2020-05-04 04:07
I understand from @dkoslicki 's description that resultify is being called and there is a qnode with a fixed CURIE (in this case, `MONDO:0005737`) and there is no node in the KG with that CURIE. So, it seems correct that resultify is throwing an error (although it should maybe validate for this at a higher level and throw a ValueError).

**Comment by edeutsch** [comment] 2020-05-04 04:26
I recommend an informative error message written to the response log and graceful early return rather than throwing errors.

**Comment by saramsey** [comment] 2020-05-04 04:51
In branch master, I have added a test function `_test_issue731` to the module `ARAX_resultify.py` that triggers this exact issue.  I've also modified the code in `_make_adj_maps` to catch the `KeyError` and throw a `ValueError` with a more informative message. Please LMK if you feel that this is not the expected behavior for resultify. It seems to me that passing a KG containing an edge that refers to a node that is not in the graph, is incorrect input to resultify, and thus raising a `ValueError` seems reasonable to me.

**Comment by saramsey** [comment] 2020-05-04 04:57
> I recommend an informative error message written to the response log and graceful early return rather than throwing errors.

The internal function `_get_results_for_kg_by_qg` has no ability to write to the response log, since it is not a class method but a static function of the module. Following the usual python idiom, it throws a `ValueError` with an informative error message, which in the normal course of calling resultify in the production system (in non-debug mode) is caught in the class method `_resultify` and the error message is added to the ARAX message log. 

In module-level isolation testing and debugging, the stack backtrace is much more helpful to me and thus the behavior of the `_get_results_for_kg_by_qg` function is helpful and preferred. 

Please let me know if you feel this is not a satisfactory explanation.

**Comment by edeutsch** [comment] 2020-05-04 05:11
Sure, as long as resultify() writes a nice error message to the log and returns gracefully, then all is good. However it works internally is fine.

**Comment by dkoslicki** [comment] 2020-05-05 18:31
> @amykglen use `python ARAX_query.py 2018211470` to reproduce the problem I'm talking about in [a049342](https://github.com/RTXteam/RTX/commit/a049342a5960e224aeb218922966c7da3c275ec2).
> 
> Btw, you may want to do your fixes in the `expander` branch as the `731` branch is just for showing stuff (and will be deleted after you apply the fixes)

@amykglen just making sure you saw this part, as the problem appears to be in `expand` and not `resultify`. `resultify` is properly complaining that the KG doesn't contain a node requested by the QG due to the synonymizing issue

**Comment by amykglen** [comment] 2020-05-05 18:47
yep, thanks @dkoslicki - and thanks for pinpointing where the bug is in `expand`. expect to have it fixed today!

**Comment by amykglen** [comment] 2020-05-05 23:06
Ok -  fixed in the `expander` branch.

**Comment by dkoslicki** [comment] 2020-05-05 23:29
Thanks @amykglen! Do you mind merging to master if you feel it's tested enough?

@edeutsch once it's merged, do you mind rolling it out to beta? That way I can follow up on Trung's request (this was (one of) the blocking issue(s)).

**Comment by edeutsch** [comment] 2020-05-05 23:32
sure thing. I don't see commit messages, so let me know and I'll roll em!

**Comment by amykglen** [comment] 2020-05-05 23:54
Cool - yep, just merged it into master!

**Comment by edeutsch** [comment] 2020-05-06 00:00
master rolled out to /test and /beta, please test it!

**Comment by amykglen** [comment] 2020-05-06 00:38
Tried the original query on beta, and it runs without error, though the results look a little strange https://arax.rtx.ai/beta/?m=1848

```
add_qnode(name=MONDO:0005737, id=n0, type=disease)
add_qnode(type=protein, id=n1)
add_qnode(type=disease, id=n2)
add_qedge(source_id=n0, target_id=n1, id=e0)
add_qedge(source_id=n1, target_id=n2, id=e1)
expand(edge_id=[e0,e1], kp=ARAX/KG2)
resultify()
```

<img width="1069" alt="Screen Shot 2020-05-05 at 5 34 46 PM" src="https://user-images.githubusercontent.com/49423686/81128729-d7181480-8ef6-11ea-8a26-29bb15f732a3.png">

And it seems like there are too many results? It returns 665, though the knowledge graph contains only 55 nodes and 100 edges.

**Comment by amykglen** [comment] 2020-05-06 15:44
May be worth noting that if I add `is_set=true` to qnode n2, things seem to process fine (resultify produces 35 results that seem to make sense: https://arax.rtx.ai/beta/?m=1852)

**Comment by edeutsch** [comment] 2020-05-06 16:25
I've been pondering a philosophical question: is it ever sensible for an intermediate node *not* to be treated as is_set=true? Maybe we don't need to explicitly make users set this flag in the query_graph because maybe it should always be the case?

Hypothesis: for a query_graph that has two end nodes and N number of intermediate nodes, all intermediate nodes should always be treated as is_set=true. (I suppose if an intermediate nodes has a curie, then in wouldn't need to be treated as a set, but it also wouldn't harm either)

In the above example from Amy, I think the results may be correct. In the absence of is_set=true, the results are essentially all possible paths, which is 665. While, with is_set=true, the paths are coalesced by intermediate sets and only yield 35. The code is probably working as designed. I suppose both these results are potentially valid. But maybe the default for intermediate nodes should be is_set=true rather than is_set=false, since the most likely thing the user wants is to treat intermediate nodes as sets.

**Comment by amykglen** [comment] 2020-05-06 22:37
+1 for making `is_set=true` the default for intermediate nodes!

so is it correct that when `is_set=true` is not used in the [above query](https://github.com/RTXteam/RTX/issues/731#issuecomment-624380615), there should be results with orphaned nodes? (like the one in the screenshot I shared). or is that a bug?

**Comment by edeutsch** [comment] 2020-05-06 23:14
No, there should not be orphaned nodes. All results should be 3 nodes in a row that represent all possible paths from the start node to all the end nodes. Might well be 665. But sounds like the results are not quite right.

**Comment by amykglen** [comment] 2020-05-07 16:26
Ok - I'll assign @saramsey again then.

**Comment by edeutsch** [comment] 2020-05-07 16:46
Could possibly be a rendering problem? Have you checked if maybe the results are right, but the GUI is choking on it? (not implying that you need to, just wondering if you did)

**Comment by saramsey** [comment] 2020-05-07 16:52
OK, I can take a look at this next week. What's the timeline on when a fix is needed?

**Comment by amykglen** [comment] 2020-05-07 16:54
> Could possibly be a rendering problem? Have you checked if maybe the results are right, but the GUI is choking on it? (not implying that you need to, just wondering if you did)

Just checked: it does appear to be a problem in resultify and not in rendering - this result, for example, is missing a binding for edge `e1` (like the screenshot I shared):
```
{'confidence': None,
 'description': 'No description available',
 'edge_bindings': [{'kg_id': 'UniProtKB:Q8NHK3--associated_with--MONDO:0005737',
                    'qg_id': 'e0'}],
 'essence': 'brucellosis',
 'essence_type': 'disease',
 'id': None,
 'node_bindings': [{'kg_id': 'MONDO:0005737', 'qg_id': 'n0'},
                   {'kg_id': 'UniProtKB:Q8NHK3', 'qg_id': 'n1'},
                   {'kg_id': 'DOID:11077', 'qg_id': 'n2'}],
```

**Comment by edeutsch** [comment] 2020-05-07 16:58
Thanks, @amykglen !

@saramsey, this is not very high priority as far as I'm concerned. This only seems to happen with is_set=false, which I don't think is that useful to the user. So, not as high a priority as other things IMO.

**Comment by saramsey** [comment] 2020-05-11 04:48
> +1 for making `is_set=true` the default for intermediate nodes!
> 
> so is it correct that when `is_set=true` is not used in the [above query](https://github.com/RTXteam/RTX/issues/731#issuecomment-624380615), there should be results with orphaned nodes? (like the one in the screenshot I shared). or is that a bug?

For an arbitrary query graph, how precisely do we determine that a node is an intermediate node?

**Comment by edeutsch** [comment] 2020-05-11 06:04
yes, I would define intermediate node as a node with two or more edges.

Come to think of it, I wonder how my code would react if even end-nodes has two edges because there were multiple edges between all nodes. Anyway, I am mostly concerned about relatively simple cases for now.

I added some code in the QueryGraphInfo component that forces all intermediate nodes to have is_set=true. I'm not certain this is good long-term behavior and something we should ponder over the next coming months, but I think it will prevent some degree of huge result sets for now.

**Comment by saramsey** [comment] 2020-05-13 04:29
> > Could possibly be a rendering problem? Have you checked if maybe the results are right, but the GUI is choking on it? (not implying that you need to, just wondering if you did)
> 
> Just checked: it does appear to be a problem in resultify and not in rendering - this result, for example, is missing a binding for edge `e1` (like the screenshot I shared):
> 
> ```
> {'confidence': None,
>  'description': 'No description available',
>  'edge_bindings': [{'kg_id': 'UniProtKB:Q8NHK3--associated_with--MONDO:0005737',
>                     'qg_id': 'e0'}],
>  'essence': 'brucellosis',
>  'essence_type': 'disease',
>  'id': None,
>  'node_bindings': [{'kg_id': 'MONDO:0005737', 'qg_id': 'n0'},
>                    {'kg_id': 'UniProtKB:Q8NHK3', 'qg_id': 'n1'},
>                    {'kg_id': 'DOID:11077', 'qg_id': 'n2'}],
> ```

I will refer to this as 731b. I am pausing work on 731b until I can sort out #736.

**Comment by saramsey** [comment] 2020-05-13 04:34
> > +1 for making `is_set=true` the default for intermediate nodes!
> 
> I am open to this idea, but for an arbitrary query graph, how precisely do we determine that a node is an intermediate node? It has two or more edges attached to it?
> 
> Also @amykglen would you mind making this a new issue so we can discuss it there? Thank you!

Hi all, please use #737 for further discussion of making is_set=TRUE by default for intermediate nodes

**Comment by saramsey** [comment] 2020-05-13 04:36
> yes, I would define intermediate node as a node with two or more edges.
> 
> Come to think of it, I wonder how my code would react if even end-nodes has two edges because there were multiple edges between all nodes. Anyway, I am mostly concerned about relatively simple cases for now.
> 
> I added some code in the QueryGraphInfo component that forces all intermediate nodes to have is_set=true. I'm not certain this is good long-term behavior and something we should ponder over the next coming months, but I think it will prevent some degree of huge result sets for now.

Hi @edeutsch what if the user specifies `is_set=false` in the DSL, like this?
```
add_qnode(id=n00)
add_qnode(id=n01, is_set=false)
add_qnode(id=n02)
add_qedge(source=n00, target=n01)
add_qedge(source=n01, target=n02)
```
does the updated code now override it?

**Comment by edeutsch** [comment] 2020-05-13 04:50
yes, I believe it does. I'm not happy with that. But Mark and Trung are actively sending ARAX queries, and with this "fix", reasonable results are returned. Without that "fix" the results are blowing up. So that's the bandaid for the moment until we can think deeply about what the expected behavior should be.

I briefly tried only setting it to true if it was not specified. But it seems that there is no difference between null and false in a Boolean, so it seems I can't tell the difference between these two. At least in the brief fiddling that I did.

**Comment by saramsey** [comment] 2020-05-14 05:04
> yes, I believe it does. I'm not happy with that. But Mark and Trung are actively sending ARAX queries, and with this "fix", reasonable results are returned. Without that "fix" the results are blowing up. So that's the bandaid for the moment until we can think deeply about what the expected behavior should be.
> 
> I briefly tried only setting it to true if it was not specified. But it seems that there is no difference between null and false in a Boolean, so it seems I can't tell the difference between these two. At least in the brief fiddling that I did.

Thanks for rolling out the fix!  I am still working on issue 731b. It is proving to be a bit tricky.

**Comment by saramsey** [comment] 2020-05-14 21:01
Hi @amykglen can you please try the following test script?
```
#!/usr/bin/env python3

import sys
import os

PACKAGE_PARENT = '../../UI/OpenAPI/python-flask-server'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))
from ARAX_query import ARAXQuery

query = {"previous_message_processing_plan": {"processing_actions": [
    "add_qnode(name=MONDO:0005737, id=n0, type=disease)",
    "add_qnode(type=protein, id=n1)",
    "add_qnode(type=disease, id=n2)",
    "add_qedge(source_id=n0, target_id=n1, id=e0)",
    "add_qedge(source_id=n1, target_id=n2, id=e1)",
    "expand(edge_id=[e0,e1], kp=ARAX/KG2)"]}}
araxq = ARAXQuery()
response = araxq.query(query)
message = araxq.message

kg = message.knowledge_graph
ids_want = {'MONDO:0005737', 'UniProtKB:Q8NHK3', 'DOID:11077'}
edges = [edge for edge in kg.edges if edge.source_id in ids_want and edge.target_id in ids_want]
print("The number of edges connecting nodes in the desired set is: " 
         + str(len(edges)))

print(edges[0])
```
It should generate the following output:
```
The number of edges connecting nodes in the desired set is: 1
{'confidence': None,
 'defined_datetime': None,
 'edge_attributes': [{'name': 'relation_curie',
                      'type': None,
                      'url': None,
                      'value': 'RTXKG1:gene_associated_with_condition'},
                     {'name': 'simplified_relation_curie',
                      'type': None,
                      'url': None,
                      'value': 'Biolink:gene_associated_with_condition'},
                     {'name': 'simplified_relation',
                      'type': None,
                      'url': None,
                      'value': 'http://w3id.org/biolink/vocab/associatedWith'},
                     {'name': 'edge_label',
                      'type': None,
                      'url': None,
                      'value': 'gene_associated_with_condition'}],
 'evidence_type': None,
 'id': 'UniProtKB:Q8NHK3--associated_with--MONDO:0005737',
 'is_defined_by': 'ARAX/KG2',
 'negated': False,
 'provided_by': ['http://www.disgenet.org'],
 'publications': [],
 'qedge_id': 'e0',
 'qualifiers': None,
 'relation': 'http://arax.rtx.ai/geneAssociatedWithCondition',
 'source_id': 'UniProtKB:Q8NHK3',
 'target_id': 'MONDO:0005737',
 'type': 'associated_with',
 'weight': None}
```
To me, this (and other testing that I have done, for example with the triple `{'MONDO:0005737', 'UniProtKB:P43629', 'DOID:11077'}`) suggests that there is no edge between `UniProtKB:Q8NHK3` and `DOID:11077` (and also no edge between `UniProtKB:P43629`  and `DOID:11077`) in the KG that is being passed to resultify. Thus I am starting to wonder if resultify is behaving as expected?

**Comment by saramsey** [comment] 2020-05-14 21:06
I forgot to add, the above script is intended to be run in the master branch code and in the subdirectory `RTX/code/ARAX/ARAXQuery`.

**Comment by saramsey** [comment] 2020-05-14 21:19
The same result happens if I run the test script with the triple `{'MONDO:0005737', 'UniProtKB:Q14943', 'DOID:9970'}` which I think is the triple that is shown in the screen capture that @amykglen posted:
```
The number of edges connecting nodes in the desired set is: 1
{'confidence': None,
 'defined_datetime': None,
 'edge_attributes': [{'name': 'relation_curie',
                      'type': None,
                      'url': None,
                      'value': 'RTXKG1:gene_associated_with_condition'},
                     {'name': 'simplified_relation_curie',
                      'type': None,
                      'url': None,
                      'value': 'Biolink:gene_associated_with_condition'},
                     {'name': 'simplified_relation',
                      'type': None,
                      'url': None,
                      'value': 'http://w3id.org/biolink/vocab/associatedWith'},
                     {'name': 'edge_label',
                      'type': None,
                      'url': None,
                      'value': 'gene_associated_with_condition'}],
 'evidence_type': None,
 'id': 'UniProtKB:Q14943--associated_with--MONDO:0005737',
 'is_defined_by': 'ARAX/KG2',
 'negated': False,
 'provided_by': ['http://www.disgenet.org'],
 'publications': [],
 'qedge_id': 'e0',
 'qualifiers': None,
 'relation': 'http://arax.rtx.ai/geneAssociatedWithCondition',
 'source_id': 'UniProtKB:Q14943',
 'target_id': 'MONDO:0005737',
 'type': 'associated_with',
 'weight': None}
```

**Comment by saramsey** [comment] 2020-05-14 21:26
OK, I see the bug. This appears to be a bug in resultify. There are 81 edges in the KG that match `e1` so it is unclear why resultify is returning result subgraphs that fail to cover the `e1` edge. I think I need to add some filtering code.

**Comment by saramsey** [comment] 2020-05-14 23:50
Here is a MWE test case (in `ARAX_resultify.py`) that reproduces this bug:
```
def _test_issue731c():
    qg = QueryGraph(nodes=[QNode(curie='MONDO:0005737',
                                 id='n0',
                                 type='disease'),
                           QNode(id='n1',
                                 type='protein'),
                           QNode(id='n2',
                                 type='disease')],
                    edges=[QEdge(source_id='n0',
                                 target_id='n1',
                                 id='e0'),
                           QEdge(source_id='n1',
                                 target_id='n2',
                                 id='e1')])
    kg = KnowledgeGraph(nodes=[Node(id='MONDO:0005737',
                                    type='disease',
                                    qnode_id='n0'),
                               Node(id='UniProtKB:Q14943',
                                    type='protein',
                                    qnode_id='n1'),
                               Node(id='DOID:12297',
                                    type='disease',
                                    qnode_id='n2'),
                               Node(id='DOID:11077',
                                    type='disease',
                                    qnode_id='n2')],
                        edges=[Edge(source_id='MONDO:0005737',
                                    target_id='UniProtKB:Q14943',
                                    qedge_id='e0'),
                               Edge(source_id='UniProtKB:Q14943',
                                    target_id='DOID:12297',
                                    qedge_id='e1')])
    results = _get_results_for_kg_by_qg(kg, qg)
    indexes_results_with_single_edge = [index for index, result in enumerate(results) if len(result.result_graph.edges) == 1]
    assert len(indexes_results_with_single_edge) == 0
```

**Comment by saramsey** [comment] 2020-05-15 00:13
OK @amykglen I have just pushed a fix. Can you please test it?

**Comment by saramsey** [comment] 2020-05-15 00:17
Just confirming:  all my test functions in `ARAX_resultify.py` are now passing (except the demo "example3" test which takes forever so I commented it out).

**Comment by amykglen** [comment] 2020-05-15 00:36
Awesome - yep, just tested it out and it seems to be working great! (Confirmed no edge bindings are missing, and the number of results make much more sense now - 81 when `is_set=false`, 35 when `is_set=true` for the original query.)

**Comment by amykglen** [comment] 2020-05-15 00:47
So this will just need to be rolled out to production, and then I can confirm it's working there.

**Comment by edeutsch** [comment] 2020-05-15 00:55
I have just rolled out master to "test", i.e. https://arax.rtx.ai/test/
Is that a good place for testing or shall I go all the way around to production right away?

**Comment by amykglen** [comment] 2020-05-15 00:56
nope, that sounds good - I'll try it out there

**Comment by amykglen** [comment] 2020-05-15 01:00
looks good on /test! the query produces 81 results, with no orphan nodes https://arax.rtx.ai/test/?m=2030
```
add_qnode(name=MONDO:0005737, id=n0, type=disease)
add_qnode(type=protein, id=n1)
add_qnode(type=disease, id=n2)
add_qedge(source_id=n0, target_id=n1, id=e0)
add_qedge(source_id=n1, target_id=n2, id=e1)
expand(edge_id=[e0,e1], kp=ARAX/KG2)
resultify()
```

**Comment by edeutsch** [comment] 2020-05-15 01:05
okay, latest master is rolled out to production, beta, and test!

**Comment by amykglen** [comment] 2020-05-15 01:21
awesome, thanks!

**Closed** 2020-05-15 01:22 UTC
Labels: bug, high priority, need to test on production
