### ISSUE TITLE
DGIdb NCI

### ISSUE THREAD

**Issue by BluePiggy49** [RTXteam/RTX#449] opened 2019-07-26 23:39 UTC
Hi Steve,
I looked into the GitHub issue (#434) on the DGIdb interactions that could not be mapped. I found that most of the unmapped interactions are from the same source, so you would potentially only have to ETL the NCI Thesaurus to bring in most of the nodes. The NCI Thesaurus has ChEBI IDs, UMLS CUIs, and NCI Thesaurus codes for many of their subjects. If you are looking to add in TdgClinicalTrial as well, there is much less information out there, but I found a table of their data here, https://www.annualreviews.org/doi/suppl/10.1146/annurev-pharmtox-011613-135943 , that could be helpful. Here are the number are unmapped interactions by source:

Source : Number of Unmapped Interactions
NCI : 1898
TdgClinicalTrial : 931
CKB : 550
CIViC : 115
MyCancerGenome : 81
ClearityFoundationClinicalTrial : 61
CGI : 61
TALC : 55
TEND : 29
OncoKB : 28
ClearityFoundationsBiomarkers : 15
FDA : 12
MyCancerGenomeClinicalTrial : 6
CancerCommons : 5
DoCM : 4
ChemblInteractions : 1

In case you are curious, I've attached my code and the dgidb_tsv_to_kg_json.py log.

Thank you,
Erica Wood

**Comment by saramsey** [comment] 2019-08-01 18:09
Given that we have six weeks until the hackathon, I'm going to mark this as Low Priority.  I think we should focus on getting KG2 into Neo4j and then on figuring out how to do some reasoning in it, for the next six weeks.

**Comment by saramsey** [comment] 2019-08-01 18:10
Should have added -- it is still a very good idea.

**Comment by saramsey** [comment] 2019-08-15 18:48
duplicate of #449

**Closed by saramsey** 2019-08-15 18:48 UTC
Labels: kg2, low priority, question
