### ISSUE TITLE
Add attributes[] property to /meta_knowledge_graph

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1617] opened 2021-08-18 20:15 UTC
As mentioned in issue #1613

**Comment by amykglen** [comment] 2021-08-18 22:29
relevant documentation about `MetaAttribute`s is here: https://github.com/NCATSTranslator/ReasonerAPI/blob/v1.2/docs/reference.md#metaattribute-

so it looks like `MetaNode`s and `MetaEdge`s each can have a list of `MetaAttribute`s now.

realized - currently our `MetaKnowledgeGraph` doesn't contain any Overlay `MetaEdge`s like for biolink:has_normalized_google_distance_with, and etc. should it? I suppose such `MetaEdge`s would only belong in ARAX's `MetaKnowledgeGraph`, and not KG2's. without them I don't think we have anywhere to add `MetaAttributes` for Overlay.

that makes me wonder though - what is even supposed to be in an ARA's (vs. KP's) `MetaKnowledgeGraph`? are ARAs supposed to grab the `MetaKnowledgeGraph`s of all of their KPs, merge them, and add in any additional `MetaAttributes` as applicable? right now I believe ARAX's `MetaKnowledgeGraph` is the same as KG2's.

**Comment by edeutsch** [comment] 2021-08-19 05:40
Good question. I vaguely think this was already discussed, but I don't recall the result. I will ask at the TRAPI call to see if anyone knows about the policy.

Would it be relatively straightforward for us to build a merged MKG from all our KPs?

**Comment by amykglen** [comment] 2021-08-19 17:08
sounds good! yes, I think it should be relatively straightforward (assuming all of the KPs' endpoints are up when we're trying to build our merged MKG 🙂)

**Comment by edeutsch** [comment] 2021-08-19 20:56
okay, thanks. Probably no action needed yet then. The conversation about what we *should* do translator-wide still needs to happen.

**Comment by amykglen** [comment] 2021-08-30 20:36
from 8/30 minihackathon: Amy will add attributes to KG2 meta KG, no action needed for ARAX meta KG

**Comment by amykglen** [comment] 2021-09-23 17:24
confirmed that these are appearing in the KG2.7.3 metaKG:

```
    {
      "attributes": [
        {
          "attribute_source": "infores:rtx-kg2",
          "attribute_type_id": "biolink:knowledge_source"
        },
        {
          "attribute_source": "infores:rtx-kg2",
          "attribute_type_id": "biolink:aggregator_knowledge_source"
        }
      ],
      "object": "biolink:DiseaseOrPhenotypicFeature",
      "predicate": "biolink:in_taxon",
      "subject": "biolink:NucleicAcidEntity"
    },
```

(the `biolink:knowledge_source` attribute captures the upstream sources (e.g., semmeddb), while the `biolink:aggregator_knowledge_source` is the attribute we create that says this edge came from KG2)

realizing I neglected to specify `constraint_use: false` for these two attributes... though technically that field is optional.

**Comment by edeutsch** [comment] 2021-09-23 17:35
thanks!
fine to close AFAIC

**Closed** 2021-09-23 17:38 UTC
Labels: kg2c, confirm in next kg2c build
