### ISSUE TITLE
Sometimes first answer doesn't auto-open

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#148] opened 2018-05-16 21:00 UTC
@isbluis , sometimes on the "first time" I run a question an rtx instance via the web UI, the first answer doesn't auto-open. First time after what? I'm not sure. I've seen this several times, on different computers, perhaps always of Firefox. I have no specific repro. The first 3 times I saw it, I didn't report it. Now I've seen it a 4th time and I'm reporting it.

Basically, the auto-open-the-first answer systems doesn't work 100% of the time. But I'm hard pressed to explain the exact circumstances. Seems like it is the first time a site is accessed after a while.

**Comment by isbluis** [comment] 2018-05-17 00:59
Odd one.  I have not encountered it, but will keep looking and inspect the code for a possible cause.  Will be hard to test if can't be reproduced reliably.

**Comment by edeutsch** [comment] 2018-05-17 04:16
So it just happened again. On Firefox. in test/. immediately after rolling out new code and restarting flask. I also did a SHIFT+RELOAD in case there was new HTML or JavaScript. I ran the first Q0. The answer came back with one result. But it was closed. So I opened it manually. Another weird thing. No feedback was visible! Result id was indeed 1:
  "result_list": [
    {
      "confidence": 1,
      "id": "http://rtx.ncats.io/api/rtx/v1/result/1",

Down in the JSON area I see this:
================================================================= FEEDBACK::

[
  {
    "comment": "This is a great result because...",
    "commenter_id": 1,
    "datetime": "2018-05-15T21:18:20Z",
    "expertise_level_id": 3,
    "id": "http://rtx.ncats.io/api/rtx/v1/result/1/feedback/1",
    "rating_id": 2,
    "result_id": "http://rtx.ncats.io/api/rtx/v1/result/1"
  },
  {
    "comment": "Looks good to me",
    "commenter_id": 1,
    "datetime": "2018-05-16T19:37:34Z",
    "expertise_level_id": 2,
    "id": "http://rtx.ncats.io/api/rtx/v1/result/1/feedback/3",
    "rating_id": 2,
    "result_id": "http://rtx.ncats.io/api/rtx/v1/result/1"
  },
  {
    "comment": "",
    "commenter_id": 1,

So, it is receiving the feedback JSON, but not showing it. maybe related?

Aha! I just reproed it! It seems to be the SHIFT-RELOAD, which I do periodically on my browser to ensure no old stuff it cached. Try doing a SHIFT+RELOAD and see if you can repro.

**Comment by dkoslicki** [comment] 2018-05-17 06:02
Just my $0.02: I've noticed the same thing (on the main site and the /devXX and /test sites). Using Chrome

**Comment by edeutsch** [comment] 2018-08-11 02:41
@isbluis, I haven't seen this bug manifest itself in a while. has this bug been officially squashed? Can we close?

**Comment by isbluis** [comment] 2018-08-21 02:10
Have not observed it since the Hackathon, or received reports thereof.  I'll close it.

**Closed by isbluis** 2018-08-21 02:10 UTC
