### ISSUE TITLE
Wrong resource_id?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2109] opened 2023-08-20 20:20 UTC
From Andy: why is the `resource_id` given as `infores:rtx-kg2` and not `infores:arax` for the results from https://arax.ncats.io/?r=159664

Relevant part of the response:
```
{
                "analyses": [
                    {
                        "attributes": null,
                        "edge_bindings": {
                            "t_edge": [
                                {
                                    "attributes": null,
                                    "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:drugcentral"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:repodb"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:chembl"
                                },
                                {
                                    "attributes": null,
                                    "id": "creative_DTD_prediction_0"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:molepro:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:chembl"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:automat-robokop:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:drugcentral"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:spoke:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:chembl"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:molepro:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:drugcentral"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:automat-drug-central:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:drugcentral"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:service-provider-trapi:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:drugcentral"
                                },
                                {
                                    "attributes": null,
                                    "id": "infores:service-provider-trapi:PUBCHEM.COMPOUND:124087--biolink:treats--None--None--None--MONDO:0005709--infores:chembl"
                                }
                            ]
                        },
                        "resource_id": "infores:rtx-kg2",  #<----- why rtx-kg2 and not arax?
                        "score": 0.9856886860581948,
                        "scoring_method": null,
                        "support_graphs": [
                            "aux_graph_N1_150"
                        ]
                    }
                ],
                "confidence": null,
                "description": "No description available",
                "essence": "Desloratadine",
                "essence_category": "['biolink:Drug', 'biolink:SmallMolecule']",
                "id": null,
                "node_bindings": {
                    "on": [
                        {
                            "attributes": null,
                            "id": "MONDO:0005709",
                            "query_id": null
                        }
                    ],
                    "sn": [
                        {
                            "attributes": null,
                            "id": "PUBCHEM.COMPOUND:124087",
                            "query_id": null
                        }
                    ]
                },
                "normalized_score": 100.0,
                "resource_id": "ARAX",  #<---- not in the form infores:arax
                "result_group": null,
                "result_group_similarity_score": null,
                "row_data": [
                    0.986,
                    "Desloratadine",
                    "['biolink:Drug', 'biolink:SmallMolecule']"
                ],
                "score": null,
                "score_direction": null,
                "score_name": null
            }
```
Tagging Eric and Steve for their inputs. Kevin could probably implement the solution as needed (once it's confirmed)

**Comment by edeutsch** [comment] 2023-08-21 04:43
Indeed all of the analysis resource_ids coming out of ARAX should be tagged "infores:arax" like they are in results here:
```
    "results": [
      {
        "analyses": [
          {
            "attributes": null,
            "edge_bindings": {
              "e00": [
                {
                  "attributes": null,
                  "id": "infores:rtx-kg2:MESH:D011451--biolink:physically_interacts_with--None--None--None--PUBCHEM.COMPOUND:1983--infores:semmeddb"
                },
                {
                  "attributes": null,
                  "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:1983--biolink:physically_interacts_with--None--None--None--MESH:D011451--infores:semmeddb"
                }
              ]
            },
            "resource_id": "infores:arax",
            "score": 1,
            "scoring_method": null,
            "support_graphs": [
              "aux_graph_N1_63"
            ]
          }
        ],
```
in https://arax.ci.transltr.io/?r=159847

I was not aware that they are sometimes not.

**Comment by dkoslicki** [comment] 2023-08-21 15:17
@kvnthomas98 Do you have any insight on why `infores:arax` is sometimes not there, and how to fix it?

**Comment by kvnthomas98** [comment] 2023-08-21 20:21
Hi @dkoslicki , 
I think on arax.ncats.io. It is referring to an older version of the code as I am not able to recreate the issue of infores:rtx-kg2 being present inside the Analysis Object.
Please see the https://arax.ci.transltr.io/?r=159966. I was not able to recreate the issue on arax.ncats.io/beta as well.

<img width="552" alt="image" src="https://github.com/RTXteam/RTX/assets/17030839/400b4a3e-0418-4868-974f-b1c1e270e823">

With regards to the resource_id being to "ARAX" for each result(not analysis). It is caused by https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query.py#L887 and the fix is pretty simple. Should I push the fix to master?

**Comment by dkoslicki** [comment] 2023-08-21 21:23
Ah, I see! So I'll report to Andy that it should already be fixed.

And yes, please do fix the ARAX->"infores:arax" part

**Comment by saramsey** [comment] 2023-08-21 22:02
Thank you @kvnthomas98 for your detective work on this one.

**Comment by saramsey** [comment] 2023-08-22 04:25
Unassigning myself for this one since it seems like it's already fixed. Thanks all!

**Comment by dkoslicki** [comment] 2023-08-23 12:12
Good to close @kvnthomas98 ?

**Comment by kvnthomas98** [comment] 2023-08-25 15:21
Code has been merged to master. So closing it.

**Closed by kvnthomas98** 2023-08-25 15:21 UTC
