### ISSUE TITLE
Incorrect synonym

### ISSUE THREAD

**Issue by Genomewide** [RTXteam/RTX#1811] opened 2022-03-14 02:12 UTC
Methylglycol - CHEMBL.COMPOUND:CHEMBL170721. The equivalent identifiers include a number of gene IDs through the ARAX interface using their synonym function.

Link to synonym look up: http://arax.ncats.io/?term=CHEMBL.COMPOUND:CHEMBL170721  
 
I looked at the publication https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5932893/ and I don’t see either thing. So, I am not sure what to recommend for the fix either.  

**I am not sure that this is always true, but it would be interesting to see how many terms have the biolink category for things that should not overlap (e.g. drugs and genes).** 

-Andy Crouse (Unsecret agent and UI team)

**Comment by dkoslicki** [comment] 2022-03-14 14:58
Might be due to us using an old version of the SRI NN? I don't know when we've updated it last

**Comment by finnagin** [comment] 2022-03-14 17:58
@edeutsch do you know if we use a local version of the SRI node normalizer or do we use the api?

**Comment by finnagin** [comment] 2022-03-14 21:46
Looks like we do get the data [from the api but we cache it.](https://github.com/RTXteam/RTX/blob/2440ad0565398421f33c8fc17e8503ef958b4068/code/ARAX/NodeSynonymizer/sri_node_normalizer.py#L52-L58) So maybe if we refresh the cache we don't see this issue. 

@edeutsch if I were to backup and remove the file `sri_node_normalizer_curie_cache.pickle` would the node synonymizer automatically download a fresh cache and recreate that file or do I need to do it manually?

**Comment by edeutsch** [comment] 2022-03-15 12:46
You can remove both the pickle file and the sqlite file and then rerun the sri_node_normalizer.py with --build to re-create what you need with the latest data.

**Comment by edeutsch** [comment] 2022-03-15 12:51
Note that the sri_node_normalizer database is only used during the building of our node_synonymizer database. So just rebuilding the sri_node_normalizer database won't have any effect until you rebuild the node_synonymizer database.

**Comment by finnagin** [comment] 2022-03-15 18:20
Ah I see. Thanks! 

Since we are currently rebuilding the node synonymizer as part of #1810 looks like this may be solved when we roll out KG2.7.5. Should we just wait for that then?

**Comment by dkoslicki** [comment] 2022-06-05 18:41
Check to see if the node normalizer has been refreshed and see if this is still being conflated with a Gene

**Comment by amykglen** [comment] 2023-05-03 22:29
this appears fixed in our overhauled synonymizer (#2003) - it's not quite deployed but should be later this week (to dev):

Cluster for CHEMBL.COMPOUND:CHEMBL170721 (PUBCHEM.COMPOUND:880) has 14 nodes:

| id                                   | category      | name           | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------------------------|:--------------|:---------------|:---------|:------------|:-----------------|
| CHEBI:17158                          | SmallMolecule | methylglyoxal  | X        | X           |                  |
| CHEMBL.COMPOUND:CHEMBL170721         | SmallMolecule | METHYLGLYOXAL  | X        | X           |                  |
| DRUGBANK:DB03587                     | SmallMolecule | Pyruvaldehyde  | X        | X           |                  |
| GTOPDB:6303                          | SmallMolecule | methylglyoxal  | X        |             |                  |
| HMDB:HMDB0001167                     | SmallMolecule | Pyruvaldehyde  | X        | X           |                  |
| INCHIKEY:AIJULSRZWUXGPQ-UHFFFAOYSA-N | SmallMolecule |                | X        |             |                  |
| KEGG.COMPOUND:C00546                 | SmallMolecule | Methylglyoxal  | X        | X           |                  |
| MESH:D011765                         | SmallMolecule | Pyruvaldehyde  | X        | X           |                  |
| PUBCHEM.COMPOUND:880                 | SmallMolecule | Methylglyoxal  | X        |             | X                |
| PathWhiz.Compound:40676              | SmallMolecule | Pyruvoyl group |          | X           |                  |
| PathWhiz.Compound:905                | SmallMolecule | Pyruvaldehyde  |          | X           |                  |
| RXNORM:1373350                       | Drug          | pyruvaldehyde  |          | X           |                  |
| UMLS:C0034338                        | SmallMolecule | pyruvaldehyde  | X        | X           |                  |
| UNII:722KLD7415                      | SmallMolecule | PYRUVALDEHYDE  | X        |             |                  |

**Comment by amykglen** [comment] 2023-05-25 22:37
confirmed fixed on dev/CI instances:

https://arax.ncats.io/devLM/?term=CHEMBL.COMPOUND:CHEMBL170721

(that concept cluster only contains drug-like nodes now; no genes)

and our synonymizer build now has strict rules that prevent it from merging identifiers that have conflicting categories (e.g., gene with drug, disease with gene, etc.)

I'm going to close this issue, but feel free to reopen if you have any concerns, @Genomewide

**Closed by amykglen** 2023-05-25 22:37 UTC
Labels: verify in next deployment, conflation
