### ISSUE TITLE
ARAX returning TRAPI-noncompliant result?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1290] opened 2021-03-12 17:06 UTC
From the BDT Friday stand-up meeting (2021.03.12),

<img width="1441" alt="Screen Shot 2021-03-12 at 9 04 20 AM" src="https://user-images.githubusercontent.com/5562107/110973381-0adf7a00-8312-11eb-98f2-e90c9bfd8471.png">

I think Sarah said that the red "50" means results that are not TRAPI-compliant. Just bringing this up in case it is something fixable that is not currently on the docket to be fixed via another issue (apologies if this already duplicates an in-progress issue; just close it out in that case).

**Comment by edeutsch** [comment] 2021-03-12 17:36
The validator error message is fairly inscrutable but I think the issue is that one of our node or edge attributes has a missing or null "value" field, and that is not permitted. "value" is required. I haven't found the exact instance though.

**Comment by edeutsch** [comment] 2021-03-12 17:47
aha, found it! Looks like our iri attribute is  without a value:
```
      "nodes": {
        "CHEBI:10138": {
          "attributes": [
            {
              "name": "description",
              "type": "biolink:Unknown",
              "value": "[8]-Shogaol belongs to the class of organic compounds known as shogaols. These are ginger derivatives containing a shogaol moiety, which consists of a benzene ring bearing a dec-4-en-3-one moiety, a methoxyphenyl group, a hydroxyl group and at positions 1, 3, and 4, respectively. [8]-Shogaol is considered to be a practically insoluble (in water) and relatively neutral molecule. Within the cell, [8]-shogaol is primarily located in the membrane (predicted from logP). Outside of the human body, [8]-shogaol can be found in ginger. This makes [8]-shogaol a potential biomarker for the consumption of this food product. --- UMLS Semantic Type: UMLS_STY:T121; UMLS Semantic Type: UMLS_STY:T109 --- SHOGAOL; FULL_MW:276.38; MAX_FDA_APPROVAL_PHASE: 0"
            },
            {
              "name": "iri",
              "type": "biolink:IriType",
              "url": "http://purl.obolibrary.org/obo/CHEBI_10138"
            },
```

I suggest that the value of the iri should go in the "value" field instead of the "url" field, which is designed as a "more information to click on for the human user".

@amykglen I think this comes from Expand(). Would you make that change, and then I think we'll be compliant.

**Comment by edeutsch** [comment] 2021-03-12 17:56
and of course any other instances that may be lurking in the code. "value" is a required field. If no value is available, then the whole attribute should be suppressed.

**Comment by amykglen** [comment] 2021-03-12 18:00
ah, yep, makes sense! will do. I believe @isbluis [requested a ways back](https://github.com/RTXteam/RTX/issues/750#issue-620507625) that URLs go in the `url` field - maybe I should put them in _both_ the `url` and `value` of the `Attribute`?

**Comment by edeutsch** [comment] 2021-03-12 18:13
sure, both would be fine with me although redundant. In principle if the type is IriType or some other link of URI type or URL type then that should be rendered as a hyperlink. But fine to just duplicate it for now. This section of the schema is slated to be revised in 1.1 anyway.

**Comment by amykglen** [comment] 2021-03-12 18:17
sounds good - yep, was just going to say the UI could look and see that the `Attribute.type` is `"biolink:IriType"`, but for now I've added such URLs to both the `Attribute.value` and `Attribute.url` fields, so as not to break any of @isbluis's stuff.

fix is in `master`, will need to be rolled out to the KG2 API.

**Comment by amykglen** [comment] 2021-03-23 04:42
think this issue can be closed? (seems to be working well)

**Comment by edeutsch** [comment] 2021-03-23 04:52
agreed. fixed.

**Closed by edeutsch** 2021-03-23 04:52 UTC
Labels: ARAX demo, need to test on production, question
