### ISSUE TITLE
No OMOP ids returned for SNOMEDCT:197358007

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1571] opened 2021-07-13 21:25 UTC
When running this query through expand(kp=COHD) in this [query](https://arax.ncats.io/test/?r=16127) we get the warning `No OMOP concept id was found for source preferred id 'SNOMEDCT:197358007'' with qnode id 'n0'` however SNOMEDCT:197358007 has the OMOP concept id [4059297](https://athena.ohdsi.org/search-terms/terms/4059297).

**Comment by chunyuma** [comment] 2021-07-14 04:39
Hi @finnagin, I rebuilt COHD database and modified the corresponding COHDIndex script so that even though `SNOMEDCT:197358007` has no preferred curie info returned by node synonymizer, it can still query Athena database. Now, However, `SNOMEDCT:197358007 ` can return 4059297. from CODH local database. But it seems like your query still has no return. I'm not sure if `expand` only allows preferred curie to return. I got a warning message:

```
2021-07-14T00:27:57.639238 WARNING: [] NodeSynonymizer did not return canonical info for: {'SNOMEDCT:197358007'}
```

**Comment by saramsey** [comment] 2021-07-14 05:58
Not sure if it is related to this issue, but just an FYI, we have removed SNOMED CT from KG2, because the SNOMED license is not compatible with publicly releasing KG2c. Tagging @ericawood who can elaborate.

**Comment by saramsey** [comment] 2021-07-14 06:01
Is it necessary to use a SNOMED node?  Could we just frame the query in terms of `HP:0200119` instead?

**Comment by saramsey** [comment] 2021-07-14 06:05
Or `MONDO:0002251`?

**Comment by ericawood** [comment] 2021-07-14 06:27
Based on the warnings in this issue, I'm pretty sure that this is a result of SNOMED IDs no longer being in KG2. This, they will not show up in the synonymizer. Was there a particular reason you used this CURIE? Would it be beneficial to have a SNOMED-included (and maybe MEDDRA too) version of KG2 for each build? 
![image](https://user-images.githubusercontent.com/36611732/125573559-33d9b4d3-ab65-408f-bfdc-f40212514707.jpeg)

**Comment by finnagin** [comment] 2021-07-14 07:54
So the problem with using the other identifiers is that we couldn't get the OMOP mapping for them. The curies I had were MONDO:0005359, SNOMEDCT:197358007, MESH:D056487, MESH:D006760, and NCIT:C26991 

Looks like hte HP curie works though: https://arax.ncats.io/test/?r=16147

However we are still getting no results but not because of the OMOP id thing. Just because it can't find any edges matching e1.

**Comment by ericawood** [comment] 2021-07-14 07:56
Were those OMOP mappings coming from KG2 or another source?

**Comment by finnagin** [comment] 2021-07-14 08:03
I believe the OMOP mappings come from [Athena](https://athena.ohdsi.org/search-terms/start).

**Comment by finnagin** [comment] 2021-07-14 08:03
Though a local version that we have.

**Comment by chunyuma** [comment] 2021-07-14 17:16
> So the problem with using the other identifiers is that we couldn't get the OMOP mapping for them. The curies I had were MONDO:0005359, SNOMEDCT:197358007, MESH:D056487, MESH:D006760, and NCIT:C26991

Hi @finnagin, by checking the OMOP mapping for the other identifiers that you listed above in the new-build COHD local database, I found that some of them (eg. `MONDO:0005359`, `MESH:D056487`) still have a few OMOP mapping.

```
In [2]: from COHDIndex import COHDIndex

In [3]: cohdindex = COHDIndex()
INFO: Connecting to database
In [12]: cohdindex.get_concept_ids('MONDO:0005359')
Out[12]: [45619654, 4055223]

In [13]: cohdindex.get_concept_ids('SNOMEDCT:197358007')
Can't convert SNOMEDCT:197358007 to preferred curie in get_concept_ids and thus use its original curie
Out[13]: [4059297]

In [14]: cohdindex.get_concept_ids('MESH:D056487')
Out[14]: [35944536, 4340942, 45612398]

In [15]: cohdindex.get_concept_ids('MESH:D006760')
Out[15]: []

In [16]: cohdindex.get_concept_ids('NCIT:C26991')
Out[16]: []
```

**Comment by saramsey** [comment] 2021-07-14 18:06
So are we good?  Big picture, can we live without SNOMED?

**Comment by finnagin** [comment] 2021-07-14 18:13
@saramsey Yeah I think we can likely live without SNOMED in KG2 though I'm wondering if we want the ability to query using curies that do not appear in KG2 if we are expanding with a different KP.

@chunyuma Looks like for "MONDO:0005359" and "MESH:D056487" I get a warning like `No paired concept frequency was found from COHD database for source preferred id 'MONDO:0005359'' with qnode id 'n0'` does this mean that we found an OMOP id but then COHD doesn't return results for it?

**Comment by chunyuma** [comment] 2021-07-14 18:39
@finnagin, you're right, when you got that warning, it means that there is no COHD information (eg. `chi-square`, `observed expected ratio` and `relative frequency`) for any one of OMOP id mapping (45619654, 4055223) of `MONDO:0005359`. If you check them by using COHD API, you will also find that there is no result for these two OMOP ids:

https://cohd.io/api/association/chiSquare?dataset_id=3&concept_id_1=45619654
https://cohd.io/api/association/chiSquare?dataset_id=3&concept_id_1=4055223

**Comment by dkoslicki** [comment] 2021-07-15 15:26
@CaseyTa Any ideas why the current COHD API doesn't have any results for these DILI identifiers?

**Comment by CaseyTa** [comment] 2021-07-15 16:22
@dkoslicki Unfortunately, due to institutional policy, we don't have data on iatrogenic codes (conditions potentially caused by medical care) in COHD. This is why we decided to include SNOMEDCT:197358007 (toxic liver disease with acute hepatitis) as one of the identifiers. This is the closest condition to DILI that we have information on in COHD, and COHD doesn't have data on any of the other IDs used in Workflow B. The other IDs suggested by Steve (HP:0200119 - acute hepatitis and MONDO:0002251 - hepatitis) are too broad to relate to DILI. 

The COHD TRAPI endpoint will also respond to UMLS:C0451709 with the same results, if that helps get around the SNOMED issue. 

The below query to COHD using multiple IDs *should* work including all IDs:
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "Disease Or Phenotypic Feature"
        },
        "n0": {
          "ids": [
            "UMLS:C0451709", "MONDO:0005359", "MESH:D056487", "MESH:D006760", "NCIT:C26991"
          ],
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "toxic liver disease with acute hepatitis"
        }
      },
      "edges": {
        "e0": {
          "subject": "n1",
          "object": "n0",
          "predicates": [
            "biolink:correlated_with"
          ]
        }
      }
    }
  }
}
```

But right now a recent code change has introduced a crash on this query. We should have this fixed later today. For now, the query with just the single `UMLS:C0451709` ID works.

**Comment by finnagin** [comment] 2021-07-15 17:27
Looks like we can't find the OMOP id for that UMLS query: https://arax.ncats.io/test/?r=16239

Though, I'm also seeing the node synonymizer warning as well so this may run into the same problem the SNOMEDCT curie was having even if we figure out the OMOP id issue.

I tried searching Athena and didn't find the OMOP id either: https://athena.ohdsi.org/search-terms/terms?query=C0451709

**Comment by CaseyTa** [comment] 2021-07-15 18:44
@finnagin Ah, so the UMLS doesn't work either? I don't think Athena incorporates UMLS. SRI Node Normalizer just maps UMLS:C0451709 and SNOMEDCT:197358007 together (https://nodenormalization-sri.renci.org/1.1/get_normalized_nodes?curie=UMLS%3AC0451709), so if you don't have SNOMED, that probably doesn't help. It may be hard to get mappings to OMOP without SNOMED-CT since most OMOP condition concepts are based on SNOMED-CT. 

Regarding the overlay / scoring operation for Workflow B, would it be easier to prototype either starting from the DILI results coming from ICEES instead or using the COHD TRAPI call to pull in COHD results? 

Also, we have that previous issue with the above TRAPI query resolved now. Sending either the above query with multiple IDs or a query with just the single UMLS ID to COHD's TRAPI endpoint should produce (essentially) the same results since COHD doesn't have data on the other IDs.

**Comment by finnagin** [comment] 2021-07-15 19:56
Hmmm... We could try that. @amykglen do we have a way of taking someone else's results and then running resultify on them? Or someone else's partially filled query then expanding on the remaining edges?

**Comment by edeutsch** [comment] 2021-07-16 04:02
> Hmmm... We could try that. @amykglen do we have a way of taking someone else's results and then running resultify on them? Or someone else's partially filled query then expanding on the remaining edges?

workflows is the intended solution to this.

**Comment by chunyuma** [comment] 2021-07-16 16:04
>  @amykglen do we have a way of taking someone else's results and then running resultify on them?

Perhaps it might be somewhat related to #1574. I'm wondering if calling COHD APIs and taking their results as part of our results is fast enough. If it works, perhaps it might mean that the local copy is useless. It might also directly solve the issue #1574. The original goal of building a local copy is about the slow speed of calling COHD APIs. So I think we might need to consider this when thinking a way of taking some else 's results.

**Comment by amykglen** [comment] 2021-07-19 20:27
@chunyuma - that's certainly an option to switch to using the COHD API vs. a local copy. it's very easy to plug into the `TRAPIQuerier` - when I do so locally, it looks like the three COHD tests in `test_ARAX_expand.py` take a combined total of 2.25 minutes vs. 13 seconds when the local copy is used. is this worth switching to their API, or too slow still?

if we do switch to using their API, I would likely have to adjust Expand's timeout rules so that they're more lenient for COHD (maybe specifically for queries where COHD is the only KP capable of answering a query), as this is quite a bit slower than the other KPs.

**Comment by chunyuma** [comment] 2021-07-19 20:35
Thanks so much for testing @amykglen. I think the difference between 2.25 minutes vs 13 seconds is large. If we need to call `expand` multiple times in one single query, perhaps this difference might be more significant. 

How about we consider the similar idea like what DTD uses that we set a `slow_mode` parameter for users to switch between COHD API and the local copy? In default, it can use the local copy because it is much faster. However, In some special case where the local copy can't return the expected result like this issue or #1574, we can switch to use COHD API.

**Comment by chunyuma** [comment] 2021-09-08 22:56
@finnagin, can we close this issue now? I just checked the following query that you posted and it works:

```
  "add_qnode(key=n0,ids=SNOMEDCT:197358007)",
  "add_qnode(key=n1,categories=biolink:DiseaseOrPhenotypicFeature)",
  "add_qnode(key=n2,categories=biolink:Gene)",
  "add_qnode(key=n3,categories=biolink:ChemicalEntity)",
  "add_qedge(key=e0,subject=n0,object=n1,predicates=biolink:correlated_with)",
  "add_qedge(key=e1,subject=n1,object=n2,predicates=biolink:condition_associated_with_gene)",
  "add_qedge(key=e2,subject=n2,object=n3,predicates=biolink:related_to)",
  "add_qedge(key=e3,subject=n3,object=n1,predicates=biolink:correlated_with)",
  "expand(kp=COHD)",
  "resultify()"
```

**Closed** 2022-02-02 21:18 UTC
Labels: bug, high priority
