### ISSUE TITLE
MolPro results with "superclass reasoning" causing issues with ARAX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1886] opened 2022-08-05 16:41 UTC
The following query,
```
{
  "edges": {
    "e0": {
      "object": "n0",
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:PhenotypicFeature",
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0100231",
        "MONDO:0100232"
      ],
      "is_set": false
    },
    "n1": {
      "is_set": false
    }
  }
}
```
(which came out of the [Translator Question of the Month](https://github.com/NCATSTranslator/testing/issues/220) session today), is generating some results (see [ARAX results 55221](https://arax.ncats.io/?r=55221) that show loss of semantic precision that I think derives from the "superclass reasoning" that MolPro is doing (which was discussed at length in the Expander Agent all-hands meeting on Aug. 3, 2022; see also [RTX issue 1855](https://github.com/RTXteam/RTX/issues/1855) which I think has the same root cause as this issue). The aforementioned query is asking for concepts (any concepts) that are `biolink:related_to` the disease "suseptibility to psoriatic arthritis" (coded as a query node with a pair of CURIEs, `MONDO:0100231` and `MONDO:0100232`). Seems straightforwad, but we are seeing a bunch of organic compounds returned that are not related to "susceptibility to psoriatic arthritis" but instead are related to `MONDO:0042489` ("disease susceptibility"):

<img width="892" alt="Screen Shot 2022-08-05 at 9 39 49 AM" src="https://user-images.githubusercontent.com/5562107/183122821-3a747b87-fe35-4410-9ccd-240e7e8adae1.png">

Note, `MONDO:0042489` is two levels _higher_ in the MONDO hierarchy than `MONDO:0100232`, as shown here:
<img width="529" alt="Screen Shot 2022-08-05 at 9 41 08 AM" src="https://user-images.githubusercontent.com/5562107/183122680-8ecff7fd-49a5-41d3-baf3-e91c73a74cf4.png">

**Comment by saramsey** [comment] 2022-08-05 16:44
I am tagging @dkoslicki and @edeutsch to see if this can be brought up in the Architecture Committee meeting. I think the best remedy here would be if MolPro stops doing this kind of "superclass reasoning", at least by default. The second-best remedy would be if MolPro makes "superclass reasoning" something that can be turned off by specifying an option somewhere in the TRAPI query graph.

**Comment by saramsey** [comment] 2022-08-05 16:49
Another example of MolPro results where superclass reasoning is evident can be see in this [ARS query result link](https://arax.ncats.io/?r=729a0522-8861-4564-bc32-24e33d7c16f0), where one should go to the ARAX results. We see all kinds of drugs in the result-list that are connected to high-level disease concepts like "rheumatic disorder", "psychiatric disorder", "disease or disorder", "neurodegenerative disease", "immune systems disease", basically the whole gamut.

**Comment by saramsey** [comment] 2022-08-05 16:50
Marking this "high priority" as I think it is really causing an issue with the quality of results.

**Comment by saramsey** [comment] 2022-08-05 16:53
It may be that MolPro has already inferred and stored all of these "superclass-reasoned" triples internally, in which case, it may be more difficult for them to filter them out. We should maybe try to ascertain whether or not this is the case, as it may be relevant to what kind of remedy we can hope to get.

**Comment by amykglen** [comment] 2022-08-05 17:00
in the short-term should we remove MolePro as a KP? that is a trivial change, easy to undo when a solution is settled on.

**Comment by saramsey** [comment] 2022-08-05 17:39
I'm open to the idea. Would like to get David and Eric's take on it as well.

**Comment by edeutsch** [comment] 2022-08-06 03:34
It is a bit of a drastic move, but I would support it. 

I wonder if a good way to handle this is to compute a relevance score for each received edge? Although a fair bit of work, maybe we could be able to consider each edge we receive and see if it is relevant. If we ask for information about type 1 diabetes and get back answers for immune disorder, perhaps we could keep it, but downweight it substantially as not very relevant. This would be for pinned nodes in queries. If we had easy access to ontologies, we could compute how relevant is the returned node relative to the pinned nodes. Exact matches are highly relevant. Children are less relevant but okay. Ancestors are severely downweighted, perhaps say a factor of 2 in each generation. This could allow such ancestor reasoning to stay, but be downweighted as not very relevant to the question. If there are relevant answers, they get prioritized and these ancestor relationships are way down the rank. If there's nothing relevant, then less relevant things are top.

Perhaps a good abstract question is: if I ask ARAX about specific disease X, and there's nothing highly relevant for X or children of X, might I be interested in generic things for ancestors of X like immune disorders, or do I want nothing in response. Nothing or less relevant?

**Comment by jh111** [comment] 2022-08-24 22:09
I'd actually prefer to have something less relevant than nothing.

**Comment by saramsey** [comment] 2022-10-06 20:27
What's the status on this?  Did we remove MolPro from Expand?

**Comment by amykglen** [comment] 2022-10-06 21:42
no, no action was taken - we still currently use MolePro

**Comment by dkoslicki** [comment] 2023-03-15 02:01
See https://github.com/NCATSTranslator/Feedback/issues/148 for a possible additional issue caused by superclass reasoning

**Comment by dkoslicki** [comment] 2023-04-30 21:29
Take a look at: https://arax.ncats.io/?r=135342, specifically things like result 14, where superclass reasoning is used. Maybe their fix hasn't been deployed yet?

**Comment by jh111** [comment] 2023-05-01 03:11
The problem still occurs with https://arax.ncats.io/?r=135342, and answer like 4-aminophenylarsenoxide are not related to the query. You can disregard my earlier note, the answer is not more helpful than having nothing at all. It's just that edges were displaying on top of each other. Here they are spread out.

![image](https://user-images.githubusercontent.com/25163472/235396258-c3ec9ed3-a675-423e-890b-a0758c5850f2.png)

**Comment by jh111** [comment] 2023-05-01 03:13
At the same time, I expect people will query with "Psoriatic Arthritis", not "Susceptibility to Psoriatic Arthritis".

**Comment by saramsey** [comment] 2023-05-01 15:58
Thank you @jh111 and @dkoslicki for pointing out this issue is still going on. I have reached out to the MolePro team via Slack DM and via a comment on [NCATSTranslator/Feedback issue 148](https://github.com/NCATSTranslator/Feedback/issues/148), to find out which ITRB service maturity level their fix was deployed to (test, dev, or prod).

**Comment by dkoslicki** [comment] 2023-06-08 13:04
Update: turns out this was a subtle issue between ARAGORN/Automat and MolePro. Apparently an Automat fix will be up within a week, and then MolePro will re-build and push a fix.

**Comment by saramsey** [comment] 2023-06-12 16:59
Thank you @dkoslicki!

**Comment by kvnthomas98** [comment] 2024-06-18 15:17
Seems to be fixed now [the test query](https://arax.ncats.io/?r=247450)

**Closed by kvnthomas98** 2024-06-18 15:17 UTC
Labels: Reasoning
