### ISSUE TITLE
somewhat odd canonical CURIE prefix for KG2c nodes of category `biolink:OrganismTaxon`

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1377] opened 2021-04-15 16:56 UTC
On `kg2c-5-2.rtx.ai`, I ran the following Cypher query:
```
match (n:`biolink:OrganismTaxon` {name: 'Homo sapiens'}) return n.name, n.id, n.equivalent_curies;
```
and was a bit surprised to see this result:
<img width="1154" alt="Screen Shot 2021-04-15 at 9 55 36 AM" src="https://user-images.githubusercontent.com/5562107/114908270-c8a5ce80-9dd0-11eb-885c-6b0879255f41.png">

Is it not the case that for nodes of `category` `biolink:OrganismTaxon`, the canonical CURIE prefix should be `NCBITaxon`?

Apologies if `CHEMBL.TARGET` is in fact the established canonical CURIE prefix for such nodes and I'm just out of the loop...

**Comment by amykglen** [comment] 2021-04-15 17:12
does seem a bit strange - tagging @edeutsch as he is the mastermind of preferred curies :)

(side note: since nodes are labeled with all of their `expanded_categories` in KG2c, the query you did could've pulled up nodes whose `category` (the 'preferred' category) was something different than `biolink:OrganismTaxon`. but I confirmed that in this case, biolink:OrganismTaxon is also the `category`.)

**Comment by saramsey** [comment] 2021-04-15 17:25
Thanks, @amykglen

**Comment by amykglen** [comment] 2023-05-26 16:38
this is resolved in KG2.8.0.1c:

![Screen Shot 2023-05-26 at 9 38 07 AM](https://github.com/RTXteam/RTX/assets/49423686/d46794e7-1be6-4179-9e7e-e99d04058b73)

closing

**Closed by amykglen** 2023-05-26 16:38 UTC
Labels: question, node synonymizer, kg2c
