### ISSUE TITLE
Roll out KG2.7.6 (Biolink 2.2.11)

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX#1838] opened 2022-05-18 01:43 UTC
_NOTE: To create a new issue based on this template, simply go to: https://github.com/RTXteam/RTX/issues/new?template=kg2rollout.md_

##### 1. Build and load KG2c:

- [x] merge `master` into the `kg2integration` branch
- [x] update the four hardcoded biolink version numbers in the `kg2integration` branch (as needed):
  - [x] in [code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml](../code/UI/OpenAPI/python-flask-server/openapi_server/openapi/openapi.yaml)
  - [x] in [code/UI/OpenAPI/python-flask-server/KG2/openapi_server/openapi/openapi.yaml](../code/UI/OpenAPI/python-flask-server/KG2/openapi_server/openapi/openapi.yaml)
  - [x] in [code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.2_ARAX.yaml](../code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.2_ARAX.yaml)
  - [x] in [code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.2_KG2.yaml](../code/UI/OpenAPI/python-flask-server/RTX_OA3_TRAPI1.2_KG2.yaml)
- [x] build a new KG2c on `buildkg2c.rtx.ai` from the `kg2integration` branch (how-to is [here](https://github.com/RTXteam/RTX/tree/master/code/kg2c#build-kg2canonicalized))
  - [x] make sure to choose to build a new synonymizer in `kg2c_config.json`, as described in the how-to
  - [x] verify the build looks ok:
    - [x] the synonymizer sqlite should be around 15-20 GB
    - [x] the entire build process (synonymizer + KG2c) shouldn't have taken more than ~24 hours
    - [x] the synonymizer and KG2c artifacts should have been auto-uploaded into the proper directory on `arax.ncats.io` (`/data/orangeboard/databases/KG2.7.6`)
- [x] load the new KG2c into neo4j at http://kg2-7-6c.rtx.ai:7474/browser/ (how to is [here](https://github.com/RTXteam/RTX/tree/master/code/kg2c#host-kg2canonicalized-in-neo4j))
- [x] upload the new `kg2c_lite_2.7.6.json.gz` file to the [translator-lfs-artifacts](https://github.com/ncats/translator-lfs-artifacts/tree/main/files) repo
- [x] load the new KG2c into plover (available at http://kg2-7-6cplover.rtx.ai:9990)

##### 2. Rebuild downstream databases:

Copies of all of these should be put in `/data/orangeboard/databases/KG2.7.6` on arax.ncats.io.

- [x] configv2.json (should point to the new KG2pre/KG2c/plover)
    - note: save this as `config_local.json`, since we want it to be used over `configv2.json` during testing
- [x] NodeSynonymizer
- [x] KG2c meta knowledge graph
- [x] KG2c sqlite
- [x] KG2c TSV tarball
- [x] KG2c neo4j dump (this is created on the neo4j hosting instance when loading KG2c, at `/home/ubuntu/kg2-build/kg2c.dump`)
- [x] FDA-approved drugs pickle
- [x] NGD database
- [x] COHD database @chunyuma
- [x] refreshed DTD @chunyuma
- [x] DTD model @chunyuma _(may be skipped - depends on the KG2 version)_
- [x] DTD database @chunyuma _(may be skipped - depends on the KG2 version)_

**NOTE**: As databases are rebuilt, the new copy of `config_local.json` will need to be updated to point to their new paths. However, if the rollout of KG2 has already occurred, then you should update the master `configv2.json` directly. 

##### 3. Update the ARAX codebase:

All code changes should go in the `kg2integration` branch.

- [x] update Expand code as needed
- [x] update any other modules as needed
- [x] test everything together (entire ARAX pytest suite should pass when using the new `config_local.json` - must locally set `force_local = True` in `ARAX_expander.py` to avoid using the old KG2 API)
- [x] update the KG2 and ARAX version numbers in the appropriate places (`openapi.yaml`, etc.) @edeutsch

##### 4. Do the rollout:

- [x] merge `master` into `kg2integration`
- [x] merge `kg2integration` into `master`
- [x] make `config_local.json` the new master config file on `araxconfig.rtx.ai` (rename it to `configv2.json`)
- [x] roll `master` out to the various `arax.ncats.io` endpoints and delete their `configv2.json`s
- [x] run the database manager
- [x] run the pytest suite on the various endpoints
- [x] update the CI/CD instance:
  - [x] replace the `configv2.json` file on `cicd.rtx.ai` with the new one
  - [x] download the new database files to `cicd.rtx.ai`

##### 5. Final items/clean up:

- [x] generate KGX files and upload them to the KGE Archive @acevedol
- [x] update the KG2c test triples file (generate with [this script](https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/create_csv_of_kp_predicate_triples.py), using the new `config_local.json`) @acevedol
- [x] rename the `config_local.json` on arax.ncats.io to `config_local.json_FROZEN_DO-NOT-EDIT-FURTHER` (any additional edits to the config file should be made directly to the master `configv2.json` on araxconfig.rtx.ai going forward)
- [x] turn off the old KG2c version's neo4j instance
- [x] turn off the old KG2c version's plover instance
- [x] turn off the new KG2pre version's neo4j instance
- [x] upgrade the NCATS-hosted Plover endpoint (https://kg2cploverdb.ci.transltr.io) to this KG2 version and make the KG2 API start using it (instead of our self-hosted endpoint): 
    - [x] update `kg_config.json` in the `main` branch of the Plover repo to point to the new `kg2c_lite_2.X.Y.json.gz` file (push this change)
    - [x] wait about 45 minutes for the endpoint to rebuild and then run Plover tests to verify it's working
    - [x] run the ARAX pytest suite with the NCATS endpoint plugged in: use a `config_local.json` that points to it and locally set `force_local = True` in Expand
    - [x] if all tests pass, update the master `configv2.json` on araxconfig.rtx.ai to point to this Plover endpoint
    - [x] delete the arax.ncats.io `kg2` endpoint's `configv2.json` to force it to download the new copy and then verify it's working correctly by running a query
    - [x] turn off our plover endpoint and verify once more that ARAX is still working ok

**Comment by acevedol** [comment] 2022-05-18 01:46
The biolink version did not change, so there is no need this time to update the biolink version

**Comment by acevedol** [comment] 2022-05-18 01:50
Building synonymizer on branch `kg2integration`

**Comment by acevedol** [comment] 2022-05-18 17:43
Node Synonymizer SQLite `node_synonymizer_v1.0_KG2.7.6.sqlite` is about 19.11 GB, slightly larger than `node_synonymizer_v1.0_KG2.7.5.sqlite`

**Comment by acevedol** [comment] 2022-05-18 17:45
Synonymizer artifacts made it to `arax.ncats.io`

**Comment by acevedol** [comment] 2022-05-18 17:50
Error building kg2c
```
2022-05-18 06:07:24,628 INFO: Downloading kg2-tsv-for-neo4j.tar.gz from the rtx-kg2 S3 bucket
2022-05-18 06:08:19,285 INFO: Unpacking kg2-tsv-for-neo4j.tar.gz..
tar (child): kg2-tsv-for-neo4j.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "RTX/code/kg2c/build_kg2c.py", line 147, in <module>
    main()
  File "RTX/code/kg2c/build_kg2c.py", line 127, in main
    create_kg2c_files(args.test)
  File "/home/ubuntu/RTX/code/kg2c/create_kg2c_files.py", line 662, in create_kg2c_files
    subprocess.check_call(["tar", "-xvzf", kg2pre_tarball_name, "-C", local_tsv_dir_path])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xvzf', 'kg2-tsv-for-neo4j.tar.gz', '-C', '/home/ubuntu/RTX/code/kg2c/kg2pre_tsvs']' returned non-zero exit status 2.
```

**Comment by acevedol** [comment] 2022-06-15 18:25
@amykglen I'm working on the config_local.json. Thank you for sending instructions! I'll let you know when it's complete

**Comment by acevedol** [comment] 2022-06-15 18:43
@amykglen Okay, I got config_local.json updated on `buildkg2c.rtx.ai` on the `kg2integration` branch, and copied it to `arax.ncats.io`.

**Comment by acevedol** [comment] 2022-06-15 20:58
Skipping COHD database rebuild and refreshed DTD steps on this build

**Comment by amykglen** [comment] 2022-06-21 17:26
all databases have been rebuilt and I tested everything together on my system - all tests passing. 

so we're ready for a rollout. maybe at tomorrow's mini-hackathon?

**Comment by amykglen** [comment] 2022-06-22 23:09
plan is to do the roll out at 6/29 mini-hackathon

**Comment by amykglen** [comment] 2022-08-03 20:06
hey @acevedol - have you gotten a chance to create the test triples file for KG2.7.6 yet?

**Comment by amykglen** [comment] 2022-08-03 23:47
arax.ncats.io/NewFmt seems to be working properly after rebuilding Plover

**Comment by amykglen** [comment] 2022-08-03 23:56
successfully uploaded the KG2.7.6 files to `sftp.transltr.io`

**Comment by amykglen** [comment] 2022-08-04 04:05
I also just updated the CI/CD instance with new config/database files (I think) - we'll see if it's working again with my commit a minute ago...

**Comment by amykglen** [comment] 2022-08-04 15:54
the ITRB folks have done the deployments on their end - they're ready for us to merge `master` into `production` and `itrb-test`. I can take care of that as long as @edeutsch doesn't have any objections? I'll hold off on actually rolling those branches out to our endpoints.

**Comment by edeutsch** [comment] 2022-08-04 15:58
no objections. a conflict is possible.
I can roll out to our endpoints at 11am

**Comment by amykglen** [comment] 2022-08-04 16:04
great! I did the merges; no conflicts. pushed. 

note that when we roll out to our production endpoint, we'll need to create a new `config_local.json` for it. I can create that now and have it standing by.

**Comment by amykglen** [comment] 2022-08-04 16:23
I created new copies of `config_local.json` for the production endpoints - they're standing by at:
```
/translator/data/orangeboard/production/RTX/code/config_local.json_2.7.6
/translator/data/orangeboard/kg2/RTX/code/config_local.json_2.7.6
```

**Comment by amykglen** [comment] 2022-08-04 17:14
@acevedol - it looks I fixed the KG2.7.6c Neo4j issues just now (http://kg2-7-6c.rtx.ai:7474/browser/). fyi, what I did was:
```
ssh ubuntu@kg2canonicalized2.rtx.ai
sudo service neo4j stop
bash -x RTX/code/kg2c/tsv-to-neo4j-canonicalized.sh
```
confirmed it actually seems to be KG2.7.6 that was loaded by running the following query:
```
match (n {id:"RTX:KG2c"}) return n
```
![Screen Shot 2022-08-04 at 10 12 54 AM](https://user-images.githubusercontent.com/49423686/182910963-e268895b-d6e1-4ea9-ab25-33088adf201d.png)

so this means you can regenerate the test triples file now (using the KG2.7.6 `config_local.json`).

**Comment by amykglen** [comment] 2022-08-05 01:33
current status of the rollout is:
- our endpoints are all on KG2.7.6 now
- ITRB Plover is on 2.7.6 for CI, Test, and Prod
- ITRB KG2/ARAX is on 2.7.6 for CI
- ITRB KG2/ARAX Test and Prod are broken (apparently due to a database download issue on ITRB's end) Pouyan has been working on this today

**Comment by edeutsch** [comment] 2022-08-05 02:04
Thank you, Amy! This is getting very complex to maintain.

**Comment by amykglen** [comment] 2022-08-05 17:05
alright, ITRB Prod and Test are also both working now! 

so I think the only real lingering pieces of this rollout are these two items:

- [ ] generate KGX files and upload them to the KGE Archive @acevedol
- [ ] update the KG2c test triples file (generate with [this script](https://github.com/RTXteam/RTX/blob/master/code/ARAX/KnowledgeSources/create_csv_of_kp_predicate_triples.py), using the new config_local.json) @acevedol

**Comment by acevedol** [comment] 2022-08-05 22:14
Thanks, Amy. The test triples are now updated and the KGX files uploaded to KGE.

**Comment by amykglen** [comment] 2022-08-06 00:08
awesome! think the rollout is complete!

@edeutsch - is it ok to merge `master` into `production` so that the updated test triples file makes it to the `production` branch?

**Comment by edeutsch** [comment] 2022-08-06 02:55
yes, that should be fine, thanks!

**Comment by amykglen** [comment] 2022-08-06 04:41
great - just did that.

it sounds like Chunyu is updating COHD and DTD for KG2.7.6 - when he's done these are the config files that will need updating:
* the master `configv2.json` on `araxconfig.rtx.ai`
* our ARAX production endpoint's `config_local.json`
* the three ITRB config files (`ci-configv2.json`, `test-configv2.json`, and `prod-configv2.json`); we will then need to provide ITRB with these three updated config files as well as the new databases by uploading them to the `sftp.transltr.io` server and notifying them
* `cicd.rtx.ai`'s config file; also the new databases will need to be uploaded to that instance

**Comment by amykglen** [comment] 2022-09-08 21:21
ok, the KG2.7.6 COHD/DTD databases have been deployed in `master` and the ITRB CI instance rebuilt successfully. note (@edeutsch in particular) that when we merge `master` into `itrb-test` and `production`, the corresponding ITRB instances will likely give 503 errors while they are downloading the new databases, which will probably take 30 minutes or so. so we may want to do those merges at a relatively quiet time.

**Comment by edeutsch** [comment] 2022-09-08 21:33
@amykglen shall we plan on a deployment tonight?

**Comment by amykglen** [comment] 2022-09-09 02:28
sure, sounds good!

**Comment by edeutsch** [comment] 2022-09-09 03:00
I am at an event now, but maybe returning 10:30ish?

**Comment by edeutsch** [comment] 2022-09-09 05:57
okay, I am finally back. The goal is to roll out master everywhere?

**Comment by amykglen** [comment] 2022-09-09 05:57
yes, think so

**Comment by amykglen** [comment] 2022-09-09 16:16
closing this since all KG2.7.6 databases have been rolled out now

**Closed by amykglen** 2022-09-09 16:16 UTC
Labels: kg2 rollout
