### ISSUE TITLE
ARAX_expand: edge directions matter. Should they?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#627] opened 2020-02-17 05:43 UTC
In the following query:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:11130, id=n00)",  # Secondary hypertension
            "add_qnode(type=phenotypic_feature, is_set=true, id=n01)",
            "add_qnode(type=chemical_substance, is_set=true, id=n02)",
            "add_qnode(type=protein, is_set=true, id=n03)",
            "add_qedge(source_id=n00, target_id=n01, id=e00, type=has_phenotype)",  # phenotypes of secondary hypertension
            "add_qedge(source_id=n02, target_id=n01, id=e01, type=indicated_for)",  # only look for drugs that are indicated for those phenotypes
            "add_qedge(source_id=n02, target_id=n03, id=e02)",  # find proteins that interact with those drugs
            "expand(edge_id=[e00, e01, e02])",
            "return(message=true, store=false)"
        ]}}
```
a graph is found with 960 nodes. Yet reverse the direction of one `qedge`:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:11130, id=n00)",  # Secondary hypertension
            "add_qnode(type=phenotypic_feature, is_set=true, id=n01)",
            "add_qnode(type=chemical_substance, is_set=true, id=n02)",
            "add_qnode(type=protein, is_set=true, id=n03)",
            "add_qedge(source_id=n00, target_id=n01, id=e00, type=has_phenotype)",  # phenotypes of secondary hypertension
            "add_qedge(source_id=n01, target_id=n02, id=e01, type=indicated_for)",  #<---- NOTE REVERSED SOURCE, TARGET
            "add_qedge(source_id=n02, target_id=n03, id=e02)",  # find proteins that interact with those drugs
            "expand(edge_id=[e00, e01, e02])",
            "return(message=true, store=false)"
        ]}}
```
and you get an empty graph. @amykglen @saramsey Is this ok with you guys? I thought one paradigm was that "most" edges should be considered bidirectional...

**Comment by saramsey** [comment] 2020-02-29 16:53
What's the status of this issue?  I just noticed it (sorry). I feel like a `ignore_edge_direction` boolean optional parameter (like we have for `ARAX_resultify`) would make sense, if it is technically feasible? What do you think, @amykglen ?

**Comment by amykglen** [comment] 2020-02-29 17:01
Yeah, an `ignore_edge_direction` optional boolean parameter sounds good to me... I haven't yet done any work on this issue, but technical feasibility seems fine to me. I can work on this after wrapping up #641 .

**Comment by dkoslicki** [comment] 2020-03-11 22:37
@amykglen Just curious if this issue is still an issue, or if it was addressed at some point.

**Comment by amykglen** [comment] 2020-03-12 02:29
It hasn't been addressed yet, but I could tackle it this week if desired.

**Comment by amykglen** [comment] 2020-04-09 16:55
Since #698 involved moving away from `QueryGraphReasoner` and writing some new cypher generation code (for KG2 expands, so far), I've started to address this issue - I actually began by ignoring edge directions (so that is how KG2 expands are currently functioning). Is that the default behavior we want? Perhaps with an optional boolean parameter like `enforce_edge_directions=true`?  Or vice versa?

And interestingly, I suppose this parameter would technically apply more at the `QueryEdge` level, rather than the `Expand` level. Since it seems possible a user may want to ignore edge direction for one edge in their query graph, but not for another...

**Comment by edeutsch** [comment] 2020-04-09 18:20
I don't really know for sure here what is best, but I do think that returning two edges of the same type with opposing directions is just distracting. If we have a parameter to control this, I would make the default be to suppress two edges, but maybe allow an optional parameter to preserve both edges.

**Comment by dkoslicki** [comment] 2020-04-10 02:16
@edeutsch I think the more pressing issue is not two edges with opposing directions, but rather when (n1)->(n2), but not conversely (I.e. there’s a single directed edge in a single direction). If someone adds a qedge, (even myself for instance, hence opening this issue), I don’t always immediately know which directions the arrows are pointing and would rather just have (when no edge direction is specified), have it “just give me an edge, I don’t care which direction it points.” So @amykglen your proposal of having edge direction not matter by default, but optionally enforcing it at the `QueryEdge` level makes the most sense (since if we or a user really cares about edge direction, they would specify it here).

Note: This may be a thing to also bring up in the https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI as if the ARS passes us a query graph with edge directions are specified, we’d better be _really_ sure that they want these edge directions enforced. Or we need to communicate to them that if they are unsure of the edge direction, make the edge undirected (I don’t know the the ReasonerStdAPI allows for specifying undirected QG edges).

**Comment by edeutsch** [comment] 2020-04-10 03:39
The API standard has source_id and target_id so everything is implicitly directional. I suppose I would suggest that we have a global (or potentially also local) option enforce_directionality={true|lazy} where the default is lazy and that means "Be lazy about which is the source and target, it doesn't matter, but don't give me both if you have both directions".

**Comment by amykglen** [comment] 2020-04-28 14:24
I think this can be closed now? (addressed in #714 - `expand` now ignores edge direction by default, and has an optional parameter `enforce_directionality` that can be set to `true` in the event one does want to obey edge directions)

**Comment by amykglen** [comment] 2020-04-28 14:34
(Confirmed on beta that **both** of the two original DSL examples posted here now produce results.)

**Comment by edeutsch** [comment] 2020-04-28 14:38
excellent! fine to close, thanks.

**Closed by edeutsch** 2020-04-28 14:38 UTC
Labels: ARAX demo
