### ISSUE TITLE
ICEES one-hop endpoint as another expand

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1509] opened 2021-06-11 20:53 UTC
From Hao Xu:
>ICEES has a one hop API endpoint which is in addition to the overlay API endpoint that has been integrated into the overlay command in ARAXi. I wonder if it is possible to integrate the ICEES one hop API endpoint into the expand command, which will help us express one of our workflows in ARAXi? We currently have two ICEES instances. exposures: https://icees.renci.org:16339/apidocs#/reasoner/knowledge_graph_one_hop_query_post, dili: https://icees.renci.org:16341/apidocs#/reasoner/knowledge_graph_one_hop_query_post

@amykglen do you think it would be feasible to hook this into `expand`?

**Comment by dkoslicki** [comment] 2021-06-11 20:57
Hao Xu's GH handle is @xu-hao in case there are any questions

**Comment by saramsey** [comment] 2021-06-11 21:02
David, any idea why the `/knowledge_graph_one_hop_query_post` endpoint is showing up as "deprecated"?

![Screen Shot 2021-06-11 at 2 01 52 PM 1](https://user-images.githubusercontent.com/5562107/121748361-aa510c00-cabd-11eb-897f-f76eb5343832.png)

**Comment by dkoslicki** [comment] 2021-06-11 21:20
Looks like it was depreciated in favor of `query`, but @xu-hao might know more

**Comment by amykglen** [comment] 2021-06-15 16:36
yes, seems feasible to me! I'll reach out to Hao with any questions.

**Comment by dkoslicki** [comment] 2021-07-03 04:27
Tagging @karafecho as she asked to be kept up-to-date on the integration

**Comment by amykglen** [comment] 2021-07-04 20:38
this is almost ready, but I'm running into a couple issues with the ICEES API's `/meta_knowledge_graph` endpoint.

the first is that its list of `edges` seems very sparse and contains different information on different calls.

for instance, the first time I called it (at `https://icees.renci.org:16341/meta_knowledge_graph`), this was the contents of the meta knowledge graph's `edges`:
```
  "edges": [
    {
      "subject": "biolink:EnvironmentalExposure",
      "object": "biolink:EnvironmentalExposure",
      "predicate": "biolink:correlated_with"
    }
  ]
```
but the second time I called it, this is what it contained:
```
  "edges": [
    {
      "subject": "NamedThing",
      "object": "NamedThing",
      "predicate": "biolink:correlated_with"
    }
  ]
```
our KP integration system relies heavily on the `/meta_knowledge_graph` endpoint so it's really ideal that this endpoint returns all of the meta-edges ICEES can answer (or, technically just the most 'specific' ones - our system infers predicate/category ancestors). 

the second issue is that the `NamedThing` categories above are missing their `biolink:` prefixes. i.e., they should be listed as `biolink:NamedThing` instead of `NamedThing`.

@xu-hao are these things you can fix?

**Comment by amykglen** [comment] 2021-07-04 20:46
actually - scratch the part about getting different information on different calls to `/meta_knowledge_graph`! I was just mixing up the two API URLs, I think.

but for the DILI `/meta_knowledge_graph` (`https://icees.renci.org:16341/meta_knowledge_graph`), the missing `biolink:` prefixes is still an issue and sparsity might also be an issue. is it correct that `biolink:NamedThing` is the most specific category it can answer?

**Comment by xu-hao** [comment] 2021-07-06 16:28
@patrickkwang has checked in a fix for the two issues. We have now more specific edges. I just redeployed the DILI instance and it should be the same as the Asthma instance.

Thanks.

**Comment by amykglen** [comment] 2021-07-06 22:23
great, thanks @xu-hao! I see a lot more meta-edges listed now in the DILI instance's `meta_knowledge_graph`, and locally I have the integration working on a basic level. but I noticed a few more issues with the `meta_knowledge_graph`s that will negatively impact the integration:

**for the Asthma instance `meta_knowledge_graph`:**

I see it still only contains one meta-edge:
```
    {
      "subject": "biolink:EnvironmentalExposure",
      "object": "biolink:EnvironmentalExposure",
      "predicate": "biolink:correlated_with"
    }
```
which, if that is truly the only kind of query the Asthma instance can answer, means the example query in the [swagger documentation](https://icees.renci.org:16339/apidocs#/reasoner/knowledge_graph_one_hop_query_post) shouldn't work, as it looks like:
```
"query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicates": [
            "biolink:correlated_with"
          ]
        }
      },
      "nodes": {
        "n00": {
          "ids": [
            "NCIT:C28421"
          ],
          "categories": [
            "biolink:PhenotypicFeature"
          ]
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ]
        }
      }
    }
```
is the `meta_knowledge_graph` or the example query off here?

**for the DILI instance `meta_knowledge_graph`:**

it looks `biolink:Drug` is sometimes written as `biolink:Dru`? and `biolink:EnvironmentalExposure` is sometimes written as `biolink:EnvironmentalExposureal`? e.g.:
```
    {
      "subject": "biolink:Dru",
      "object": "biolink:EnvironmentalExposureal",
      "predicate": "biolink:correlated_with"
    },
    {
      "subject": "biolink:Dru",
      "object": "biolink:Drug",
      "predicate": "biolink:correlated_with"
    },
....
```
and `biolink:PhenotypicFeature` sometimes has a space in it (like `biolink:Phenotypic Feature`). and I still see some instances of `NamedThing` instead of `biolink:NamedThing`. e.g.:
```
    {
      "subject": "biolink:Phenotypic Feature",
      "object": "NamedThing",
      "predicate": "biolink:correlated_with"
    },
```

**Comment by xu-hao** [comment] 2021-07-12 18:25
thanks @amykglen!

We just fixed the issues.

**Comment by amykglen** [comment] 2021-07-14 17:05
awesome! confirmed they look good on my end.

so the last issue I'm running into is the speed of the Asthma endpoint - how long would you expect a simple one-hop query to take? for the example query in your swagger documentation, our system times out after 2 minutes:
```
     {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicates": [
            "biolink:correlated_with"
          ]
        }
      },
      "nodes": {
        "n00": {
          "ids": [
            "NCIT:C28421"
          ],
          "categories": [
            "biolink:PhenotypicFeature"
          ]
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ]
        }
      }
    }
```
the DILI endpoint seems to give an answer in a reasonable amount of time though.

**Comment by karafecho** [comment] 2021-07-19 17:59
@amykglen : The ICEES+ asthma instance has been redeployed, so this issue should be resolved.

**Comment by amykglen** [comment] 2021-07-19 20:04
great! seems to be working well from my end.

I've merged the integration code into `master`. @isbluis could you make it so these new KPs will appear as options in the DSL builder dropdown? (all documentation has been updated from my end)

after that it'd be awesome if @finnagin or @edeutsch could roll `master` out.

and a couple final things about the Asthma endpoint for @karafecho / @xu-hao - both of these can be observed with the following QG:
```
{
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicates": [
            "biolink:correlated_with"
          ]
        }
      },
      "nodes": {
        "n00": {
          "ids": [
            "NCIT:C28421"
          ],
          "categories": [
            "biolink:PhenotypicFeature"
          ]
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ]
        }
      }
    }
```

1. I noticed that the returned nodes use the prefix `CHEMBL` (e.g., CHEMBL:CHEMBL2108429, CHEMBL:CHEMBL1263) rather than `CHEMBL.COMPOUND`, which I believe is the [Biolink-approved prefix](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L7235) for Chembl. can those be changed to `CHEMBL.COMPOUND:___`? I bring this up since using a non-approved prefix means we struggle to merge your results with those from other KPs.

2. it seems that the `knowledge_graph` you return contains a few nodes that are not bound anywhere in the `results`. I'm not sure whether this could be intentional, but it seems odd and we can't make use of nodes that have no bindings, so thought I'd point it out.
```
  - 2021-07-19T12:55:52.429016 WARNING: [] ICEES-Asthma: Node LOINC:LP101395-4 was found in ICEES-Asthma's answer KnowledgeGraph but not in its Results. Skipping since there is no binding.
  - 2021-07-19T12:55:52.429074 WARNING: [] ICEES-Asthma: Node LOINC:LP345158-2 was found in ICEES-Asthma's answer KnowledgeGraph but not in its Results. Skipping since there is no binding.
  - 2021-07-19T12:55:52.429716 WARNING: [] ICEES-Asthma: Node LOINC:MTHU036194 was found in ICEES-Asthma's answer KnowledgeGraph but not in its Results. Skipping since there is no binding.
  - 2021-07-19T12:55:52.429759 WARNING: [] ICEES-Asthma: Node MESH:D012723 was found in ICEES-Asthma's answer KnowledgeGraph but not in its Results. Skipping since there is no binding.
  - 2021-07-19T12:55:52.429873 WARNING: [] ICEES-Asthma: Node UMLS:C1522384 was found in ICEES-Asthma's answer KnowledgeGraph but not in its Results. Skipping since there is no binding.
```

neither of these breaks our system so we'll proceed with the roll-out, but would be great if they could be addressed!

**Comment by finnagin** [comment] 2021-07-19 20:15
@amykglen I've rolled out to [/test](arax.ncats.io/test). If you want to double check that it is working I can deploy everywhere.

**Comment by amykglen** [comment] 2021-07-19 20:19
awesome, thanks @finnagin! looks good to me on /test.

ICEES-DILI query: https://arax.ncats.io/test/?r=16477
ICEES-Asthma query: https://arax.ncats.io/test/?r=16483

**Comment by finnagin** [comment] 2021-07-19 20:20
Great! I'll roll out everywhere after warning everyone on slack.

**Comment by karafecho** [comment] 2021-07-19 20:33
@amykglen : We are updating our API config files, so (1) should be addressed in the near term. @xu-hao : Perhaps you can look into (2)?

Note that we have a third ICEES+ COVID Instance API that is registered in SmartAPI, but may have an uptime issue (currently under investigation).

**Comment by amykglen** [comment] 2021-07-19 22:22
good to know, thanks @karafecho!

**Comment by amykglen** [comment] 2021-07-19 22:40
I'm thinking it makes sense to close this issue since the DILI/Asthma APIs seem to have been plugged in successfully and then we could create a separate issue for plugging in the COVID API (maybe once the uptime issue is settled).

does that seem reasonable to you, @dkoslicki?

**Comment by dkoslicki** [comment] 2021-07-19 23:52
Great news! I found two issues though: 
1. The asthma endpoint appears to have the DILI knowledge_source attribute. See https://arax.ncats.io/?r=16494
2. Curiously, only one result for the standup query is being returned by ARAX even though ICEES appears to return 50 some odd results: https://github.com/NCATSTranslator/testing/issues/18#event-5040057932

**Comment by amykglen** [comment] 2021-07-20 00:46
re: 1) hmm, when I click on that link, the log shows that ICEES-DILI found results and ICEES-Asthma did not produce results (it timed out). so I'm not sure what you mean by the asthma endpoint having the DILI knowledge_source attribute? and about it timing out, I suppose I may need to adjust the timeout to be more lenient for the ICEES endpoints. (the current standard is 15 seconds for a simple one-hop query, when multiple KPs are being used)

re: 2) I'm seeing 55 results for the QG linked to in the original comment of that issue. https://arax.ncats.io/?r=16498
```
{
      "nodes": {
        "n0": {
          "ids": ["MONDO:0004979"],
          "categories": ["biolink:Disease"]
        },
        "n1": {
          "categories": ["biolink:ChemicalSubstance"]
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1",
          "predicates": ["biolink:correlated_with"]
        }
      }
    }
```
is that the query you're referring to?

**Comment by amykglen** [comment] 2021-07-20 00:52
also re: 1) - when I re-run that query, ICEES-Asthma isn't timing out, so maybe that was just more of a fluke, and I don't need to adjust Expand's timeout rules...

**Comment by isbluis** [comment] 2021-07-20 02:20
> I've merged the integration code into `master`. @isbluis could you make it so these new KPs will appear as options in the DSL builder dropdown? (all documentation has been updated from my end)

Hi @amykglen ; I have updated this in `master`.

**Comment by finnagin** [comment] 2021-07-20 02:25
I've rolled that out to [/test](http://arax.ncats.io/test). Looks like expanding with ICEES-Asthma is showing up on the drop down menu.

**Comment by finnagin** [comment] 2021-07-20 02:30
@amykglen I'll ping the general slack channel again and roll out to the other endpoints.

**Comment by amykglen** [comment] 2021-07-20 02:31
awesome, thanks @isbluis and @finnagin!

**Comment by dkoslicki** [comment] 2021-07-20 03:13
@amykglen
>re: 1) hmm, when I click on that link, the log shows that ICEES-DILI found results and ICEES-Asthma did not produce results 

Right,  hence my confusion since the single result was regarding asthma. But re-running the query, things seem to be in order. This doesn't explain the COHD issue though, but that's a separate issue. Thanks all for the quick work on this one!

**Comment by karafecho** [comment] 2021-07-21 14:03
Yes, thanks folks!

**Closed** 2021-07-23 17:35 UTC
Labels: KP integration, expand, verify in next deployment
